# Generated by Django 5.1.15 on 2026-03-09 18:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New Conversation', help_text='Auto-generated or user-defined conversation title', max_length=255)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('context_metadata', models.JSONField(blank=True, default=dict, help_text='Conversation context: topics discussed, vault items referenced, etc.')),
                ('total_tokens_used', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('tokens_used', models.IntegerField(default=0, help_text='Tokens consumed for this message (input + output for assistant)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata: queries triggered, processing time, etc.')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.conversationsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AIQueryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_type', models.CharField(choices=[('password_health', 'Password Health Analysis'), ('breach_check', 'Breach Check'), ('age_analysis', 'Password Age Analysis'), ('risk_assessment', 'Risk Assessment'), ('vault_search', 'Vault Metadata Search'), ('security_summary', 'Security Summary'), ('general', 'General Security Query')], max_length=30)),
                ('query_summary', models.TextField(help_text='Description of what data was queried')),
                ('vault_items_accessed_count', models.IntegerField(default=0, help_text='Number of vault items accessed (metadata only)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_query_logs', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='query_logs', to='ai_assistant.conversationsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='conversationsession',
            index=models.Index(fields=['user', '-last_activity'], name='ai_assistan_user_id_73b0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationsession',
            index=models.Index(fields=['user', 'is_active'], name='ai_assistan_user_id_33936d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'timestamp'], name='ai_assistan_session_b16f2f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['role'], name='ai_assistan_role_f242d3_idx'),
        ),
        migrations.AddIndex(
            model_name='aiquerylog',
            index=models.Index(fields=['user', '-timestamp'], name='ai_assistan_user_id_99744d_idx'),
        ),
        migrations.AddIndex(
            model_name='aiquerylog',
            index=models.Index(fields=['query_type'], name='ai_assistan_query_t_17cd92_idx'),
        ),
    ]
