# Generated by Django 4.2.16 on 2025-10-25 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_email', models.EmailField(help_text='The masked email address', max_length=254, unique=True)),
                ('alias_name', models.CharField(blank=True, help_text='User-friendly name for the alias', max_length=255)),
                ('description', models.TextField(blank=True, help_text='What this alias is used for')),
                ('provider', models.CharField(choices=[('simplelogin', 'SimpleLogin'), ('anonaddy', 'AnonAddy'), ('custom', 'Custom Provider')], default='simplelogin', max_length=20)),
                ('provider_alias_id', models.CharField(blank=True, help_text="ID from the provider's API", max_length=255)),
                ('forwards_to', models.EmailField(help_text='Real email address that receives forwarded emails', max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('emails_received', models.IntegerField(default=0)),
                ('emails_forwarded', models.IntegerField(default=0)),
                ('emails_blocked', models.IntegerField(default=0)),
                ('vault_item_id', models.CharField(blank=True, help_text='Associated password vault item', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_aliases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailMaskingProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('simplelogin', 'SimpleLogin'), ('anonaddy', 'AnonAddy'), ('custom', 'Custom Provider')], max_length=20)),
                ('api_key', models.CharField(help_text='Encrypted API key', max_length=500)),
                ('api_endpoint', models.URLField(blank=True, help_text='Custom API endpoint if applicable')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default provider for new aliases')),
                ('monthly_quota', models.IntegerField(default=0, help_text='Monthly alias creation limit (0 = unlimited)')),
                ('aliases_created_this_month', models.IntegerField(default=0)),
                ('quota_reset_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Masking Provider',
                'verbose_name_plural': 'Email Masking Providers',
                'unique_together': {('user', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='EmailAliasActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('received', 'Email Received'), ('forwarded', 'Email Forwarded'), ('blocked', 'Email Blocked'), ('spam', 'Spam Detected'), ('created', 'Alias Created'), ('deleted', 'Alias Deleted'), ('disabled', 'Alias Disabled'), ('enabled', 'Alias Enabled')], max_length=20)),
                ('sender_email', models.EmailField(blank=True, help_text='Sender of the email (if applicable)', max_length=254)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('alias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='email_masking.emailalias')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['alias', '-timestamp'], name='email_maski_alias_i_3eb6bd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='emailalias',
            index=models.Index(fields=['user', 'status'], name='email_maski_user_id_51e5cd_idx'),
        ),
        migrations.AddIndex(
            model_name='emailalias',
            index=models.Index(fields=['alias_email'], name='email_maski_alias_e_92379f_idx'),
        ),
        migrations.AddIndex(
            model_name='emailalias',
            index=models.Index(fields=['provider', 'provider_alias_id'], name='email_maski_provide_ff4b47_idx'),
        ),
    ]
