# Generated by Django 4.2.16 on 2025-11-25 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_dark_web', '0002_add_pgvector_support'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='breachsource',
            new_name='ml_breach_s_is_acti_c27fb0_idx',
            old_name='ml_breach_s_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='breachsource',
            new_name='ml_breach_s_source__6f2a09_idx',
            old_name='ml_breach_s_source__idx',
        ),
        migrations.RenameIndex(
            model_name='darkwebscrapelog',
            new_name='ml_darkweb__source__daefc5_idx',
            old_name='ml_darkweb_source__idx',
        ),
        migrations.RenameIndex(
            model_name='darkwebscrapelog',
            new_name='ml_darkweb__status_95ecd7_idx',
            old_name='ml_darkweb_status_idx',
        ),
        migrations.RenameIndex(
            model_name='mlbreachdata',
            new_name='ml_breach_d_breach__be4726_idx',
            old_name='ml_breach_d_breach__idx',
        ),
        migrations.RenameIndex(
            model_name='mlbreachdata',
            new_name='ml_breach_d_confide_4d0fb3_idx',
            old_name='ml_breach_d_confid_idx',
        ),
        migrations.RenameIndex(
            model_name='mlbreachdata',
            new_name='ml_breach_d_process_35281a_idx',
            old_name='ml_breach_d_process_idx',
        ),
        migrations.RenameIndex(
            model_name='mlbreachdata',
            new_name='ml_breach_d_source__56a660_idx',
            old_name='ml_breach_d_source__idx2',
        ),
        migrations.RenameIndex(
            model_name='mlbreachmatch',
            new_name='ml_breach_m_user_id_2935b6_idx',
            old_name='ml_breach_m_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='mlbreachmatch',
            new_name='ml_breach_m_similar_cf854a_idx',
            old_name='ml_breach_m_similar_idx',
        ),
        migrations.RenameIndex(
            model_name='mlbreachmatch',
            new_name='ml_breach_m_alert_c_7cac75_idx',
            old_name='ml_breach_m_alert_c_idx',
        ),
        migrations.RenameIndex(
            model_name='usercredentialmonitoring',
            new_name='ml_user_cre_email_h_a84eb2_idx',
            old_name='ml_user_cr_email_h_idx',
        ),
        migrations.RenameIndex(
            model_name='usercredentialmonitoring',
            new_name='ml_user_cre_domain_716910_idx',
            old_name='ml_user_cr_domain_idx',
        ),
        migrations.RenameIndex(
            model_name='usercredentialmonitoring',
            new_name='ml_user_cre_user_id_ee8714_idx',
            old_name='ml_user_cr_user_id_idx',
        ),
    ]
