# Generated by Django 5.1.15 on 2026-04-17 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decentralized_identity', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='signinchallenge',
            new_name='decentraliz_did_str_2e093f_idx',
            old_name='did_challenge_consumed_idx',
        ),
        migrations.RenameIndex(
            model_name='userdid',
            new_name='decentraliz_user_id_9fe34a_idx',
            old_name='did_userdid_primary_idx',
        ),
        migrations.RenameIndex(
            model_name='verifiablecredential',
            new_name='decentraliz_status_4139a9_idx',
            old_name='did_vc_status_idx',
        ),
        migrations.RenameIndex(
            model_name='verifiablecredential',
            new_name='decentraliz_subject_125adc_idx',
            old_name='did_vc_subject_status_idx',
        ),
    ]
