# Generated by Django 4.2.27 on 2026-01-23 12:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadDrop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude of dead drop location', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude of dead drop location', max_digits=9)),
                ('radius_meters', models.IntegerField(default=50, help_text='Geofence radius in meters', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(1000)])),
                ('location_hint', models.TextField(blank=True, help_text='Human-readable hint to find exact spot')),
                ('encrypted_secret', models.BinaryField(help_text='Full encrypted secret (only for verification)')),
                ('secret_hash', models.CharField(help_text='BLAKE3 hash of original secret', max_length=128)),
                ('encryption_algorithm', models.CharField(default='XChaCha20-Poly1305', max_length=50)),
                ('required_fragments', models.IntegerField(default=3, help_text='k in (k,n) threshold - minimum fragments needed', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)])),
                ('total_fragments', models.IntegerField(default=5, help_text='n in (k,n) threshold - total fragments created', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(20)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When the dead drop expires')),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Distribution'), ('distributed', 'Fragments Distributed'), ('active', 'Active - Ready for Collection'), ('collected', 'Collected'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('recipient_email', models.EmailField(blank=True, help_text='Optional: restrict to specific recipient', max_length=254, null=True)),
                ('recipient_public_key', models.TextField(blank=True, help_text='X25519 public key for recipient-only decryption', null=True)),
                ('access_code_hash', models.CharField(blank=True, help_text='Optional PIN/access code (hashed)', max_length=128, null=True)),
                ('max_attempts', models.IntegerField(default=3, help_text='Maximum collection attempts before lockout')),
                ('require_ble_verification', models.BooleanField(default=True, help_text='Require BLE beacon detection')),
                ('require_nfc_tap', models.BooleanField(default=False, help_text='Require NFC tap for verification')),
                ('min_ble_nodes_required', models.IntegerField(default=2, help_text='Minimum BLE nodes that must be visible')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dead_drops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dead Drop',
                'verbose_name_plural': 'Dead Drops',
                'db_table': 'mesh_dead_drop',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeadDropFragment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fragment_index', models.IntegerField(help_text='Share index (x-coordinate in Shamir)')),
                ('encrypted_fragment', models.BinaryField(help_text='Encrypted share data')),
                ('fragment_hash', models.CharField(help_text='BLAKE3 hash for integrity verification', max_length=128)),
                ('storage_type', models.CharField(choices=[('self', 'Creator Device'), ('mesh_node', 'BLE Mesh Node'), ('trusted_device', 'Trusted Friend Device'), ('cloud_backup', 'Encrypted Cloud Backup')], default='mesh_node', max_length=20)),
                ('node_public_key', models.TextField(blank=True, help_text='Public key used to encrypt for this node', null=True)),
                ('is_distributed', models.BooleanField(default=False)),
                ('distributed_at', models.DateTimeField(blank=True, null=True)),
                ('last_ping', models.DateTimeField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_collected', models.BooleanField(default=False)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_fragments', to=settings.AUTH_USER_MODEL)),
                ('dead_drop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragments', to='mesh_deaddrop.deaddrop')),
            ],
            options={
                'verbose_name': 'Dead Drop Fragment',
                'verbose_name_plural': 'Dead Drop Fragments',
                'db_table': 'mesh_dead_drop_fragment',
                'ordering': ['fragment_index'],
            },
        ),
        migrations.CreateModel(
            name='NFCBeacon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_id', models.CharField(help_text='NFC tag unique identifier', max_length=64, unique=True)),
                ('tag_signature', models.CharField(help_text='Cryptographic signature on tag', max_length=256)),
                ('current_challenge', models.CharField(blank=True, help_text='Current challenge for rotation', max_length=64)),
                ('challenge_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_tapped', models.DateTimeField(blank=True, null=True)),
                ('tap_count', models.IntegerField(default=0)),
                ('dead_drop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfc_beacons', to='mesh_deaddrop.deaddrop')),
            ],
            options={
                'verbose_name': 'NFC Beacon',
                'verbose_name_plural': 'NFC Beacons',
                'db_table': 'mesh_nfc_beacon',
            },
        ),
        migrations.CreateModel(
            name='MeshNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_key', models.TextField(help_text='X25519 public key for encryption')),
                ('private_key_encrypted', models.BinaryField(blank=True, help_text='Encrypted private key (only stored on device)', null=True)),
                ('device_name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('phone_android', 'Android Phone'), ('phone_ios', 'iPhone'), ('tablet', 'Tablet'), ('raspberry_pi', 'Raspberry Pi'), ('dedicated', 'Dedicated Node'), ('other', 'Other Device')], default='phone_android', max_length=20)),
                ('ble_address', models.CharField(help_text='BLE MAC address (XX:XX:XX:XX:XX:XX)', max_length=17)),
                ('device_fingerprint', models.CharField(blank=True, help_text='Device hardware fingerprint', max_length=128)),
                ('last_known_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_known_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('is_available_for_storage', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('max_fragments', models.IntegerField(default=10, help_text='Maximum fragments this node can store')),
                ('current_fragment_count', models.IntegerField(default=0)),
                ('trust_score', models.FloatField(default=0.5, help_text='Trust score 0-1 based on reliability', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('successful_transfers', models.IntegerField(default=0)),
                ('failed_transfers', models.IntegerField(default=0)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesh_nodes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mesh Node',
                'verbose_name_plural': 'Mesh Nodes',
                'db_table': 'mesh_node',
            },
        ),
        migrations.CreateModel(
            name='LocationVerificationCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy_meters', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(choices=[('gps', 'GPS'), ('ble', 'BLE Beacons'), ('wifi', 'WiFi'), ('cell', 'Cell Tower'), ('nfc', 'NFC Tap')], max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_method', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_cache', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Location Cache',
                'verbose_name_plural': 'Location Cache Entries',
                'db_table': 'mesh_location_cache',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='FragmentTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_time', models.DateTimeField(auto_now_add=True)),
                ('transfer_duration_ms', models.IntegerField(blank=True, null=True)),
                ('encryption_method', models.CharField(default='X25519+XChaCha20', max_length=50)),
                ('transfer_successful', models.BooleanField()),
                ('bytes_transferred', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('fragment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='mesh_deaddrop.deaddropfragment')),
                ('from_node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_transfers', to='mesh_deaddrop.meshnode')),
                ('to_node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to='mesh_deaddrop.meshnode')),
            ],
            options={
                'verbose_name': 'Fragment Transfer',
                'verbose_name_plural': 'Fragment Transfers',
                'db_table': 'mesh_fragment_transfer',
                'ordering': ['-transfer_time'],
            },
        ),
        migrations.AddField(
            model_name='deaddropfragment',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stored_fragments', to='mesh_deaddrop.meshnode'),
        ),
        migrations.CreateModel(
            name='DeadDropAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_time', models.DateTimeField(auto_now_add=True)),
                ('claimed_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('claimed_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('claimed_accuracy_meters', models.FloatField(blank=True, null=True)),
                ('gps_verified', models.BooleanField(default=False)),
                ('ble_verified', models.BooleanField(default=False)),
                ('nfc_verified', models.BooleanField(default=False)),
                ('wifi_verified', models.BooleanField(default=False)),
                ('ble_nodes_detected', models.IntegerField(default=0)),
                ('ble_node_ids', models.JSONField(default=list)),
                ('velocity_check_passed', models.BooleanField(default=True)),
                ('location_history_score', models.FloatField(blank=True, help_text='Confidence score from location history analysis', null=True)),
                ('result', models.CharField(choices=[('success', 'Collection Successful'), ('insufficient_fragments', 'Insufficient Fragments'), ('location_failed', 'Location Verification Failed'), ('spoofing_detected', 'GPS Spoofing Detected'), ('ble_failed', 'BLE Verification Failed'), ('nfc_failed', 'NFC Verification Failed'), ('access_code_wrong', 'Wrong Access Code'), ('expired', 'Dead Drop Expired'), ('locked_out', 'Locked Out'), ('error', 'Technical Error')], max_length=30)),
                ('fragments_collected', models.IntegerField(default=0)),
                ('reconstruction_successful', models.BooleanField(default=False)),
                ('access_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=128)),
                ('error_message', models.TextField(blank=True)),
                ('accessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dead_drop_accesses', to=settings.AUTH_USER_MODEL)),
                ('dead_drop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='mesh_deaddrop.deaddrop')),
            ],
            options={
                'verbose_name': 'Dead Drop Access',
                'verbose_name_plural': 'Dead Drop Accesses',
                'db_table': 'mesh_dead_drop_access',
                'ordering': ['-access_time'],
            },
        ),
        migrations.AddIndex(
            model_name='meshnode',
            index=models.Index(fields=['ble_address'], name='mesh_node_ble_add_98da05_idx'),
        ),
        migrations.AddIndex(
            model_name='meshnode',
            index=models.Index(fields=['is_online', 'is_available_for_storage'], name='mesh_node_is_onli_0aa1a7_idx'),
        ),
        migrations.AddIndex(
            model_name='meshnode',
            index=models.Index(fields=['last_known_latitude', 'last_known_longitude'], name='mesh_node_last_kn_2f762b_idx'),
        ),
        migrations.AddIndex(
            model_name='locationverificationcache',
            index=models.Index(fields=['user', '-recorded_at'], name='mesh_locati_user_id_4c42f5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deaddropfragment',
            unique_together={('dead_drop', 'fragment_index')},
        ),
        migrations.AddIndex(
            model_name='deaddropaccess',
            index=models.Index(fields=['dead_drop', '-access_time'], name='mesh_dead_d_dead_dr_cb05c0_idx'),
        ),
        migrations.AddIndex(
            model_name='deaddropaccess',
            index=models.Index(fields=['accessor', '-access_time'], name='mesh_dead_d_accesso_fe671e_idx'),
        ),
        migrations.AddIndex(
            model_name='deaddropaccess',
            index=models.Index(fields=['result', '-access_time'], name='mesh_dead_d_result_98fc2c_idx'),
        ),
        migrations.AddIndex(
            model_name='deaddrop',
            index=models.Index(fields=['owner', '-created_at'], name='mesh_dead_d_owner_i_4fffb2_idx'),
        ),
        migrations.AddIndex(
            model_name='deaddrop',
            index=models.Index(fields=['status', 'expires_at'], name='mesh_dead_d_status_88d311_idx'),
        ),
        migrations.AddIndex(
            model_name='deaddrop',
            index=models.Index(fields=['latitude', 'longitude'], name='mesh_dead_d_latitud_75d7fd_idx'),
        ),
    ]
