# Generated by Django 5.1.15 on 2026-04-19 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesh_deaddrop', '0003_pendingfragmentsync'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pendingfragmentsync',
            new_name='mesh_pendin_node_id_50252c_idx',
            old_name='mesh_sync_node_status_idx',
        ),
        migrations.RenameIndex(
            model_name='pendingfragmentsync',
            new_name='mesh_pendin_status_7b21ec_idx',
            old_name='mesh_sync_status_next_idx',
        ),
        migrations.RenameIndex(
            model_name='pendingfragmentsync',
            new_name='mesh_pendin_dead_dr_a95c25_idx',
            old_name='mesh_sync_drop_status_idx',
        ),
    ]
