# Generated by Django 4.2 on 2025-06-06 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#4A6CF7', max_length=20)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='vault.vaultfolder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='VaultBackup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('encrypted_data', models.TextField()),
                ('size', models.IntegerField(default=0)),
                ('cloud_storage_path', models.CharField(blank=True, max_length=255, null=True)),
                ('cloud_sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSalt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt', models.BinaryField()),
                ('auth_hash', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vault_salt', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EncryptedVaultItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_id', models.CharField(help_text='Client-generated ID', max_length=64, unique=True)),
                ('item_type', models.CharField(choices=[('password', 'Password'), ('card', 'Payment Card'), ('identity', 'Identity'), ('note', 'Secure Note')], max_length=20)),
                ('encrypted_data', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags for categorization')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('favorite', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='vault.vaultfolder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DeletedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=64)),
                ('deleted_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BreachAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breach_name', models.CharField(max_length=255)),
                ('breach_date', models.DateField(blank=True, null=True)),
                ('breach_description', models.TextField(blank=True)),
                ('data_type', models.CharField(choices=[('password', 'Password'), ('email', 'Email'), ('username', 'Username'), ('phone', 'Phone Number'), ('other', 'Other')], default='password', max_length=20)),
                ('identifier', models.CharField(help_text='Item identifier (email/username)', max_length=255)),
                ('exposed_data', models.JSONField(blank=True, default=dict)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notified', models.BooleanField(default=False)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breach_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create_item', 'Create Item'), ('update_item', 'Update Item'), ('delete_item', 'Delete Item'), ('access_item', 'Access Item'), ('login', 'Login'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('export_data', 'Export Data'), ('import_data', 'Import Data')], max_length=20)),
                ('item_type', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='encryptedvaultitem',
            index=models.Index(fields=['user', 'item_type'], name='vault_encry_user_id_d53284_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptedvaultitem',
            index=models.Index(fields=['user', 'deleted'], name='vault_encry_user_id_d84f4a_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptedvaultitem',
            index=models.Index(fields=['item_id'], name='vault_encry_item_id_b97898_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptedvaultitem',
            index=models.Index(fields=['folder'], name='vault_encry_folder__3905e4_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptedvaultitem',
            index=models.Index(fields=['user', 'item_type', 'favorite'], name='vault_encry_user_id_08295f_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptedvaultitem',
            index=models.Index(fields=['user', 'updated_at'], name='vault_encry_user_id_3d2ae1_idx'),
        ),
        migrations.AddIndex(
            model_name='deleteditem',
            index=models.Index(fields=['user', 'deleted_at'], name='vault_delet_user_id_edf097_idx'),
        ),
        migrations.AddIndex(
            model_name='deleteditem',
            index=models.Index(fields=['item_id'], name='vault_delet_item_id_476085_idx'),
        ),
        migrations.AddIndex(
            model_name='breachalert',
            index=models.Index(fields=['user', 'resolved'], name='vault_breac_user_id_e265df_idx'),
        ),
        migrations.AddIndex(
            model_name='breachalert',
            index=models.Index(fields=['user', 'breach_name', 'identifier'], name='vault_breac_user_id_e7cb2b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'action'], name='vault_audit_user_id_5f5219_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='vault_audit_timesta_686197_idx'),
        ),
    ]
