# Generated by Django 4.2.16 on 2025-11-19 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vault', '0002_add_crypto_versioning'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('require_2fa', models.BooleanField(default=False, help_text='Require 2FA to access this folder')),
                ('allow_export', models.BooleanField(default=False, help_text='Allow members to export items')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_shared_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedVaultItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vault_item_id', models.CharField(help_text='ID of the original vault item', max_length=255)),
                ('encrypted_folder_key', models.TextField(help_text='Folder key encrypted for each user')),
                ('encrypted_metadata', models.TextField(blank=True, help_text='Encrypted item metadata (name, type, etc.)')),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_items', to='vault.sharedfolder')),
                ('shared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_vault_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-shared_at'],
                'indexes': [models.Index(fields=['folder', 'is_active'], name='vault_share_folder__c0f312_idx')],
                'unique_together': {('folder', 'vault_item_id')},
            },
        ),
        migrations.CreateModel(
            name='SharedFolderMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('can_invite', models.BooleanField(default=False, help_text='Can invite other users')),
                ('can_edit_items', models.BooleanField(default=False, help_text='Can edit items in folder')),
                ('can_delete_items', models.BooleanField(default=False, help_text='Can delete items from folder')),
                ('can_export', models.BooleanField(default=False, help_text='Can export items')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('invitation_token', models.CharField(blank=True, max_length=255, unique=True)),
                ('invitation_expires_at', models.DateTimeField(blank=True, null=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='vault.sharedfolder')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_folder_invitations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_folder_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-invited_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='vault_share_user_id_e87673_idx'), models.Index(fields=['folder', 'status'], name='vault_share_folder__ab28e9_idx')],
                'unique_together': {('folder', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SharedFolderKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_folder_key', models.TextField(help_text="Folder key encrypted with user's public ECC key")),
                ('key_version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encrypted_keys', to='vault.sharedfolder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_folder_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('folder', 'user', 'key_version')},
            },
        ),
        migrations.CreateModel(
            name='SharedFolderActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('created', 'Folder Created'), ('member_added', 'Member Added'), ('member_removed', 'Member Removed'), ('member_role_changed', 'Member Role Changed'), ('item_added', 'Item Added'), ('item_removed', 'Item Removed'), ('item_viewed', 'Item Viewed'), ('item_edited', 'Item Edited'), ('invitation_sent', 'Invitation Sent'), ('invitation_accepted', 'Invitation Accepted'), ('invitation_declined', 'Invitation Declined'), ('access_revoked', 'Access Revoked')], max_length=30)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='vault.sharedfolder')),
                ('target_user', models.ForeignKey(blank=True, help_text='User affected by this activity (e.g., invited user)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_folder_activities', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_folder_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Shared Folder Activities',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['folder', '-timestamp'], name='vault_share_folder__e33212_idx'), models.Index(fields=['user', '-timestamp'], name='vault_share_user_id_a6d2bc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sharedfolder',
            index=models.Index(fields=['owner', 'is_active'], name='vault_share_owner_i_d57a43_idx'),
        ),
    ]
