# Generated by Django 4.2.16 on 2025-11-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_sharedfolder_sharedvaultitem_sharedfoldermember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedvaultitem',
            name='cached_breach_check',
            field=models.BinaryField(blank=True, help_text='Cached FHE-computed breach check result', null=True),
        ),
        migrations.AddField(
            model_name='encryptedvaultitem',
            name='cached_strength_score',
            field=models.BinaryField(blank=True, help_text='Cached FHE-computed password strength score', null=True),
        ),
        migrations.AddField(
            model_name='encryptedvaultitem',
            name='domain_fuzzy_hash',
            field=models.CharField(blank=True, help_text='Fuzzy hash for similarity search (OPE encrypted)', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='encryptedvaultitem',
            name='encrypted_domain_hash',
            field=models.BinaryField(blank=True, help_text='Encrypted domain hash for FHE search', null=True),
        ),
        migrations.AddField(
            model_name='encryptedvaultitem',
            name='encrypted_username_hash',
            field=models.BinaryField(blank=True, help_text='Encrypted username hash for FHE search', null=True),
        ),
        migrations.AddField(
            model_name='encryptedvaultitem',
            name='fhe_cache_timestamp',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last FHE cache update', null=True),
        ),
        migrations.AddField(
            model_name='encryptedvaultitem',
            name='fhe_password',
            field=models.BinaryField(blank=True, help_text='FHE encrypted password (SEAL CKKS ciphertext)', null=True),
        ),
        migrations.AddIndex(
            model_name='encryptedvaultitem',
            index=models.Index(fields=['user', 'domain_fuzzy_hash'], name='vault_encry_user_id_5c34f7_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptedvaultitem',
            index=models.Index(fields=['fhe_cache_timestamp'], name='vault_encry_fhe_cac_33bacb_idx'),
        ),
    ]
