# Generated by Django 5.1.15 on 2026-04-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0005_add_vault_user_active_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='breachalert',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='breachalert',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
