# Generated by Django 5.1.15 on 2026-04-14 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0006_breachalert_is_read_breachalert_read_at'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='encryptedvaultitem',
            name='idx_vault_user_active',
        ),
    ]
