# Generated by Django 5.1.15 on 2026-04-19 05:42

import vault.models.vault_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0008_encryptedvaultitem_name_hash_search_and_item_id_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedvaultitem',
            name='item_id',
            field=models.CharField(default=vault.models.vault_models._generate_item_id, help_text='Client-generated ID', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='encryptedvaultitem',
            name='name_hash',
            field=models.CharField(blank=True, default='', help_text='Hashed item name for equality lookups', max_length=128),
        ),
        migrations.AlterField(
            model_name='encryptedvaultitem',
            name='name_search',
            field=models.CharField(blank=True, default='', help_text='Tokenized/normalized name for full-text style search', max_length=255),
        ),
    ]
