# Generated by Django 4.2.16 on 2025-11-23 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BehavioralRecoveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expected_completion_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_stage', models.CharField(choices=[('initiated', 'Recovery Initiated'), ('typing_challenge', 'Typing Dynamics Challenge'), ('mouse_challenge', 'Mouse Biometrics Challenge'), ('cognitive_challenge', 'Cognitive Challenge'), ('navigation_challenge', 'Navigation Challenge'), ('verification', 'Final Verification'), ('completed', 'Recovery Completed'), ('failed', 'Recovery Failed')], default='initiated', max_length=50)),
                ('samples_collected', models.IntegerField(default=0, help_text='Total behavioral samples collected during recovery')),
                ('challenges_completed', models.IntegerField(default=0)),
                ('challenges_total', models.IntegerField(default=20)),
                ('similarity_scores', models.JSONField(default=dict, help_text='Similarity scores for each challenge type')),
                ('overall_similarity', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed Successfully'), ('failed', 'Failed - Low Similarity'), ('abandoned', 'Abandoned by User'), ('expired', 'Expired - Took Too Long')], default='in_progress', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('user', models.ForeignKey(blank=True, help_text="User may be null initially if email lookup hasn't completed", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recovery_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BehavioralProfileSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period_start', models.DateTimeField(help_text='Start of the time period this snapshot covers')),
                ('period_end', models.DateTimeField(help_text='End of the time period this snapshot covers')),
                ('encrypted_embedding', models.BinaryField(help_text='Encrypted 128-dim behavioral DNA for this time period')),
                ('samples_count', models.IntegerField(default=0, help_text='Number of behavioral samples in this snapshot')),
                ('quality_score', models.FloatField(default=0.0, help_text='Quality/completeness of behavioral data (0-1)')),
                ('dimensional_coverage', models.JSONField(default=dict, help_text='How many dimensions were captured (out of 247)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavioral_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BehavioralCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commitment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('encrypted_embedding', models.BinaryField(help_text='Encrypted 128-dim behavioral DNA vector')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('unlock_conditions', models.JSONField(default=dict, help_text='Similarity threshold, temporal requirements, etc.')),
                ('challenge_type', models.CharField(choices=[('typing', 'Typing Dynamics'), ('mouse', 'Mouse Biometrics'), ('cognitive', 'Cognitive Patterns'), ('navigation', 'UI Navigation'), ('semantic', 'Semantic Behaviors'), ('combined', 'Combined Multi-modal')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('samples_used', models.IntegerField(default=0, help_text='Number of behavioral samples used to create this commitment')),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('kyber_public_key', models.BinaryField(blank=True, help_text='Kyber-768 public key for this commitment (1184 bytes)', null=True)),
                ('kyber_ciphertext', models.BinaryField(blank=True, help_text='Kyber-encapsulated shared secret (1088 bytes)', null=True)),
                ('quantum_encrypted_embedding', models.JSONField(blank=True, help_text='Hybrid Kyber+AES encrypted embedding (complete encrypted data structure)', null=True)),
                ('encryption_algorithm', models.CharField(default='base64', help_text='Encryption algorithm: base64 (legacy), kyber768-aes256gcm (quantum)', max_length=50)),
                ('is_quantum_protected', models.BooleanField(default=False, help_text='Whether this commitment uses post-quantum encryption')),
                ('legacy_encrypted_embedding', models.BinaryField(blank=True, help_text='Original encryption format (preserved during migration)', null=True)),
                ('migrated_to_quantum', models.DateTimeField(blank=True, help_text='Timestamp when migrated to quantum encryption', null=True)),
                ('blockchain_hash', models.CharField(blank=True, db_index=True, help_text='SHA-256 hash for blockchain anchoring (hex string without 0x prefix)', max_length=64, null=True)),
                ('blockchain_anchored', models.BooleanField(default=False, help_text='Whether this commitment has been anchored to blockchain')),
                ('blockchain_anchored_at', models.DateTimeField(blank=True, help_text='Timestamp when anchored to blockchain', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavioral_commitments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creation_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BehavioralChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('challenge_type', models.CharField(choices=[('typing', 'Typing Dynamics'), ('mouse', 'Mouse Biometrics'), ('cognitive', 'Cognitive Patterns'), ('navigation', 'UI Navigation'), ('semantic', 'Semantic Behaviors')], max_length=50)),
                ('challenge_data', models.JSONField(help_text='Specific task/prompt for this challenge (e.g., sentence to type)')),
                ('user_response', models.JSONField(blank=True, help_text="Captured behavioral data from user's response", null=True)),
                ('similarity_score', models.FloatField(blank=True, help_text='Similarity to stored behavioral profile (0-1)', null=True)),
                ('passed', models.BooleanField(blank=True, help_text='Whether this challenge passed the similarity threshold', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken_seconds', models.IntegerField(blank=True, null=True)),
                ('attempt_number', models.IntegerField(default=1, help_text='Number of times this specific challenge was attempted')),
                ('recovery_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='behavioral_recovery.behavioralrecoveryattempt')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_type', models.CharField(choices=[('recovery_initiated', 'Recovery Initiated'), ('challenge_completed', 'Challenge Completed'), ('challenge_failed', 'Challenge Failed'), ('adversarial_detected', 'Adversarial Activity Detected'), ('replay_detected', 'Replay Attack Detected'), ('suspicious_activity', 'Suspicious Activity'), ('recovery_completed', 'Recovery Completed'), ('recovery_failed', 'Recovery Failed')], help_text='Type of event logged', max_length=50)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details about the event')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', help_text='Severity level of the event', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('recovery_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='behavioral_recovery.behavioralrecoveryattempt')),
            ],
            options={
                'ordering': ['-timestamp'],
                'verbose_name': 'Recovery Audit Log',
                'verbose_name_plural': 'Recovery Audit Logs',
            },
        ),
        migrations.AddIndex(
            model_name='behavioralrecoveryattempt',
            index=models.Index(fields=['user', 'status'], name='behavioral__user_id_2e34f6_idx'),
        ),
        migrations.AddIndex(
            model_name='behavioralrecoveryattempt',
            index=models.Index(fields=['attempt_id'], name='behavioral__attempt_22bd0c_idx'),
        ),
        migrations.AddIndex(
            model_name='behavioralrecoveryattempt',
            index=models.Index(fields=['started_at'], name='behavioral__started_8b3e76_idx'),
        ),
        migrations.AddIndex(
            model_name='behavioralprofilesnapshot',
            index=models.Index(fields=['user', 'created_at'], name='behavioral__user_id_8c26b2_idx'),
        ),
        migrations.AddIndex(
            model_name='behavioralcommitment',
            index=models.Index(fields=['user', 'is_active'], name='behavioral__user_id_58fafe_idx'),
        ),
        migrations.AddIndex(
            model_name='behavioralcommitment',
            index=models.Index(fields=['commitment_id'], name='behavioral__commitm_4241b4_idx'),
        ),
        migrations.AddIndex(
            model_name='behavioralchallenge',
            index=models.Index(fields=['recovery_attempt', 'challenge_type'], name='behavioral__recover_df9a37_idx'),
        ),
        migrations.AddIndex(
            model_name='behavioralchallenge',
            index=models.Index(fields=['challenge_id'], name='behavioral__challen_f9ba55_idx'),
        ),
        migrations.AddIndex(
            model_name='recoveryauditlog',
            index=models.Index(fields=['recovery_attempt', '-timestamp'], name='behavioral__recover_0d06d9_idx'),
        ),
        migrations.AddIndex(
            model_name='recoveryauditlog',
            index=models.Index(fields=['event_type', '-timestamp'], name='behavioral__event_t_85d194_idx'),
        ),
        migrations.AddIndex(
            model_name='recoveryauditlog',
            index=models.Index(fields=['severity', '-timestamp'], name='behavioral__severit_7a77dc_idx'),
        ),
    ]
