# Generated by Django 4.2.16 on 2025-11-23 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('behavioral_recovery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_perception', models.IntegerField(blank=True, help_text="User's perceived security level (1=very insecure, 10=very secure)", null=True)),
                ('ease_of_use', models.IntegerField(blank=True, help_text='How easy was the recovery process? (1=very difficult, 10=very easy)', null=True)),
                ('trust_level', models.IntegerField(blank=True, help_text='Trust in the behavioral recovery system (1=no trust, 10=complete trust)', null=True)),
                ('time_perception', models.IntegerField(blank=True, help_text='Was the recovery time acceptable? (1=too long, 5=perfect)', null=True)),
                ('nps_rating', models.IntegerField(blank=True, help_text='How likely to recommend this system? (0=not at all, 10=extremely likely)', null=True)),
                ('feedback_text', models.TextField(blank=True, help_text='Open-ended feedback from user')),
                ('challenge_difficulty', models.IntegerField(blank=True, help_text='Were the challenges appropriate? (1=too hard, 5=perfect, 10=too easy)', null=True)),
                ('would_use_again', models.BooleanField(blank=True, help_text='Would you use behavioral recovery again?', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recovery_attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='behavioral_recovery.behavioralrecoveryattempt')),
            ],
            options={
                'verbose_name': 'Recovery Feedback',
                'verbose_name_plural': 'Recovery Feedback',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryPerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(db_index=True, help_text="Type of metric (e.g., 'blockchain_tx', 'ml_inference', 'recovery_time')", max_length=50)),
                ('value', models.FloatField(help_text='Numeric value of the metric')),
                ('unit', models.CharField(help_text="Unit of measurement (e.g., 'ms', 'seconds', 'percentage', 'USD')", max_length=20)),
                ('metadata', models.JSONField(default=dict, help_text='Additional context and details about this metric')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recovery_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='behavioral_recovery.behavioralrecoveryattempt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_performance_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Performance Metric',
                'verbose_name_plural': 'Performance Metrics',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['metric_type', 'recorded_at'], name='behavioral__metric__c8d50e_idx'), models.Index(fields=['user', 'recorded_at'], name='behavioral__user_id_3d22ce_idx'), models.Index(fields=['recovery_attempt'], name='behavioral__recover_6e6d5b_idx')],
            },
        ),
    ]
