# Generated by Django 5.1.15 on 2026-04-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavioral_recovery', '0002_recoveryfeedback_recoveryperformancemetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='behavioralrecoveryattempt',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
