# Generated by Django 4.2.16 on 2025-11-25 10:28

from django.db import migrations, models
import django.db.models.deletion


def remove_indexes_if_exist(apps, schema_editor):
    """
    Safely remove indexes only if they exist
    """
    db_alias = schema_editor.connection.alias
    
    # Get the table name
    table_name = 'behavioral_recovery_recoveryauditlog'
    
    # List of indexes to remove
    indexes_to_remove = [
        'behavioral__recover_4d1cc7_idx',
        'behavioral__event_t_32f1f6_idx',
        'behavioral__flagged_d08f7a_idx',
    ]
    
    # Try to remove each index, but don't fail if it doesn't exist
    for index_name in indexes_to_remove:
        try:
            with schema_editor.connection.cursor() as cursor:
                # Check if index exists (SQLite specific)
                cursor.execute(
                    "SELECT name FROM sqlite_master WHERE type='index' AND name=?",
                    [index_name]
                )
                if cursor.fetchone():
                    # Index exists, drop it
                    cursor.execute(f"DROP INDEX IF EXISTS {index_name}")
        except Exception as e:
            # Index doesn't exist or couldn't be removed, continue
            pass


def reverse_indexes(apps, schema_editor):
    """
    Reverse operation - do nothing as we can't recreate indexes we don't know about
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('behavioral_recovery', '0002_recoveryfeedback_recoveryperformancemetric'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recoveryauditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Recovery Audit Log', 'verbose_name_plural': 'Recovery Audit Logs'},
        ),
        # Use RunPython to safely remove indexes
        migrations.RunPython(remove_indexes_if_exist, reverse_indexes),
        migrations.RemoveField(
            model_name='recoveryauditlog',
            name='device_fingerprint',
        ),
        migrations.RemoveField(
            model_name='recoveryauditlog',
            name='event_data',
        ),
        migrations.RemoveField(
            model_name='recoveryauditlog',
            name='flagged_for_review',
        ),
        migrations.RemoveField(
            model_name='recoveryauditlog',
            name='geolocation',
        ),
        migrations.RemoveField(
            model_name='recoveryauditlog',
            name='risk_score',
        ),
        migrations.AddField(
            model_name='recoveryauditlog',
            name='details',
            field=models.JSONField(blank=True, default=dict, help_text='Additional details about the event'),
        ),
        migrations.AddField(
            model_name='recoveryauditlog',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', help_text='Severity level of the event', max_length=20),
        ),
        migrations.AlterField(
            model_name='recoveryauditlog',
            name='event_type',
            field=models.CharField(choices=[('recovery_initiated', 'Recovery Initiated'), ('challenge_completed', 'Challenge Completed'), ('challenge_failed', 'Challenge Failed'), ('adversarial_detected', 'Adversarial Activity Detected'), ('replay_detected', 'Replay Attack Detected'), ('suspicious_activity', 'Suspicious Activity'), ('recovery_completed', 'Recovery Completed'), ('recovery_failed', 'Recovery Failed')], help_text='Type of event logged', max_length=50),
        ),
        migrations.AlterField(
            model_name='recoveryauditlog',
            name='recovery_attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='behavioral_recovery.behavioralrecoveryattempt'),
        ),
        migrations.AlterField(
            model_name='recoveryauditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='recoveryauditlog',
            index=models.Index(fields=['recovery_attempt', '-timestamp'], name='behavioral__recover_0d06d9_idx'),
        ),
        migrations.AddIndex(
            model_name='recoveryauditlog',
            index=models.Index(fields=['event_type', '-timestamp'], name='behavioral__event_t_85d194_idx'),
        ),
        migrations.AddIndex(
            model_name='recoveryauditlog',
            index=models.Index(fields=['severity', '-timestamp'], name='behavioral__severit_7a77dc_idx'),
        ),
    ]
