# Generated by Django 4.2.16 on 2025-11-25 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('behavioral_recovery', '0003_alter_recoveryauditlog_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='recoveryauditlog',
            name='behavioral__recover_4d1cc7_idx',
        ),
        migrations.RemoveIndex(
            model_name='recoveryauditlog',
            name='behavioral__event_t_32f1f6_idx',
        ),
        migrations.RemoveIndex(
            model_name='recoveryauditlog',
            name='behavioral__flagged_d08f7a_idx',
        ),
    ]
