# Generated by Django 4.2.27 on 2026-02-07 13:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LivenessSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context', models.CharField(choices=[('login', 'Login Verification'), ('high_security', 'High Security Action'), ('enrollment', 'Initial Enrollment'), ('re_enrollment', 'Re-enrollment'), ('suspicious', 'Suspicious Activity')], default='login', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('passed', 'Passed'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('required_challenges', models.JSONField(default=list, help_text='List of required challenge types for this session')),
                ('completed_challenges', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('overall_liveness_score', models.FloatField(default=0.0, help_text='Aggregated liveness score from all challenges', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('deepfake_probability', models.FloatField(default=0.0, help_text='Probability that input is a deepfake', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('confidence', models.FloatField(default=0.0, help_text='Confidence in the verification result', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('micro_expression_score', models.FloatField(default=0.0)),
                ('gaze_tracking_score', models.FloatField(default=0.0)),
                ('pulse_oximetry_score', models.FloatField(default=0.0)),
                ('thermal_score', models.FloatField(default=0.0)),
                ('texture_artifact_score', models.FloatField(default=0.0)),
                ('total_frames_processed', models.IntegerField(default=0)),
                ('face_detection_rate', models.FloatField(default=0.0)),
                ('device_fingerprint', models.CharField(blank=True, max_length=256)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liveness_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liveness Session',
                'verbose_name_plural': 'Liveness Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThermalReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('frame_number', models.IntegerField()),
                ('average_face_temp_c', models.FloatField(blank=True, help_text='Average facial temperature in Celsius', null=True)),
                ('temp_range_c', models.JSONField(default=dict, help_text='Min/max temperature range on face')),
                ('heat_map_features', models.JSONField(default=dict, help_text='Extracted thermal feature points')),
                ('has_natural_thermal_gradient', models.BooleanField(default=True, help_text='Natural temp gradient from nose/eyes to edges')),
                ('matches_living_tissue_range', models.BooleanField(default=True, help_text='Temperature in expected living tissue range')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thermal_readings', to='biometric_liveness.livenesssession')),
            ],
            options={
                'verbose_name': 'Thermal Reading',
                'verbose_name_plural': 'Thermal Readings',
                'ordering': ['session', 'frame_number'],
            },
        ),
        migrations.CreateModel(
            name='PulseOximetryReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('frame_number', models.IntegerField()),
                ('heart_rate_bpm', models.FloatField(blank=True, help_text='Estimated heart rate in BPM', null=True)),
                ('heart_rate_variability', models.FloatField(blank=True, help_text='Heart rate variability metric', null=True)),
                ('spo2_estimate', models.FloatField(blank=True, help_text='Estimated SpO2 percentage', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('signal_quality', models.FloatField(default=0.0, help_text='Quality of the rPPG signal (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('rgb_means', models.JSONField(default=list, help_text='RGB channel mean values from ROI')),
                ('ppg_signal_segment', models.JSONField(default=list, help_text='Extracted PPG signal segment')),
                ('is_consistent_with_living', models.BooleanField(default=True, help_text='Whether readings are consistent with living tissue')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pulse_readings', to='biometric_liveness.livenesssession')),
            ],
            options={
                'verbose_name': 'Pulse Oximetry Reading',
                'verbose_name_plural': 'Pulse Oximetry Readings',
                'ordering': ['session', 'frame_number'],
            },
        ),
        migrations.CreateModel(
            name='MicroExpressionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('frame_number', models.IntegerField()),
                ('duration_ms', models.IntegerField(help_text='Duration of micro-expression in milliseconds')),
                ('expression_type', models.CharField(choices=[('surprise', 'Surprise'), ('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('fear', 'Fear'), ('disgust', 'Disgust'), ('contempt', 'Contempt'), ('neutral', 'Neutral')], max_length=20)),
                ('intensity', models.FloatField(help_text='Intensity of expression (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('action_units', models.JSONField(default=dict, help_text='Facial Action Coding System units detected')),
                ('onset_natural', models.BooleanField(default=True, help_text='Whether onset timing appears natural')),
                ('offset_natural', models.BooleanField(default=True, help_text='Whether offset timing appears natural')),
                ('asymmetry_score', models.FloatField(default=0.0, help_text='Facial asymmetry (natural faces have some)')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expression_events', to='biometric_liveness.livenesssession')),
            ],
            options={
                'verbose_name': 'Micro Expression Event',
                'verbose_name_plural': 'Micro Expression Events',
                'ordering': ['session', 'frame_number'],
            },
        ),
        migrations.CreateModel(
            name='LivenessSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enable_on_login', models.BooleanField(default=False, help_text='Require liveness check on every login')),
                ('enable_on_sensitive_actions', models.BooleanField(default=True, help_text='Require for sensitive vault operations')),
                ('enable_pulse_detection', models.BooleanField(default=True, help_text='Enable rPPG pulse detection')),
                ('enable_thermal', models.BooleanField(default=False, help_text='Enable thermal camera (if available)')),
                ('challenge_difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('extended_time', models.BooleanField(default=False, help_text='Allow extra time for challenges')),
                ('simplified_challenges', models.BooleanField(default=False, help_text='Use simplified challenge variants')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liveness_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liveness Settings',
                'verbose_name_plural': 'Liveness Settings',
            },
        ),
        migrations.CreateModel(
            name='LivenessProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_calibrated', models.BooleanField(default=False, help_text='Whether profile has been calibrated with baseline data')),
                ('calibration_samples', models.IntegerField(default=0, help_text='Number of calibration sessions completed')),
                ('last_calibration_at', models.DateTimeField(blank=True, null=True)),
                ('baseline_pulse_signature', models.JSONField(default=dict, help_text='Baseline rPPG pulse waveform characteristics')),
                ('baseline_gaze_pattern', models.JSONField(default=dict, help_text='Typical gaze movement patterns and fixation durations')),
                ('baseline_expression_patterns', models.JSONField(default=dict, help_text='Natural micro-expression timing and intensity')),
                ('baseline_thermal_signature', models.JSONField(default=dict, help_text='Facial thermal distribution pattern (if available)')),
                ('profile_confidence', models.FloatField(default=0.0, help_text='Confidence level in profile accuracy (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('liveness_threshold', models.FloatField(default=0.85, help_text='Minimum liveness score required to pass', validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(0.99)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liveness_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liveness Profile',
                'verbose_name_plural': 'Liveness Profiles',
            },
        ),
        migrations.CreateModel(
            name='LivenessChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('challenge_type', models.CharField(choices=[('gaze', 'Gaze Tracking'), ('expression', 'Expression Analysis'), ('cognitive', 'Cognitive Task'), ('blink', 'Blink Detection'), ('pulse', 'Pulse Measurement')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('sequence_number', models.IntegerField(help_text='Order of this challenge in the session')),
                ('challenge_data', models.JSONField(default=dict, help_text='Challenge-specific instructions and parameters')),
                ('expected_response', models.JSONField(default=dict, help_text='Expected response patterns (hashed for security)')),
                ('time_limit_ms', models.IntegerField(default=5000, help_text='Maximum time allowed in milliseconds')),
                ('presented_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_passed', models.BooleanField(null=True)),
                ('score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='biometric_liveness.livenesssession')),
            ],
            options={
                'verbose_name': 'Liveness Challenge',
                'verbose_name_plural': 'Liveness Challenges',
                'ordering': ['session', 'sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='GazeTrackingData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp_ms', models.BigIntegerField(help_text='Milliseconds since challenge start')),
                ('gaze_x', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('gaze_y', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('target_x', models.FloatField(blank=True, null=True)),
                ('target_y', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.0, help_text='Confidence in gaze detection', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_fixation', models.BooleanField(default=False, help_text='Whether this is a fixation point vs saccade')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaze_data', to='biometric_liveness.livenesschallenge')),
            ],
            options={
                'verbose_name': 'Gaze Tracking Data',
                'verbose_name_plural': 'Gaze Tracking Data',
                'ordering': ['challenge', 'timestamp_ms'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response_data', models.JSONField(default=dict, help_text='Extracted response features')),
                ('reaction_time_ms', models.IntegerField(help_text='Time from challenge display to first response')),
                ('total_duration_ms', models.IntegerField(help_text='Total time spent on challenge')),
                ('face_detected', models.BooleanField(default=True)),
                ('multiple_faces_detected', models.BooleanField(default=False)),
                ('blink_detected', models.BooleanField(default=False)),
                ('micro_movement_detected', models.BooleanField(default=False)),
                ('natural_skin_texture', models.BooleanField(default=True)),
                ('texture_liveness_score', models.FloatField(default=0.0)),
                ('depth_liveness_score', models.FloatField(default=0.0)),
                ('motion_liveness_score', models.FloatField(default=0.0)),
                ('client_timestamp', models.BigIntegerField()),
                ('server_received_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='biometric_liveness.livenesschallenge')),
            ],
            options={
                'verbose_name': 'Challenge Response',
                'verbose_name_plural': 'Challenge Responses',
            },
        ),
        migrations.AddIndex(
            model_name='livenesssession',
            index=models.Index(fields=['user', 'status'], name='biometric_l_user_id_ed7697_idx'),
        ),
        migrations.AddIndex(
            model_name='livenesssession',
            index=models.Index(fields=['created_at'], name='biometric_l_created_2a44c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='livenesschallenge',
            unique_together={('session', 'sequence_number')},
        ),
    ]
