# Generated by Django 5.1.15 on 2026-07-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometric_liveness', '0002_add_missing_liveness_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livenesssession',
            name='verdict',
            field=models.CharField(blank=True, choices=[('HIGH_CONFIDENCE_LIVE', 'High confidence live'), ('VERIFIED_LIVE', 'Verified live'), ('LOW_CONFIDENCE', 'Low confidence'), ('SUSPECTED_FAKE', 'Suspected fake'), ('INSUFFICIENT_SIGNAL', 'Insufficient signal'), ('INCONCLUSIVE', 'Inconclusive')], help_text='Final human-readable verdict from complete_session()', max_length=30),
        ),
    ]
