# Generated by Django 5.1.15 on 2026-07-22 07:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometric_liveness', '0003_alter_livenesssession_verdict'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivenessPersistOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(help_text='LivenessSession id the payload belongs to (one record per session)', unique=True)),
                ('payload', models.JSONField(help_text='JSON-safe verdict payload (views._liveness_result_payload)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('abandoned', 'Abandoned')], default='pending', help_text='pending = awaiting re-apply; abandoned = attempts exhausted, kept for operator inspection', max_length=12)),
                ('attempts', models.IntegerField(default=0, help_text='Failed drain attempts so far')),
                ('last_error', models.TextField(blank=True, help_text='Most recent failure (why the row is still here)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Liveness Persist Outbox Record',
                'verbose_name_plural': 'Liveness Persist Outbox Records',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='biometric_l_status_26b75c_idx')],
            },
        ),
    ]
