# Generated by Django 4.2.16 on 2025-11-23 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('behavioral_recovery', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merkle_root', models.CharField(db_index=True, help_text='Root hash of Merkle tree (0x prefixed)', max_length=66, unique=True)),
                ('tx_hash', models.CharField(db_index=True, help_text='Arbitrum transaction hash', max_length=66, unique=True)),
                ('block_number', models.BigIntegerField(help_text='Block number where transaction was mined')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When the batch was anchored')),
                ('batch_size', models.IntegerField(help_text='Number of commitments in this batch')),
                ('network', models.CharField(choices=[('testnet', 'Arbitrum Sepolia Testnet'), ('mainnet', 'Arbitrum One Mainnet')], default='testnet', help_text='Network where commitment was anchored', max_length=20)),
                ('gas_used', models.BigIntegerField(blank=True, help_text='Gas used for the transaction', null=True)),
                ('gas_price_wei', models.BigIntegerField(blank=True, help_text='Gas price in wei', null=True)),
            ],
            options={
                'verbose_name': 'Blockchain Anchor',
                'verbose_name_plural': 'Blockchain Anchors',
                'db_table': 'blockchain_anchors',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PendingCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commitment_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the commitment', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_anchored', models.BooleanField(default=False, help_text='Whether this commitment has been anchored to blockchain')),
                ('commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_anchor', to='behavioral_recovery.behavioralcommitment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_commitments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pending Commitment',
                'verbose_name_plural': 'Pending Commitments',
                'db_table': 'pending_commitments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MerkleProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commitment_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the commitment', max_length=64)),
                ('merkle_root', models.CharField(db_index=True, help_text='Root hash this proof verifies against', max_length=66)),
                ('proof', models.JSONField(help_text='Array of sibling hashes for Merkle proof')),
                ('leaf_index', models.IntegerField(help_text='Position of this leaf in the Merkle tree')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('blockchain_anchor', models.ForeignKey(help_text='The blockchain anchor this proof belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='blockchain.blockchainanchor')),
                ('commitment', models.ForeignKey(help_text='The behavioral commitment this proof is for', on_delete=django.db.models.deletion.CASCADE, related_name='merkle_proofs', to='behavioral_recovery.behavioralcommitment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merkle_proofs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Merkle Proof',
                'verbose_name_plural': 'Merkle Proofs',
                'db_table': 'merkle_proofs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='blockchainanchor',
            index=models.Index(fields=['-timestamp'], name='blockchain__timesta_bfcf41_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchainanchor',
            index=models.Index(fields=['network', '-timestamp'], name='blockchain__network_8c760e_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingcommitment',
            index=models.Index(fields=['is_anchored', 'created_at'], name='pending_com_is_anch_370768_idx'),
        ),
        migrations.AddIndex(
            model_name='merkleproof',
            index=models.Index(fields=['user', '-created_at'], name='merkle_proo_user_id_af16f3_idx'),
        ),
        migrations.AddIndex(
            model_name='merkleproof',
            index=models.Index(fields=['commitment_hash'], name='merkle_proo_commitm_47e3ef_idx'),
        ),
        migrations.AddIndex(
            model_name='merkleproof',
            index=models.Index(fields=['merkle_root'], name='merkle_proo_merkle__9231f2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='merkleproof',
            unique_together={('commitment', 'blockchain_anchor')},
        ),
    ]
