# Generated by Django 4.2.16 on 2025-11-23 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainanchor',
            name='submitter_address',
            field=models.CharField(blank=True, help_text='Address that submitted the transaction', max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='merkleproof',
            name='verified',
            field=models.BooleanField(default=False, help_text='Whether this proof has been verified'),
        ),
        migrations.AddField(
            model_name='merkleproof',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When this proof was verified', null=True),
        ),
        migrations.AddField(
            model_name='pendingcommitment',
            name='anchored_at',
            field=models.DateTimeField(blank=True, help_text='When this commitment was anchored', null=True),
        ),
        migrations.AddField(
            model_name='pendingcommitment',
            name='blockchain_anchor',
            field=models.ForeignKey(blank=True, help_text='The blockchain anchor this was included in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_commitments', to='blockchain.blockchainanchor'),
        ),
    ]
