# Generated by Django 5.1.15 on 2026-03-30 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TOTPDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Authenticator', help_text='User-friendly device name (e.g., "Google Authenticator")', max_length=100)),
                ('key', models.CharField(help_text='Base32-encoded TOTP secret key', max_length=80)),
                ('digits', models.PositiveSmallIntegerField(default=6, help_text='Number of digits in the OTP (6 or 8)')),
                ('step', models.PositiveIntegerField(default=30, help_text='Time step in seconds')),
                ('t0', models.PositiveIntegerField(default=0, help_text='Unix time start (usually 0)')),
                ('tolerance', models.PositiveSmallIntegerField(default=1, help_text='Number of time steps to tolerate for clock skew')),
                ('last_t', models.BigIntegerField(default=-1, help_text='Last successfully verified time step (replay protection)')),
                ('confirmed', models.BooleanField(default=False, help_text='Whether the device has been confirmed by verifying a token')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totp_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TOTP Device',
                'verbose_name_plural': 'TOTP Devices',
                'indexes': [models.Index(fields=['user', 'confirmed'], name='two_factor__user_id_3ca023_idx')],
            },
        ),
    ]
