# Generated by Django 5.1.15 on 2026-04-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_destruct', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='selfdestructpolicy',
            new_name='self_destru_user_id_3947d3_idx',
            old_name='sd_policy_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='selfdestructpolicy',
            new_name='self_destru_expires_6225b5_idx',
            old_name='sd_policy_expires_idx',
        ),
        migrations.AlterField(
            model_name='selfdestructpolicy',
            name='kinds',
            field=models.JSONField(default=list, help_text='Subset of PolicyKind values; multiple may be active.'),
        ),
    ]
