# Generated by Django 4.2 on 2025-05-02 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('access_type', models.CharField(choices=[('view', 'View Only'), ('full', 'Full Access')], default='view', max_length=10)),
                ('waiting_period_hours', models.IntegerField(default=24)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emergency_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_access_to', to=settings.AUTH_USER_MODEL)),
                ('vault_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('emergency_contact', 'vault_owner')},
            },
        ),
        migrations.CreateModel(
            name='EmergencyAccessRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Waiting Period'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('auto_approved', 'Automatically Approved'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('access_granted_at', models.DateTimeField(blank=True, null=True)),
                ('auto_approve_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('access_key', models.CharField(blank=True, max_length=64)),
                ('emergency_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='user.emergencycontact')),
            ],
        ),
    ]
