/**
 * Frontend ⇔ Backend base64url parity vectors.
 *
 * The Python backend uses ``base64.urlsafe_b64encode(x).rstrip(b'=')``
 * for all PRE fields on the wire. The frontend must produce the
 * byte-for-byte same encoding or the server's
 * ``CreateShareSerializer`` will reject the payload.
 *
 * These vectors were generated by:
 *
 *     python -c "import base64, os; \
 *         b=bytes.fromhex('...'); \
 *         print(base64.urlsafe_b64encode(b).rstrip(b'=').decode())"
 *
 * If this test starts failing, either the JS encoder diverged
 * (fix `preB64.encode`), or someone changed the backend encoding
 * (update both this file and fhe_sharing/serializers._Base64BytesField).
 */

import { describe, expect, test } from 'vitest';
import { preB64 } from '../preClient';

const VECTORS = [
  { hex: '00',                              b64u: 'AA' },
  { hex: '0102',                            b64u: 'AQI' },
  { hex: '010203',                          b64u: 'AQID' },
  { hex: '01020304',                        b64u: 'AQIDBA' },
  { hex: 'fbfcfdfeff',                      b64u: '-_z9_v8' },
  // typical umbral capsule size — 152 bytes of entropy
  { hex: Array.from({ length: 152 }, (_, i) => (i * 7 % 256).toString(16).padStart(2, '0')).join(''),
    b64u: (() => {
      const bytes = Array.from({ length: 152 }, (_, i) => i * 7 % 256);
      return _pyUrlSafe(bytes);
    })() },
];

function _pyUrlSafe(bytes) {
  // Pure-JS mirror of `base64.urlsafe_b64encode(x).rstrip(b'=')`.
  const std = btoa(bytes.map((b) => String.fromCharCode(b)).join(''));
  return std.replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

function _hexToBytes(s) {
  const out = new Uint8Array(s.length / 2);
  for (let i = 0; i < out.length; i += 1) {
    out[i] = parseInt(s.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}

describe('PRE wire-format parity with Python backend', () => {
  test.each(VECTORS)('encode($hex) = $b64u', ({ hex, b64u }) => {
    const bytes = _hexToBytes(hex);
    expect(preB64.encode(bytes)).toBe(b64u);
  });

  test.each(VECTORS)('decode($b64u) = hex($hex)', ({ hex, b64u }) => {
    const bytes = preB64.decode(b64u);
    const actual = Array.from(bytes).map((b) => b.toString(16).padStart(2, '0')).join('');
    expect(actual).toBe(hex);
  });
});

describe('round-trip for random byte strings', () => {
  test('100 random round-trips preserve bytes', () => {
    const rng = () => Math.floor(Math.random() * 256);
    for (let trial = 0; trial < 100; trial += 1) {
      const len = 1 + Math.floor(Math.random() * 200);
      const bytes = new Uint8Array(Array.from({ length: len }, rng));
      const enc = preB64.encode(bytes);
      expect(enc).not.toContain('=');
      expect(enc).not.toContain('+');
      expect(enc).not.toContain('/');
      const dec = preB64.decode(enc);
      expect(Array.from(dec)).toEqual(Array.from(bytes));
    }
  });
});
