# Generated by Django 5.1.15 on 2026-03-14 18:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vault', '0004_encryptedvaultitem_cached_breach_check_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable name for this share group', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_share_groups', to=settings.AUTH_USER_MODEL)),
                ('vault_item', models.ForeignKey(help_text='The vault item being shared in this group', on_delete=django.db.models.deletion.CASCADE, related_name='share_groups', to='vault.encryptedvaultitem')),
            ],
            options={
                'verbose_name': 'Share Group',
                'verbose_name_plural': 'Share Groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomomorphicShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_autofill_token', models.BinaryField(help_text='FHE-encrypted autofill circuit token. This is the encrypted payload that can fill form fields but CANNOT be decrypted to reveal the password. Created using create_autofill_circuit().')),
                ('encrypted_domain_binding', models.TextField(blank=True, default='', help_text='JSON-serialized list of domains where this token can autofill. If empty, the token works on any domain (less secure).')),
                ('token_metadata', models.JSONField(blank=True, default=dict, help_text='Metadata: FHE circuit parameters, key versions, creation device info. No sensitive data.')),
                ('permission_level', models.CharField(choices=[('autofill_only', 'Autofill Only (cannot view password)')], default='autofill_only', help_text='Permission level. FHE shares are always autofill_only.', max_length=30)),
                ('can_autofill', models.BooleanField(default=True)),
                ('can_view_password', models.BooleanField(default=False, help_text='Always False for FHE shares — the whole point of the feature')),
                ('can_copy_password', models.BooleanField(default=False, help_text='Always False for FHE shares')),
                ('max_uses', models.IntegerField(blank=True, help_text='Maximum number of autofill uses. Null = unlimited.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
                ('use_count', models.IntegerField(default=0, help_text='How many times the autofill token has been used')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this share expires. Null = no expiration.', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this share is currently active')),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(help_text='User who owns the original password', on_delete=django.db.models.deletion.CASCADE, related_name='sent_homomorphic_shares', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(help_text='User who can USE but not SEE the password', on_delete=django.db.models.deletion.CASCADE, related_name='received_homomorphic_shares', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, help_text='User who revoked this share', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_shares', to=settings.AUTH_USER_MODEL)),
                ('vault_item', models.ForeignKey(help_text='The original vault item being shared', on_delete=django.db.models.deletion.CASCADE, related_name='homomorphic_shares', to='vault.encryptedvaultitem')),
                ('group', models.ForeignKey(blank=True, help_text='Optional share group this belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shares', to='fhe_sharing.sharegroup')),
            ],
            options={
                'verbose_name': 'Homomorphic Share',
                'verbose_name_plural': 'Homomorphic Shares',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('share_created', 'Share Created'), ('autofill_used', 'Autofill Used'), ('autofill_denied', 'Autofill Denied'), ('share_revoked', 'Share Revoked'), ('share_expired', 'Share Expired'), ('domain_mismatch', 'Domain Mismatch'), ('usage_limit_reached', 'Usage Limit Reached'), ('share_viewed', 'Share Details Viewed')], max_length=30)),
                ('domain', models.CharField(blank=True, default='', help_text='Domain where autofill was attempted', max_length=255)),
                ('success', models.BooleanField(default=True)),
                ('failure_reason', models.CharField(blank=True, default='', help_text='Reason for failure (if success=False)', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional context (device info, etc.)')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('share', models.ForeignKey(help_text='The share this log entry relates to', on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='fhe_sharing.homomorphicshare')),
                ('user', models.ForeignKey(help_text='The user who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Share Access Log',
                'verbose_name_plural': 'Share Access Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['share', '-timestamp'], name='fhe_sharing_share_i_c9c9e7_idx'), models.Index(fields=['user', '-timestamp'], name='fhe_sharing_user_id_9df180_idx'), models.Index(fields=['action', '-timestamp'], name='fhe_sharing_action_cb3eb1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sharegroup',
            index=models.Index(fields=['owner', '-created_at'], name='fhe_sharing_owner_i_65782b_idx'),
        ),
        migrations.AddIndex(
            model_name='sharegroup',
            index=models.Index(fields=['vault_item'], name='fhe_sharing_vault_i_58fe04_idx'),
        ),
        migrations.AddIndex(
            model_name='homomorphicshare',
            index=models.Index(fields=['owner', 'is_active', '-created_at'], name='fhe_sharing_owner_i_968301_idx'),
        ),
        migrations.AddIndex(
            model_name='homomorphicshare',
            index=models.Index(fields=['recipient', 'is_active', '-created_at'], name='fhe_sharing_recipie_8673a6_idx'),
        ),
        migrations.AddIndex(
            model_name='homomorphicshare',
            index=models.Index(fields=['vault_item', 'is_active'], name='fhe_sharing_vault_i_128cc7_idx'),
        ),
        migrations.AddIndex(
            model_name='homomorphicshare',
            index=models.Index(fields=['expires_at'], name='fhe_sharing_expires_fa81e2_idx'),
        ),
        migrations.AddIndex(
            model_name='homomorphicshare',
            index=models.Index(fields=['group'], name='fhe_sharing_group_i_0fa554_idx'),
        ),
        migrations.AddConstraint(
            model_name='homomorphicshare',
            constraint=models.CheckConstraint(condition=models.Q(('can_view_password', False)), name='fhe_share_no_view_password'),
        ),
        migrations.AddConstraint(
            model_name='homomorphicshare',
            constraint=models.CheckConstraint(condition=models.Q(('can_copy_password', False)), name='fhe_share_no_copy_password'),
        ),
    ]
