# Generated by Django 4.2 on 2025-05-04 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logging_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryAttemptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('attempt_type', models.CharField(choices=[('validate_key', 'Validate Recovery Key'), ('get_vault', 'Get Encrypted Vault'), ('reset_password', 'Reset Password'), ('recovery_success', 'Recovery Success')], max_length=20)),
                ('result', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], max_length=10)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('region', models.CharField(blank=True, max_length=2, null=True)),
                ('browser_family', models.CharField(blank=True, max_length=20, null=True)),
                ('os_family', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='recoveryattemptlog',
            index=models.Index(fields=['timestamp'], name='logging_man_timesta_08258b_idx'),
        ),
        migrations.AddIndex(
            model_name='recoveryattemptlog',
            index=models.Index(fields=['user', 'timestamp'], name='logging_man_user_id_fab601_idx'),
        ),
        migrations.AddIndex(
            model_name='recoveryattemptlog',
            index=models.Index(fields=['attempt_type', 'result'], name='logging_man_attempt_be578d_idx'),
        ),
    ]
