# Generated by Django 5.1.15 on 2026-04-14 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_manager', '0002_recoveryattemptlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoveryattemptlog',
            name='browser_family',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='recoveryattemptlog',
            name='os_family',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['request_path', 'timestamp'], name='logging_man_request_367ab9_idx'),
        ),
    ]
