# Generated by Django 5.1.15 on 2026-04-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='heartbeatsession',
            new_name='heartbeat_s_user_id_835a49_idx',
            old_name='hb_session_u_t_idx',
        ),
        migrations.RenameIndex(
            model_name='heartbeatsession',
            new_name='heartbeat_s_user_id_7b9c1c_idx',
            old_name='hb_session_u_s_idx',
        ),
        migrations.AlterField(
            model_name='heartbeatevent',
            name='decision',
            field=models.CharField(help_text='allow|deny|duress|reject', max_length=12),
        ),
        migrations.AlterField(
            model_name='heartbeatprofile',
            name='duress_rmssd_sigma',
            field=models.FloatField(default=2.0, help_text='Duress trigger: RMSSD must drop this many sigmas below baseline.'),
        ),
        migrations.AlterField(
            model_name='heartbeatprofile',
            name='match_threshold',
            field=models.FloatField(default=0.75, help_text='Minimum match score in [0,1] to allow verification.'),
        ),
        migrations.AlterField(
            model_name='heartbeatreading',
            name='features',
            field=models.JSONField(default=dict, help_text='Canonical feature dict (see services.feature_matcher.FEATURE_ORDER).'),
        ),
        migrations.AlterField(
            model_name='heartbeatreading',
            name='rr_intervals',
            field=models.JSONField(blank=True, default=list, help_text='Optional raw R-R intervals (ms); empty for privacy-min uploads.'),
        ),
    ]
