# Generated by Django 5.1.15 on 2026-03-21 15:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartContractVault',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Human-readable vault title', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text="Description of this vault's purpose")),
                ('vault_id_onchain', models.PositiveIntegerField(blank=True, db_index=True, help_text='Vault ID on the TimeLockedVault smart contract', null=True)),
                ('password_hash', models.CharField(help_text='Keccak256 hash of the encrypted password (0x prefixed)', max_length=66)),
                ('password_encrypted', models.TextField(help_text='Server-side encrypted password data (AES-256-GCM)')),
                ('condition_type', models.CharField(choices=[('time_lock', 'Time Lock'), ('dead_mans_switch', "Dead Man's Switch"), ('multi_sig', 'Multi-Signature'), ('dao_vote', 'DAO Voting'), ('price_oracle', 'Price Oracle'), ('escrow', 'Escrow')], db_index=True, help_text='Type of unlock condition', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending_approval', 'Pending Approval'), ('unlocked', 'Unlocked'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='active', help_text='Current vault status', max_length=20)),
                ('contract_address', models.CharField(blank=True, default='', help_text='TimeLockedVault contract address', max_length=42)),
                ('tx_hash', models.CharField(blank=True, default='', help_text='Transaction hash for vault creation', max_length=66)),
                ('network', models.CharField(choices=[('testnet', 'Arbitrum Sepolia Testnet'), ('mainnet', 'Arbitrum One Mainnet')], default='testnet', help_text='Blockchain network', max_length=20)),
                ('unlock_at', models.DateTimeField(blank=True, help_text='For TIME_LOCK: when the vault unlocks', null=True)),
                ('check_in_interval_days', models.PositiveIntegerField(blank=True, help_text='For DEAD_MANS_SWITCH: days between required check-ins', null=True)),
                ('last_check_in', models.DateTimeField(blank=True, help_text='For DEAD_MANS_SWITCH: last check-in timestamp', null=True)),
                ('grace_period_days', models.PositiveIntegerField(blank=True, help_text='For DEAD_MANS_SWITCH: extra days after missed check-in', null=True)),
                ('price_threshold', models.DecimalField(blank=True, decimal_places=8, help_text='For PRICE_ORACLE: price threshold (e.g., 10000.00 USD)', max_digits=20, null=True)),
                ('price_above', models.BooleanField(default=True, help_text='For PRICE_ORACLE: true=unlock when price > threshold')),
                ('oracle_address', models.CharField(blank=True, default='', help_text='Chainlink oracle contract address', max_length=42)),
                ('beneficiary_email', models.EmailField(blank=True, default='', help_text='Beneficiary email for notifications', max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('beneficiary_user', models.ForeignKey(blank=True, help_text='Beneficiary user (if registered)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary_vaults', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Vault creator/owner', on_delete=django.db.models.deletion.CASCADE, related_name='smart_contract_vaults', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Smart Contract Vault',
                'verbose_name_plural': 'Smart Contract Vaults',
                'db_table': 'smart_contract_vaults',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MultiSigGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('required_approvals', models.PositiveSmallIntegerField(help_text='Number of approvals required (M)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('signers', models.ManyToManyField(help_text='Authorized signers (N)', related_name='multisig_memberships', to=settings.AUTH_USER_MODEL)),
                ('vault', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multi_sig_group', to='smart_contracts.smartcontractvault')),
            ],
            options={
                'verbose_name': 'Multi-Sig Group',
                'verbose_name_plural': 'Multi-Sig Groups',
                'db_table': 'smart_contract_multi_sig_groups',
            },
        ),
        migrations.CreateModel(
            name='InheritancePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('beneficiary_email', models.EmailField(help_text='Beneficiary email for notifications', max_length=254)),
                ('inactivity_period_days', models.PositiveIntegerField(default=90, help_text='Days of inactivity before grace period starts')),
                ('grace_period_days', models.PositiveIntegerField(default=7, help_text='Days in grace period before auto-release')),
                ('last_check_in', models.DateTimeField(default=django.utils.timezone.now, help_text='Last time owner confirmed they are alive')),
                ('grace_period_started_at', models.DateTimeField(blank=True, help_text='When grace period notification was sent', null=True)),
                ('notification_sent', models.BooleanField(default=False, help_text='Whether grace period notification was sent to owner')),
                ('beneficiary_notified', models.BooleanField(default=False, help_text='Whether beneficiary was notified of pending release')),
                ('status', models.CharField(choices=[('active', 'Active (Monitoring)'), ('grace_period', 'Grace Period (Owner Notified)'), ('triggered', 'Triggered (Released to Beneficiary)'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary_user', models.ForeignKey(blank=True, help_text='Beneficiary user account (if registered)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inheritance_plans_beneficiary', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inheritance_plans_owned', to=settings.AUTH_USER_MODEL)),
                ('vault', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inheritance_plan', to='smart_contracts.smartcontractvault')),
            ],
            options={
                'verbose_name': 'Inheritance Plan',
                'verbose_name_plural': 'Inheritance Plans',
                'db_table': 'smart_contract_inheritance_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EscrowAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arbitrator_wallet', models.CharField(blank=True, default='', help_text="Arbitrator's Ethereum wallet address", max_length=42)),
                ('release_conditions', models.TextField(help_text='Human-readable description of release conditions')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('released', 'Released'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arbitrator', models.ForeignKey(help_text='Trusted arbitrator who controls release', on_delete=django.db.models.deletion.CASCADE, related_name='escrow_arbitrating', to=settings.AUTH_USER_MODEL)),
                ('beneficiary', models.ForeignKey(help_text='User who receives the password', on_delete=django.db.models.deletion.CASCADE, related_name='escrow_beneficiary', to=settings.AUTH_USER_MODEL)),
                ('depositor', models.ForeignKey(help_text='User who deposited the password', on_delete=django.db.models.deletion.CASCADE, related_name='escrow_deposited', to=settings.AUTH_USER_MODEL)),
                ('vault', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_agreement', to='smart_contracts.smartcontractvault')),
            ],
            options={
                'verbose_name': 'Escrow Agreement',
                'verbose_name_plural': 'Escrow Agreements',
                'db_table': 'smart_contract_escrow_agreements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DAOProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('voting_deadline', models.DateTimeField(help_text='When voting ends')),
                ('quorum_threshold', models.PositiveSmallIntegerField(default=5100, help_text='Quorum in basis points (5100 = 51%)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('eligible_voters', models.ManyToManyField(help_text='Users eligible to vote', related_name='dao_eligible_proposals', to=settings.AUTH_USER_MODEL)),
                ('vault', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dao_proposal', to='smart_contracts.smartcontractvault')),
            ],
            options={
                'verbose_name': 'DAO Proposal',
                'verbose_name_plural': 'DAO Proposals',
                'db_table': 'smart_contract_dao_proposals',
            },
        ),
        migrations.CreateModel(
            name='VaultCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('condition_type', models.CharField(choices=[('time_lock', 'Time Lock'), ('dead_mans_switch', "Dead Man's Switch"), ('multi_sig', 'Multi-Signature'), ('dao_vote', 'DAO Voting'), ('price_oracle', 'Price Oracle'), ('escrow', 'Escrow')], help_text='Condition type for this node', max_length=20)),
                ('operator', models.CharField(choices=[('and', 'AND'), ('or', 'OR')], default='and', help_text='How this condition combines with siblings', max_length=3)),
                ('parameters', models.JSONField(default=dict, help_text='Type-specific parameters (threshold, deadline, addresses, etc.)')),
                ('is_met', models.BooleanField(default=False)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='smart_contracts.smartcontractvault')),
            ],
            options={
                'verbose_name': 'Vault Condition',
                'verbose_name_plural': 'Vault Conditions',
                'db_table': 'smart_contract_vault_conditions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DAOVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approve', models.BooleanField(help_text='True = approve, False = reject')),
                ('tx_hash', models.CharField(blank=True, default='', help_text='On-chain vote transaction hash', max_length=66)),
                ('voted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='smart_contracts.daoproposal')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dao_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DAO Vote',
                'verbose_name_plural': 'DAO Votes',
                'db_table': 'smart_contract_dao_votes',
                'unique_together': {('proposal', 'voter')},
            },
        ),
        migrations.CreateModel(
            name='MultiSigApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approved', models.BooleanField(default=False)),
                ('tx_hash', models.CharField(blank=True, default='', help_text='On-chain approval transaction hash', max_length=66)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multisig_approvals', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='smart_contracts.multisiggroup')),
            ],
            options={
                'verbose_name': 'Multi-Sig Approval',
                'verbose_name_plural': 'Multi-Sig Approvals',
                'db_table': 'smart_contract_multi_sig_approvals',
                'unique_together': {('group', 'signer')},
            },
        ),
        migrations.AddIndex(
            model_name='smartcontractvault',
            index=models.Index(fields=['user', '-created_at'], name='smart_contr_user_id_72870a_idx'),
        ),
        migrations.AddIndex(
            model_name='smartcontractvault',
            index=models.Index(fields=['condition_type', 'status'], name='smart_contr_conditi_fa3f60_idx'),
        ),
        migrations.AddIndex(
            model_name='smartcontractvault',
            index=models.Index(fields=['network', '-created_at'], name='smart_contr_network_d4a17b_idx'),
        ),
    ]
