# Generated by Django 4.2.16 on 2025-11-26 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FHEMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], max_length=10)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('total_operations', models.IntegerField(default=0)),
                ('successful_operations', models.IntegerField(default=0)),
                ('failed_operations', models.IntegerField(default=0)),
                ('timeout_operations', models.IntegerField(default=0)),
                ('client_only_count', models.IntegerField(default=0)),
                ('hybrid_fhe_count', models.IntegerField(default=0)),
                ('full_fhe_count', models.IntegerField(default=0)),
                ('cached_fhe_count', models.IntegerField(default=0)),
                ('avg_latency_ms', models.FloatField(default=0)),
                ('p50_latency_ms', models.FloatField(default=0)),
                ('p95_latency_ms', models.FloatField(default=0)),
                ('p99_latency_ms', models.FloatField(default=0)),
                ('cache_hit_rate', models.FloatField(default=0)),
                ('cache_size_bytes', models.BigIntegerField(default=0)),
                ('fallback_rate', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'FHE Metrics',
                'verbose_name_plural': 'FHE Metrics',
                'indexes': [models.Index(fields=['period_type', 'period_start'], name='fhe_service_period__a576e5_idx')],
                'unique_together': {('period_type', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='FHEOperationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('operation_type', models.CharField(max_length=50)),
                ('encryption_tier', models.CharField(choices=[('client_only', 'Client Only'), ('hybrid_fhe', 'Hybrid FHE'), ('full_fhe', 'Full FHE'), ('cached_fhe', 'Cached FHE')], max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout'), ('fallback', 'Fallback Used'), ('cached', 'Cache Hit')], max_length=20)),
                ('total_time_ms', models.IntegerField(default=0)),
                ('encryption_time_ms', models.IntegerField(default=0)),
                ('computation_time_ms', models.IntegerField(default=0)),
                ('decryption_time_ms', models.IntegerField(default=0)),
                ('circuit_depth', models.IntegerField(default=0)),
                ('circuit_complexity', models.CharField(default='unknown', max_length=20)),
                ('input_size_bytes', models.IntegerField(default=0)),
                ('output_size_bytes', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('cache_hit', models.BooleanField(default=False)),
                ('cache_key', models.CharField(blank=True, max_length=64, null=True)),
                ('requested_profile', models.CharField(blank=True, max_length=20, null=True)),
                ('actual_profile', models.CharField(blank=True, max_length=20, null=True)),
                ('fallback_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fhe_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FHE Operation Log',
                'verbose_name_plural': 'FHE Operation Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='fhe_service_user_id_df10c5_idx'), models.Index(fields=['operation_type', 'status'], name='fhe_service_operati_550637_idx'), models.Index(fields=['created_at'], name='fhe_service_created_d408ec_idx'), models.Index(fields=['encryption_tier'], name='fhe_service_encrypt_ebdd6c_idx')],
            },
        ),
        migrations.CreateModel(
            name='FHEKeyStore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_type', models.CharField(choices=[('concrete', 'Concrete-Python'), ('seal_public', 'SEAL Public Key'), ('seal_secret', 'SEAL Secret Key'), ('seal_relin', 'SEAL Relinearization Key'), ('seal_galois', 'SEAL Galois Key')], max_length=20)),
                ('encrypted_key_data', models.BinaryField()),
                ('key_size_bits', models.IntegerField(default=0)),
                ('polynomial_modulus_degree', models.IntegerField(default=8192)),
                ('security_level', models.IntegerField(default=128)),
                ('scale', models.FloatField(blank=True, null=True)),
                ('coefficient_modulus', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fhe_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FHE Key Store',
                'verbose_name_plural': 'FHE Key Stores',
                'indexes': [models.Index(fields=['user', 'key_type', 'is_active'], name='fhe_service_user_id_26f099_idx'), models.Index(fields=['expires_at'], name='fhe_service_expires_6f01f4_idx')],
                'unique_together': {('user', 'key_type')},
            },
        ),
        migrations.CreateModel(
            name='FHEComputationCacheModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('strength_check', 'Password Strength Check'), ('similarity_search', 'Similarity Search'), ('breach_detection', 'Breach Detection'), ('batch_strength', 'Batch Strength Evaluation'), ('encrypted_compare', 'Encrypted Comparison')], max_length=30)),
                ('input_hash', models.CharField(db_index=True, max_length=64)),
                ('encrypted_result', models.BinaryField()),
                ('result_size_bytes', models.IntegerField(default=0)),
                ('computation_time_ms', models.IntegerField(default=0)),
                ('circuit_depth', models.IntegerField(default=0)),
                ('encryption_tier', models.CharField(default='full_fhe', max_length=20)),
                ('hit_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fhe_cache_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FHE Computation Cache',
                'verbose_name_plural': 'FHE Computation Caches',
                'indexes': [models.Index(fields=['operation_type', 'input_hash'], name='fhe_service_operati_235d42_idx'), models.Index(fields=['user', 'operation_type'], name='fhe_service_user_id_c48992_idx'), models.Index(fields=['expires_at'], name='fhe_service_expires_5e02da_idx'), models.Index(fields=['created_at'], name='fhe_service_created_178bdb_idx')],
            },
        ),
    ]
