"""
Django settings for password_manager project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
import sys
import secrets
import warnings
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

# =============================================================================
# Warning Suppressions
# =============================================================================
# Import warning suppressions for TensorFlow, Keras, Django, and other packages
try:
    from .warning_suppressions import *
except ImportError:
    # Fallback if warning_suppressions.py doesn't exist yet
    pass

# Suppress known compatibility warnings from dj-rest-auth with django-allauth 65.x
# These warnings come from dj-rest-auth library code, not our configuration
warnings.filterwarnings('ignore', message='app_settings.USERNAME_REQUIRED is deprecated')
warnings.filterwarnings('ignore', message='app_settings.EMAIL_REQUIRED is deprecated')

# Load environment variables from .env file
load_dotenv()

# Handle Python 3.13+ cgi module removal
if sys.version_info >= (3, 13):
    try:
        import legacy_cgi
        sys.modules['cgi'] = legacy_cgi
        print("Loaded legacy-cgi package as replacement for built-in cgi module")
    except ImportError:
        # Try to find the package in the installed packages
        try:
            # This helps finding the package in some virtual environments
            import site
            site_packages = site.getsitepackages()
            for site_path in site_packages:
                legacy_cgi_path = os.path.join(site_path, 'legacy_cgi')
                if os.path.exists(legacy_cgi_path):
                    if legacy_cgi_path not in sys.path:
                        sys.path.append(legacy_cgi_path)
                    import legacy_cgi
                    sys.modules['cgi'] = legacy_cgi
                    print("Found and loaded legacy-cgi package from:", legacy_cgi_path)
                    break
        except (ImportError, Exception) as e:
            print(f"Warning: legacy-cgi package not found. Some features may not work correctly: {e}")
            print("Install with: pip install legacy-cgi")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY') or secrets.token_urlsafe(50)

# SECURITY WARNING: don't run with debug turned on in production!
# Default to True for development - set DEBUG=False in production environment
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

# Parse ALLOWED_HOSTS from environment variable
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,127.0.0.1:8000,[::1]').split(',')


# Application definition

INSTALLED_APPS = [
    # Django Channels must be before django.contrib.staticfiles
    # 'daphne',  # ASGI server for Channels - DISABLED to use WSGI in development
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    #'django.contrib.gis',  # Required for GeoIP functionality
    'django_extensions',
    
    # Third-party apps
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'drf_yasg',
    
    # Django Channels
    'channels',
    
    # Local apps
    'shared',
    'api',
    'vault',
    'auth_module',
    'user',
    'logging_manager',
    'security',
    'ml_security',  # Machine Learning Security
    'ml_dark_web',  # ML Dark Web Monitoring with WebSocket alerts
    'analytics',  # Analytics & Metrics
    'ab_testing',  # A/B Testing & Feature Flags
    'email_masking',  # Email Masking & Privacy
    'behavioral_recovery',  # Behavioral Biometric Recovery
    'blockchain',  # Blockchain Anchoring (Phase 2B)
    'fhe_service',  # Fully Homomorphic Encryption Service
    'adversarial_ai',  # Adversarial AI Password Defense
    # OAuth providers
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.apple',
    'allauth.socialaccount.providers.github',
    'push_notifications',
    'rest_framework_simplejwt',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    # FIX: CSRF exemption for auth endpoints - MUST be before CsrfViewMiddleware
    'middleware.CSRFExemptAuthMiddleware',
    # Disable HTTPS redirect in development - causes ASGI issues
    # 'middleware.HttpsRedirectMiddleware',
    'middleware.SecurityHeadersMiddleware',
    # Response compression (near top for efficiency)
    'password_manager.compression_middleware.VaultCompressionMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # CommonMiddleware removed - not compatible with ASGI/Channels and not needed for API/SPA
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Required for django-allauth
    'middleware.SecurityMiddleware',  # Custom security middleware - MUST be after AuthenticationMiddleware
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Cache control for vault endpoints
    'password_manager.compression_middleware.CacheControlMiddleware',
    # Performance monitoring (should be near the end to measure full request/response cycle)
    'shared.performance_middleware.PerformanceMonitoringMiddleware',
    'shared.performance_middleware.DatabaseQueryMonitoringMiddleware',
    'shared.performance_middleware.APIPerformanceMiddleware',
    'shared.performance_middleware.CachePerformanceMiddleware',
]

# Response compression settings
ENABLE_RESPONSE_COMPRESSION = True

# Disable APPEND_SLASH - required for ASGI/Channels compatibility
# Also recommended for API-first applications and SPAs
APPEND_SLASH = False

ROOT_URLCONF = 'password_manager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'password_manager.wsgi.application'
ASGI_APPLICATION = 'password_manager.asgi.application'


# Database configuration
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        # Temporarily using SQLite for easier setup
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'postgresql': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'password_manager',
        'USER': 'user',
        'PASSWORD': 'password123',
        'HOST': 'localhost',
        'PORT': '5432',
    }    
}

# Cache Configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 300,  # 5 minutes default
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
            'CULL_FREQUENCY': 3,
        }
    }
}

# Redis Cache Configuration (for Kyber hybrid caching)
# Enable by setting USE_REDIS_CACHE=True in environment
if os.environ.get('USE_REDIS_CACHE', 'False').lower() == 'true':
    CACHES['default'] = {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SOCKET_CONNECT_TIMEOUT': 5,
            'SOCKET_TIMEOUT': 5,
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 50,
                'timeout': 20,
            },
            'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
        },
        'KEY_PREFIX': 'kyber',
        'TIMEOUT': 3600,  # 1 hour default for Kyber keys
    }
    
    # Add dedicated Kyber cache
    CACHES['kyber'] = {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/2'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SOCKET_CONNECT_TIMEOUT': 5,
            'SOCKET_TIMEOUT': 5,
        },
        'KEY_PREFIX': 'kyber',
        'TIMEOUT': 86400,  # 24 hours for public keys
    }

# Kyber Cache Configuration
KYBER_CACHE_SETTINGS = {
    'USE_REDIS': os.environ.get('USE_REDIS_CACHE', 'False').lower() == 'true',
    'REDIS_ALIAS': 'kyber' if os.environ.get('USE_REDIS_CACHE', 'False').lower() == 'true' else 'default',
    'PUBLIC_KEY_TTL': 86400,  # 24 hours
    'SESSION_TTL': 3600,  # 1 hour
    'SHARED_SECRET_TTL': 300,  # 5 minutes
    'LRU_CACHE_SIZE': 256,
}

# ==============================================================================
# DJANGO CHANNELS CONFIGURATION (WebSocket Support)
# ==============================================================================

# Channel Layers - For WebSocket communication
# Using Redis for production, In-Memory for development
if DEBUG:
    # In-Memory Channel Layer (Development Only)
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }
else:
    # Redis Channel Layer (Production)
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [os.environ.get('REDIS_URL', 'redis://localhost:6379')],
                "capacity": 1500,  # Max messages per channel
                "expiry": 10,  # Message expiry time in seconds
            },
        },
    }

# You can override to use Redis in development by setting environment variable:
if os.environ.get('USE_REDIS_CHANNELS', 'False').lower() == 'true':
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [(
                    os.environ.get('REDIS_HOST', 'localhost'),
                    int(os.environ.get('REDIS_PORT', 6379))
                )],
                "capacity": 1500,
                "expiry": 10,
            },
        },
    }

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 12,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Authentication settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        #'rest_framework.authentication.SessionAuthentication',  # removed for SPA JWT usage
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.NamespaceVersioning',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 100,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '10/minute',
        'user': '60/minute', 
        'auth': '3/minute',  # Stricter login attempts
        'password_check': '5/hour',  # Reduced breach checks
        'security': '20/hour',  # Security operations
        'passkey': '10/minute',  # WebAuthn operations
        'vault': '100/hour',  # Reasonable vault operations
        'dj_rest_auth': '10/minute',  # dj-rest-auth operations
    }
}

# Additional throttling settings
ANON_VAULT_RATE = '10/hour'  # Rate limit for anonymous vault access

# Password hashing
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==============================================================================
# CORS CONFIGURATION (JWT-based SPA - No cookies/sessions for API)
# ==============================================================================
# Note: Detailed CORS configuration is below (after security settings)
# This placeholder ensures CORS is configured before other settings reference it

# AWS S3 settings
AWS_ACCESS_KEY_ID = 'your-access-key'
AWS_SECRET_ACCESS_KEY = 'your-secret-key'
AWS_STORAGE_BUCKET_NAME = 'password-manager-bucket'
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}
AWS_DEFAULT_ACL = 'private'

# Site ID for django-allauth
SITE_ID = 1

# Security settings
SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = os.environ.get('DJANGO_SESSION_COOKIE_SECURE', 'False') == 'True'
CSRF_COOKIE_SECURE = os.environ.get('DJANGO_CSRF_COOKIE_SECURE', 'False') == 'True'
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Additional CSRF protection
CSRF_COOKIE_HTTPONLY = True
# Use 'Lax' for development with JWT (not needed for API calls with Authorization header)
# Set to 'Strict' in production if using cookie-based auth
CSRF_COOKIE_SAMESITE = 'Lax' if DEBUG else 'Strict'

# CSRF Trusted Origins (for SPA development)
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:4173',
    'http://127.0.0.1:4173',
]

# Add production origins from environment
if not DEBUG:
    csrf_origins_env = os.environ.get('CSRF_TRUSTED_ORIGINS', '').strip()
    if csrf_origins_env:
        CSRF_TRUSTED_ORIGINS.extend([origin.strip() for origin in csrf_origins_env.split(',') if origin.strip()])

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'db': {
            'level': 'INFO',
            'class': 'logging_manager.handlers.DatabaseLogHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/debug.log'),
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'db'],
            'level': 'INFO',
            'propagate': True,
        },
        'security': {
            'handlers': ['file', 'db'],
            'level': 'INFO',
            'propagate': False,
        },
        'vault': {
            'handlers': ['file', 'db'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Authentication backends
AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin
    'django.contrib.auth.backends.ModelBackend',
    # allauth specific authentication methods
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Provider specific settings - Use environment variables
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.environ.get('GOOGLE_OAUTH_CLIENT_ID', ''),
            'secret': os.environ.get('GOOGLE_OAUTH_CLIENT_SECRET', ''),
            'key': ''
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    },
    'apple': {
        'APP': {
            'client_id': os.environ.get('APPLE_OAUTH_CLIENT_ID', ''),
            'secret': os.environ.get('APPLE_OAUTH_CLIENT_SECRET', ''),
            'key': os.environ.get('APPLE_OAUTH_KEY_ID', ''),
            'team': os.environ.get('APPLE_OAUTH_TEAM_ID', ''),
            'certificate_key': os.environ.get('APPLE_OAUTH_PRIVATE_KEY', '')
        },
        'SCOPE': ['email', 'name']
    },
    'github': {
        'APP': {
            'client_id': os.environ.get('GITHUB_OAUTH_CLIENT_ID', ''),
            'secret': os.environ.get('GITHUB_OAUTH_CLIENT_SECRET', ''),
        },
        'SCOPE': ['user:email', 'read:user']
    }
}

# ==============================================================================
# EMAIL & NOTIFICATION CONFIGURATION
# ==============================================================================

# Email settings for account recovery and notifications
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.example.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'your-email@example.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'your-email-password')

# Email addresses
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'SecureVault <noreply@securevault.com>')
SECURITY_EMAIL = os.environ.get('SECURITY_EMAIL', 'security@securevault.com')

# Frontend URL (for email links)
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')

# AllAuth settings
# Note: The UserWarnings from dj_rest_auth are from the dj-rest-auth library itself,
# not from this configuration. They will be fixed when dj-rest-auth updates to the new format.
# Our configuration here is correct for django-allauth 65.x
ACCOUNT_SIGNUP_FIELDS = ['username', 'email*', 'password1*', 'password2*']
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_LOGOUT_ON_GET = True
ACCOUNT_UNIQUE_EMAIL = True

# Authy settings
AUTHY_API_KEY = os.environ.get('AUTHY_API_KEY', 'your_authy_api_key')

# Push notification settings
PUSH_NOTIFICATIONS_SETTINGS = {
    'FCM_API_KEY': os.environ.get('FCM_API_KEY', 'your_fcm_api_key'),
    'GCM_API_KEY': os.environ.get('GCM_API_KEY', 'your_gcm_api_key'),
    'APNS_CERTIFICATE': os.path.join(BASE_DIR, 'certs', 'apns-cert.pem'),
    'WP_PRIVATE_KEY': os.path.join(BASE_DIR, 'certs', 'windows_private.pem'),
    'WP_CLAIMS': {'sub': 'mailto:dev@passwordmanager.com'}
}

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),  # Short-lived access tokens
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     # Longer-lived refresh tokens
    'ROTATE_REFRESH_TOKENS': True,                   # Enable refresh token rotation
    'BLACKLIST_AFTER_ROTATION': True,                # Blacklist old tokens after rotation
    'UPDATE_LAST_LOGIN': True,                       # Track last login
    
    # Refresh Token Family (Security Enhancement)
    'REFRESH_TOKEN_ROTATE_ON_USE': True,             # Rotate token on each use
    'REFRESH_TOKEN_FAMILY_MAX_SIZE': 5,              # Limit concurrent devices to 5
    
    # Algorithm settings
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    
    # Audience and issuer claims for added security
    'AUDIENCE': None,
    'ISSUER': 'password_manager',
    
    # Token classes
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    
    # Token type headers
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# Add to INSTALLED_APPS for token blacklisting
INSTALLED_APPS += ['rest_framework_simplejwt.token_blacklist']

# Firebase Settings
FIREBASE_PROJECT_ID = 'your-firebase-project-id'
FIREBASE_PRIVATE_KEY_ID = 'your-firebase-private-key-id'
FIREBASE_PRIVATE_KEY = 'your-firebase-private-key'
FIREBASE_CLIENT_EMAIL = 'your-firebase-client-email'
FIREBASE_CLIENT_ID = 'your-firebase-client-id'
FIREBASE_CLIENT_CERT_URL = 'your-firebase-client-cert-url'
FIREBASE_DATABASE_URL = 'https://your-project-id.firebaseio.com'

# GeoIP Database Configuration
# Download GeoLite2-City.mmdb and GeoLite2-Country.mmdb from MaxMind
# Instructions:
# 1. Register at https://www.maxmind.com/en/geolite2/signup
# 2. Download GeoLite2-City.mmdb and GeoLite2-Country.mmdb
# 3. Place them in the directory specified by GEOIP_PATH
# You can also set this via environment variable: GEOIP_PATH
GEOIP_PATH = os.environ.get('GEOIP_PATH', os.path.join(BASE_DIR, 'geoip'))

# Create the GeoIP directory if it doesn't exist
os.makedirs(GEOIP_PATH, exist_ok=True)

# GeoIP database files (optional - will work without them but with reduced functionality)
GEOIP_CITY = 'GeoLite2-City.mmdb'
GEOIP_COUNTRY = 'GeoLite2-Country.mmdb'


# Security Service Configuration
MAX_FAILED_ATTEMPTS = 5
LOCKOUT_DURATION_MINUTES = 30
SUSPICIOUS_THRESHOLD = 3
BLACKLISTED_IPS = {'192.168.1.100', '10.0.0.5'}  # Example IPs

# IP Whitelisting (Enterprise Feature - Optional)
# Set ALLOWED_IP_RANGES in .env for IP restriction
# Example: ALLOWED_IP_RANGES=192.168.1.0/24,10.0.0.0/8
ALLOWED_IP_RANGES = os.environ.get('ALLOWED_IP_RANGES', '').split(',') if os.environ.get('ALLOWED_IP_RANGES') else []
IP_WHITELISTING_ENABLED = os.environ.get('IP_WHITELISTING_ENABLED', 'False').lower() == 'true'

# ==============================================================================
# SMS NOTIFICATION CONFIGURATION (Twilio)
# ==============================================================================

# SMS Service (Optional - for Twilio integration)
# Configure these in your .env file for production:
# TWILIO_ACCOUNT_SID=your_actual_account_sid
# TWILIO_AUTH_TOKEN=your_actual_auth_token
# TWILIO_PHONE_NUMBER=+1234567890
TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID', 'your_twilio_sid')
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN', 'your_twilio_token')
TWILIO_PHONE_NUMBER = os.environ.get('TWILIO_PHONE_NUMBER', '+1234567890')
TWILIO_ENABLED = os.environ.get('TWILIO_ENABLED', 'False').lower() == 'true'

# Enhanced Security Configuration
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Force HTTPS in production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# ==============================================================================
# ENHANCED CORS SETTINGS FOR JWT-BASED SPA
# ==============================================================================

# CORS settings for frontend (JWT-based SPA - no cookies for API auth)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",   # Vite default dev port
    "http://127.0.0.1:5173",
    "http://localhost:3000",   # Alternative React dev port
    "http://127.0.0.1:3000",
    "http://localhost:4173",   # Vite preview port
    "http://127.0.0.1:4173",
    "http://localhost:8000",   # Django dev server (for testing)
    "http://127.0.0.1:8000",
]

# When using JWT auth (Authorization header), no cookies are required for API calls.
# Set to False to avoid exposing cookies unnecessarily.
# Note: WebSocket connections using query param tokens also work without credentials=True
CORS_ALLOW_CREDENTIALS = False

CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS',
]

CORS_ALLOW_HEADERS = [
    'Authorization',           # Required for JWT (Bearer token)
    'Content-Type',
    'X-Device-Fingerprint',   # Custom security header
    'Accept',
    'Origin',
    'User-Agent',
    'DNT',
    'Cache-Control',
    'X-Requested-With',
]

CORS_EXPOSE_HEADERS = [
    'Content-Length',
]

CORS_PREFLIGHT_MAX_AGE = 86400  # 24 hours

# Add production origins from environment
if not DEBUG:
    env_origins = os.environ.get('CORS_ALLOWED_ORIGINS', '').strip()
    if env_origins:
        CORS_ALLOWED_ORIGINS.extend([origin.strip() for origin in env_origins.split(',') if origin.strip()])

# Rate limiting: lenient in development, strict in production
REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'].update({
    'anon': os.environ.get('RATE_LIMIT_ANON', '100/minute') if DEBUG else os.environ.get('RATE_LIMIT_ANON', '10/minute'),
    'user': os.environ.get('RATE_LIMIT_USER', '200/minute') if DEBUG else os.environ.get('RATE_LIMIT_USER', '60/minute'), 
    'auth': os.environ.get('RATE_LIMIT_AUTH', '30/minute') if DEBUG else os.environ.get('RATE_LIMIT_AUTH', '3/minute'),
    'password_check': '5/hour',
    'vault': '100/hour',
})

# ==============================================================================
# SESSION & CSRF CONFIGURATION (For admin/WebSocket only - API uses JWT)
# ==============================================================================

# Session configuration (used for Django admin, not for SPA API)
SESSION_COOKIE_AGE = 3600  # 1 hour
SESSION_COOKIE_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax' if DEBUG else 'Strict'  # Relaxed for dev

# CSRF configuration (not needed for JWT API calls, but used for admin/forms)
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax' if DEBUG else 'Strict'  # Relaxed for dev
CSRF_USE_SESSIONS = True

# Ensure logs directory exists
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOGS_DIR, exist_ok=True)

# Enhanced Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGS_DIR, 'django.log'),
            'formatter': 'verbose',
        },
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler', 
            'filename': os.path.join(LOGS_DIR, 'security.log'),
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,
        },
        'security': {
            'handlers': ['security_file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'auth_module': {
            'handlers': ['security_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# ==============================================================================
# FIDO2/WebAuthn Passkey Configuration
# ==============================================================================

# Relying Party (RP) Configuration
PASSKEY_RP_ID = os.environ.get('PASSKEY_RP_ID', 'localhost')
PASSKEY_RP_NAME = os.environ.get('PASSKEY_RP_NAME', 'Password Manager')

# Allowed origins for WebAuthn operations
passkey_origins_env = os.environ.get('PASSKEY_ALLOWED_ORIGINS', '').strip()
PASSKEY_ALLOWED_ORIGINS = [origin.strip() for origin in passkey_origins_env.split(',') if origin.strip()]

# Add localhost origins for development
if DEBUG:
    PASSKEY_ALLOWED_ORIGINS.extend([
        'http://localhost:5173',   # Vite default
        'http://127.0.0.1:5173',
        'http://localhost:3000',
        'http://127.0.0.1:3000',
        'http://localhost:4173',
        'http://127.0.0.1:4173',
        'http://localhost:8000',
        'http://127.0.0.1:8000',
    ])

# Passkey settings
PASSKEY_TIMEOUT = 300000  # 5 minutes in milliseconds
PASSKEY_USER_VERIFICATION = 'preferred'  # 'required', 'preferred', or 'discouraged'
PASSKEY_AUTHENTICATOR_ATTACHMENT = 'platform'  # 'platform' or 'cross-platform'

# ==============================================================================
# PERFORMANCE MONITORING CONFIGURATION
# ==============================================================================

# Enable/disable performance metric collection
STORE_PERFORMANCE_METRICS = os.environ.get('STORE_PERFORMANCE_METRICS', 'True').lower() == 'true'
STORE_API_METRICS = os.environ.get('STORE_API_METRICS', 'True').lower() == 'true'

# Performance thresholds
SLOW_REQUEST_THRESHOLD = float(os.environ.get('SLOW_REQUEST_THRESHOLD', '1.0'))  # seconds
QUERY_COUNT_THRESHOLD = int(os.environ.get('QUERY_COUNT_THRESHOLD', '50'))  # number of queries

# System resource monitoring thresholds
CPU_WARNING_THRESHOLD = float(os.environ.get('CPU_WARNING_THRESHOLD', '80'))  # percentage
MEMORY_WARNING_THRESHOLD = float(os.environ.get('MEMORY_WARNING_THRESHOLD', '80'))  # percentage
DISK_WARNING_THRESHOLD = float(os.environ.get('DISK_WARNING_THRESHOLD', '80'))  # percentage

# Error rate threshold for alerting
ERROR_RATE_THRESHOLD = float(os.environ.get('ERROR_RATE_THRESHOLD', '5'))  # percentage

# Performance metric retention (days)
PERFORMANCE_METRIC_RETENTION_DAYS = int(os.environ.get('PERFORMANCE_METRIC_RETENTION_DAYS', '30'))
ERROR_LOG_RETENTION_DAYS = int(os.environ.get('ERROR_LOG_RETENTION_DAYS', '90'))
SYSTEM_METRIC_RETENTION_DAYS = int(os.environ.get('SYSTEM_METRIC_RETENTION_DAYS', '7'))

# ML model training interval (hours)
ML_MODEL_TRAINING_INTERVAL = int(os.environ.get('ML_MODEL_TRAINING_INTERVAL', '24'))

# System resource monitoring interval (seconds)
SYSTEM_MONITORING_INTERVAL = int(os.environ.get('SYSTEM_MONITORING_INTERVAL', '60'))

# ==============================================================================
# BEHAVIORAL RECOVERY SETTINGS
# ==============================================================================

# Behavioral Recovery Configuration
BEHAVIORAL_RECOVERY = {
    'SIMILARITY_THRESHOLD': float(os.environ.get('BEHAVIORAL_SIMILARITY_THRESHOLD', '0.87')),
    'RECOVERY_TIMELINE_DAYS': int(os.environ.get('BEHAVIORAL_RECOVERY_DAYS', '5')),
    'MIN_SAMPLES_PER_CHALLENGE': int(os.environ.get('MIN_SAMPLES_PER_CHALLENGE', '50')),
    'DIFFERENTIAL_PRIVACY_EPSILON': float(os.environ.get('DIFFERENTIAL_PRIVACY_EPSILON', '0.5')),
    'EMBEDDING_DIMENSION': 128,  # 128-dimensional behavioral DNA
    'INPUT_DIMENSION': 247,      # 247-dimensional input features
    'ENABLED': os.environ.get('BEHAVIORAL_RECOVERY_ENABLED', 'True').lower() == 'true',
}

# Post-Quantum Cryptography Configuration (Phase 2A)
QUANTUM_CRYPTO = {
    'ENABLED': os.environ.get('QUANTUM_CRYPTO_ENABLED', 'True').lower() == 'true',
    'ALGORITHM': os.environ.get('QUANTUM_ALGORITHM', 'Kyber768'),
    'FALLBACK_ENABLED': os.environ.get('QUANTUM_FALLBACK_ENABLED', 'True').lower() == 'true',
    'HYBRID_MODE': True,  # Always use hybrid Kyber + AES-256-GCM
    'ALLOW_SIMULATION': DEBUG,  # Only allow simulation in DEBUG mode
}

# ==============================================================================
# OPENID CONNECT (OIDC) CONFIGURATION
# ==============================================================================

# OIDC enables enterprise SSO integration (Okta, Azure AD, Auth0, etc.)
# and provides ID token validation for secure identity verification.

# Enable/disable OIDC features
OIDC_ENABLED = os.environ.get('OIDC_ENABLED', 'True').lower() == 'true'

# OIDC Provider Configuration
# These can be configured via environment variables or directly here
OIDC_PROVIDERS = {
    # Microsoft Azure AD / Entra ID
    'microsoft': {
        'client_id': os.environ.get('MICROSOFT_OAUTH_CLIENT_ID', ''),
        'client_secret': os.environ.get('MICROSOFT_OAUTH_CLIENT_SECRET', ''),
        'tenant_id': os.environ.get('MICROSOFT_TENANT_ID', 'common'),
        'discovery_url': f"https://login.microsoftonline.com/{os.environ.get('MICROSOFT_TENANT_ID', 'common')}/v2.0/.well-known/openid-configuration",
        'scopes': ['openid', 'profile', 'email', 'User.Read'],
    },
    # Okta
    'okta': {
        'client_id': os.environ.get('OKTA_OAUTH_CLIENT_ID', ''),
        'client_secret': os.environ.get('OKTA_OAUTH_CLIENT_SECRET', ''),
        'domain': os.environ.get('OKTA_DOMAIN', ''),
        'discovery_url': f"https://{os.environ.get('OKTA_DOMAIN', 'example.okta.com')}/.well-known/openid-configuration",
        'scopes': ['openid', 'profile', 'email'],
    },
    # Auth0
    'auth0': {
        'client_id': os.environ.get('AUTH0_CLIENT_ID', ''),
        'client_secret': os.environ.get('AUTH0_CLIENT_SECRET', ''),
        'domain': os.environ.get('AUTH0_DOMAIN', ''),
        'discovery_url': f"https://{os.environ.get('AUTH0_DOMAIN', 'example.auth0.com')}/.well-known/openid-configuration",
        'scopes': ['openid', 'profile', 'email'],
    },
    # Generic OIDC Provider (for custom enterprise SSO)
    'generic': {
        'client_id': os.environ.get('OIDC_CLIENT_ID', ''),
        'client_secret': os.environ.get('OIDC_CLIENT_SECRET', ''),
        'discovery_url': os.environ.get('OIDC_DISCOVERY_URL', ''),
        'scopes': os.environ.get('OIDC_SCOPES', 'openid profile email').split(),
    },
}

# Filter out unconfigured providers
OIDC_PROVIDERS = {
    name: config for name, config in OIDC_PROVIDERS.items()
    if config.get('client_id') and config.get('client_secret')
}

# OIDC Security Settings
OIDC_NONCE_TTL = int(os.environ.get('OIDC_NONCE_TTL', '600'))  # 10 minutes
OIDC_STATE_TTL = int(os.environ.get('OIDC_STATE_TTL', '600'))  # 10 minutes
OIDC_JWKS_CACHE_TTL = int(os.environ.get('OIDC_JWKS_CACHE_TTL', '3600'))  # 1 hour

# ID Token validation settings
OIDC_VERIFY_SSL = os.environ.get('OIDC_VERIFY_SSL', 'True').lower() == 'true'
OIDC_CLOCK_SKEW_SECONDS = int(os.environ.get('OIDC_CLOCK_SKEW_SECONDS', '120'))

# Auto-create users from OIDC claims
OIDC_CREATE_USER = os.environ.get('OIDC_CREATE_USER', 'True').lower() == 'true'
OIDC_UPDATE_USER = os.environ.get('OIDC_UPDATE_USER', 'True').lower() == 'true'

# ==============================================================================
# PASSKEY RECOVERY CONFIGURATION
# ==============================================================================

# Primary Recovery Settings
PASSKEY_RECOVERY = {
    'KEY_LENGTH': 24,  # Characters in recovery key (excluding hyphens)
    'KEY_FORMAT': 'XXXX-XXXX-XXXX-XXXX-XXXX-XXXX',
    'MAX_BACKUPS_PER_USER': int(os.environ.get('MAX_RECOVERY_BACKUPS', '5')),
    'BACKUP_EXPIRY_DAYS': int(os.environ.get('RECOVERY_BACKUP_EXPIRY_DAYS', '365')),
    'MAX_RECOVERY_ATTEMPTS_PER_HOUR': int(os.environ.get('MAX_RECOVERY_ATTEMPTS', '3')),
    'LOCKOUT_DURATION_HOURS': int(os.environ.get('RECOVERY_LOCKOUT_HOURS', '24')),
}

# Recovery Rate Limiting
RECOVERY_THROTTLE_RATE = os.environ.get('RECOVERY_THROTTLE_RATE', '3/hour')
RECOVERY_INITIATE_RATE = os.environ.get('RECOVERY_INITIATE_RATE', '5/hour')
RECOVERY_COMPLETE_RATE = os.environ.get('RECOVERY_COMPLETE_RATE', '3/hour')

# Security Alert Configuration
SECURITY_ALERT_EMAIL = os.environ.get('SECURITY_ALERT_EMAIL', SECURITY_EMAIL)
RECOVERY_ALERT_THRESHOLD = int(os.environ.get('RECOVERY_ALERT_THRESHOLD', '5'))

# Blockchain Anchoring Configuration (Phase 2B)
BLOCKCHAIN_ANCHORING = {
    'ENABLED': os.environ.get('BLOCKCHAIN_ENABLED', 'False').lower() == 'true',
    'NETWORK': os.environ.get('BLOCKCHAIN_NETWORK', 'testnet'),  # 'testnet' or 'mainnet'
    'RPC_URL': os.environ.get(
        f'ARBITRUM_{os.environ.get("BLOCKCHAIN_NETWORK", "testnet").upper()}_RPC_URL',
        'https://sepolia-rollup.arbitrum.io/rpc'
    ),
    'CONTRACT_ADDRESS': os.environ.get(
        f'COMMITMENT_REGISTRY_ADDRESS_{os.environ.get("BLOCKCHAIN_NETWORK", "testnet").upper()}',
        ''
    ),
    'BATCH_SIZE': int(os.environ.get('BLOCKCHAIN_BATCH_SIZE', '1000')),
    'BATCH_INTERVAL_HOURS': int(os.environ.get('BLOCKCHAIN_BATCH_INTERVAL_HOURS', '24')),
}

# ==============================================================================
# CELERY CONFIGURATION (Phase 2B.1)
# ==============================================================================

# Celery Configuration
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Celery Beat Schedule (Periodic Tasks)
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    # Anchor commitments to blockchain every 24 hours
    'anchor-commitments-to-blockchain': {
        'task': 'blockchain.tasks.anchor_pending_commitments',
        'schedule': crontab(hour='2', minute='0'),  # 2:00 AM UTC daily
    },
    # Verify blockchain anchors every 6 hours
    'verify-blockchain-anchors': {
        'task': 'blockchain.tasks.verify_blockchain_anchors',
        'schedule': crontab(minute='0', hour='*/6'),  # Every 6 hours
    },
    # Clean up old pending commitments weekly
    'cleanup-old-pending-commitments': {
        'task': 'blockchain.tasks.cleanup_old_pending_commitments',
        'schedule': crontab(day_of_week='sunday', hour='3', minute='0'),  # Sunday 3:00 AM UTC
    },
    # Vault maintenance tasks
    'cleanup-audit-logs-daily': {
        'task': 'vault.tasks.cleanup_old_audit_logs',
        'schedule': crontab(hour='4', minute='0'),  # 4:00 AM UTC daily
    },
    'cleanup-deleted-items-weekly': {
        'task': 'vault.tasks.cleanup_deleted_items',
        'schedule': crontab(day_of_week='sunday', hour='5', minute='0'),  # Sunday 5:00 AM UTC
    },
    'cleanup-cache-hourly': {
        'task': 'vault.tasks.cleanup_expired_cache',
        'schedule': crontab(minute='30'),  # Every hour at :30
    },
    # ==========================================================================
    # Adaptive Password Tasks
    # ==========================================================================
    # Aggregate typing profiles hourly
    'aggregate-typing-profiles': {
        'task': 'security.tasks.adaptive_tasks.aggregate_typing_profiles',
        'schedule': crontab(minute='15'),  # Every hour at :15
    },
    # Cleanup expired adaptation suggestions daily
    'cleanup-expired-adaptations': {
        'task': 'security.tasks.adaptive_tasks.cleanup_expired_adaptations',
        'schedule': crontab(hour='3', minute='30'),  # 3:30 AM UTC daily
    },
    # Update RL model weekly
    'update-adaptation-rl-model': {
        'task': 'security.tasks.adaptive_tasks.update_rl_model_from_feedback',
        'schedule': crontab(day_of_week='monday', hour='4', minute='0'),  # Monday 4:00 AM
    },
}

# ==============================================================================
# EPIGENETIC PASSWORD ADAPTATION CONFIGURATION
# ==============================================================================

ADAPTIVE_PASSWORD = {
    # Feature Flag
    'ENABLED': os.environ.get('ADAPTIVE_PASSWORD_ENABLED', 'True').lower() == 'true',
    
    # Privacy Settings
    'DEFAULT_OPT_IN': False,  # Opt-in by default (GDPR compliant)
    'DIFFERENTIAL_PRIVACY_EPSILON': float(os.environ.get('DP_EPSILON', '0.5')),
    
    # Suggestion Settings
    'SUGGESTION_FREQUENCY_DAYS': int(os.environ.get('ADAPTATION_FREQUENCY_DAYS', '30')),
    'MIN_SESSIONS_FOR_SUGGESTION': 10,
    'AUTO_APPLY_THRESHOLD': 0.9,  # Confidence threshold for auto-apply
    
    # Rollback Settings
    'MAX_ROLLBACK_DEPTH': 10,  # Maximum number of rollback versions
    'ADAPTATION_EXPIRY_DAYS': 7,  # Days before pending adaptations expire
    
    # ML Training Settings
    'ALLOW_CENTRALIZED_TRAINING': True,
    'ALLOW_FEDERATED_LEARNING': False,
    'RL_MODEL_UPDATE_INTERVAL_DAYS': 7,
    
    # Performance Settings
    'ASYNC_SUGGESTION_GENERATION': True,  # Use Celery for suggestions
    'MAX_ERROR_POSITIONS_STORED': 10,  # Limit for privacy
    'TIMING_BUCKET_COUNT': 9,  # Number of timing buckets
}

