"""
Django settings for password_manager project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1.15/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1.15/ref/settings/
"""
import os
import sys
import secrets
import warnings
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

# =============================================================================
# Warning Suppressions
# =============================================================================
# Import warning suppressions for TensorFlow, Keras, Django, and other packages
try:
    from .warning_suppressions import *
except ImportError:
    # Fallback if warning_suppressions.py doesn't exist yet
    pass

# Suppress known compatibility warnings from dj-rest-auth with django-allauth 65.x
# These warnings come from dj-rest-auth library code, not our configuration
warnings.filterwarnings('ignore', message='app_settings.USERNAME_REQUIRED is deprecated')
warnings.filterwarnings('ignore', message='app_settings.EMAIL_REQUIRED is deprecated')

# Load environment variables from .env file
load_dotenv()

# Handle Python 3.13+ cgi module removal
if sys.version_info >= (3, 13):
    try:
        import legacy_cgi
        sys.modules['cgi'] = legacy_cgi
        print("Loaded legacy-cgi package as replacement for built-in cgi module")
    except ImportError:
        # Try to find the package in the installed packages
        try:
            # This helps finding the package in some virtual environments
            import site
            site_packages = site.getsitepackages()
            for site_path in site_packages:
                legacy_cgi_path = os.path.join(site_path, 'legacy_cgi')
                if os.path.exists(legacy_cgi_path):
                    if legacy_cgi_path not in sys.path:
                        sys.path.append(legacy_cgi_path)
                    import legacy_cgi
                    sys.modules['cgi'] = legacy_cgi
                    print("Found and loaded legacy-cgi package from:", legacy_cgi_path)
                    break
        except (ImportError, Exception) as e:
            print(f"Warning: legacy-cgi package not found. Some features may not work correctly: {e}")
            print("Install with: pip install legacy-cgi")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1.15/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False — set DEBUG=True explicitly in development
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

# Development mode flag (defaults to match DEBUG)
DEVELOPMENT = os.environ.get('DEVELOPMENT', str(DEBUG)).lower() == 'true'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = secrets.token_urlsafe(50)
        warnings.warn("SECRET_KEY not set in environment. Using random key for development.")
    else:
        # In production, fail if SECRET_KEY is not set
        from django.core.exceptions import ImproperlyConfigured
        raise ImproperlyConfigured("The SECRET_KEY setting must not be empty in production.")

# Parse ALLOWED_HOSTS from environment variable (strip whitespace from each entry)
ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,127.0.0.1:8000,[::1]').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    # Django Channels must be before django.contrib.staticfiles
    'daphne',  # ASGI server for Channels
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    #'django.contrib.gis',  # Required for GeoIP functionality
    'django_extensions',
    
    # Third-party apps
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'drf_yasg',
    
    # Django Channels
    'channels',
    
    # Local apps
    'shared',
    'api',
    'vault',
    'auth_module',
    'two_factor',  # Two-Factor Authentication (TOTP)
    'user',
    'logging_manager',
    'security',
    'ml_security',  # Machine Learning Security
    'ml_dark_web',  # ML Dark Web Monitoring with WebSocket alerts
    'analytics',  # Analytics & Metrics
    'ab_testing',  # A/B Testing & Feature Flags
    'email_masking',  # Email Masking & Privacy
    'behavioral_recovery',  # Behavioral Biometric Recovery
    'blockchain',  # Blockchain Anchoring (Phase 2B)
    'fhe_service',  # Fully Homomorphic Encryption Service
    'fhe_sharing',  # Homomorphic Password Sharing (FHE autofill tokens)
    'adversarial_ai',  # Adversarial AI Password Defense
    'mesh_deaddrop',  # Dead Drop Password Sharing via Mesh Networks
    'neuro_feedback',  # Neuro-Feedback Password Training
    'cognitive_auth',  # Cognitive Password Testing with Implicit Memory
    'biometric_liveness',  # Deepfake-Resistant Biometric Liveness
    'password_archaeology',  # Password Archaeology & Time Travel
    'ai_assistant',  # AI-Powered Security Assistant (Claude API)
    'smart_contracts',  # Smart Contract Automation (Blockchain Conditional Access)
    # OAuth providers
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.apple',
    'allauth.socialaccount.providers.github',
    'push_notifications',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',  # Token blacklisting for JWT rotation
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    # FIX: CSRF exemption for auth endpoints - MUST be before CsrfViewMiddleware
    'middleware.CSRFExemptAuthMiddleware',
    # Disable HTTPS redirect in development - causes ASGI issues
    # 'middleware.HttpsRedirectMiddleware',
    'middleware.SecurityHeadersMiddleware',
    # Response compression (near top for efficiency)
    'password_manager.compression_middleware.VaultCompressionMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # CommonMiddleware removed - not compatible with ASGI/Channels and not needed for API/SPA
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Required for django-allauth
    'middleware.SecurityMiddleware',  # Custom security middleware - MUST be after AuthenticationMiddleware
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Cache control for vault endpoints
    'password_manager.compression_middleware.CacheControlMiddleware',
    # Performance monitoring (should be near the end to measure full request/response cycle)
    'shared.performance_middleware.PerformanceMonitoringMiddleware',
    'shared.performance_middleware.DatabaseQueryMonitoringMiddleware',
    'shared.performance_middleware.APIPerformanceMiddleware',
    'shared.performance_middleware.CachePerformanceMiddleware',
]

# Response compression settings
ENABLE_RESPONSE_COMPRESSION = True

# Disable APPEND_SLASH for this API-first SPA architecture.
# DRF endpoints define explicit paths; trailing-slash redirects add an unnecessary
# 301 round-trip for API clients. NOT an ASGI/Channels requirement — purely an
# API design choice. Keep False unless adding server-rendered form views.
APPEND_SLASH = False

ROOT_URLCONF = 'password_manager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'password_manager.wsgi.application'
ASGI_APPLICATION = 'password_manager.asgi.application'

# Django Channels Layer Configuration
# Uses Redis when USE_REDIS_CHANNELS=True, otherwise In-Memory for development
if os.environ.get('USE_REDIS_CHANNELS', 'False').lower() == 'true':
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [(
                    os.environ.get('REDIS_HOST', 'localhost'),
                    int(os.environ.get('REDIS_PORT', 6379))
                )],
                'capacity': 1500,
                'expiry': 10,
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer'
        }
    }
# Database configuration
# https://docs.djangoproject.com/en/5.1.15/ref/settings/#databases

_USE_POSTGRES = bool(os.environ.get('DB_NAME'))

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql' if _USE_POSTGRES else 'django.db.backends.sqlite3',
        'NAME': os.environ.get('DB_NAME') if _USE_POSTGRES else BASE_DIR / 'db.sqlite3',
        'USER': os.environ.get('DB_USER', 'test_user'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'test_password'),
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DB_PORT', '5432'),
        'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '60')),
        'CONN_HEALTH_CHECKS': _USE_POSTGRES,
        'OPTIONS': {
            'connect_timeout': 10,
            'options': '-c statement_timeout=30000',
            # Disable server-side prepared statements for PgBouncer transaction-mode compat
            'prepare_threshold': int(os.environ.get('DB_PREPARE_THRESHOLD', '0')) or None,
        } if _USE_POSTGRES else {},
    },
    'postgresql': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'test_db'),
        'USER': os.environ.get('DB_USER', 'test_user'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'test_password'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
        'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '60')),
        'CONN_HEALTH_CHECKS': True,
        'OPTIONS': {
            'connect_timeout': 10,
            'options': '-c statement_timeout=30000',
            'prepare_threshold': int(os.environ.get('DB_PREPARE_THRESHOLD', '0')) or None,
        },
    }    
}

# Read replica (optional — activated by setting DATABASE_REPLICA_URL or DB_REPLICA_HOST)
_REPLICA_HOST = os.environ.get('DB_REPLICA_HOST', '')
if _USE_POSTGRES and _REPLICA_HOST:
    DATABASES['replica'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_REPLICA_USER', os.environ.get('DB_USER', 'test_user')),
        'PASSWORD': os.environ.get('DB_REPLICA_PASSWORD', os.environ.get('DB_PASSWORD', 'test_password')),
        'HOST': _REPLICA_HOST,
        'PORT': os.environ.get('DB_REPLICA_PORT', os.environ.get('DB_PORT', '5432')),
        'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '60')),
        'CONN_HEALTH_CHECKS': True,
        'OPTIONS': {
            'connect_timeout': 10,
            'options': '-c statement_timeout=30000 -c default_transaction_read_only=on',
            'prepare_threshold': int(os.environ.get('DB_PREPARE_THRESHOLD', '0')) or None,
        },
    }

DATABASE_ROUTERS = ['shared.db_router.PrimaryReplicaRouter']

# Cache Configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 300,  # 5 minutes default
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
            'CULL_FREQUENCY': 3,
        }
    },
    # Dedicated cache for rate limiting.
    # Uses locmem in development; override to Redis in production via
    # USE_REDIS_CACHE=True so that rate counters survive restarts and
    # are shared across workers.  Without Redis, a Daphne/Celery restart
    # resets all counters, allowing users to bypass limits.
    'rate_limiting': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'rate-limiting-cache',
        'TIMEOUT': 3600,  # 1 hour default for rate windows
    }
}

# Redis Cache Configuration (for Kyber hybrid caching)
# Enable by setting USE_REDIS_CACHE=True in environment
if os.environ.get('USE_REDIS_CACHE', 'False').lower() == 'true':
    CACHES['default'] = {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SOCKET_CONNECT_TIMEOUT': 5,
            'SOCKET_TIMEOUT': 5,
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 50,
            },
            'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
        },
        'KEY_PREFIX': 'kyber',
        'TIMEOUT': 3600,  # 1 hour default for Kyber keys
    }
    
    # Rate limiting cache — Redis ensures counters survive restarts
    CACHES['rate_limiting'] = {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SOCKET_CONNECT_TIMEOUT': 5,
            'SOCKET_TIMEOUT': 5,
        },
        'KEY_PREFIX': 'ratelimit',
        'TIMEOUT': 3600,
    }
    
    # Add dedicated Kyber cache
    CACHES['kyber'] = {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/2'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SOCKET_CONNECT_TIMEOUT': 5,
            'SOCKET_TIMEOUT': 5,
        },
        'KEY_PREFIX': 'kyber',
        'TIMEOUT': 86400,  # 24 hours for public keys
    }

# Kyber Cache Configuration
KYBER_CACHE_SETTINGS = {
    'USE_REDIS': os.environ.get('USE_REDIS_CACHE', 'False').lower() == 'true',
    'REDIS_ALIAS': 'kyber' if os.environ.get('USE_REDIS_CACHE', 'False').lower() == 'true' else 'default',
    'PUBLIC_KEY_TTL': 86400,  # 24 hours
    'SESSION_TTL': 3600,  # 1 hour
    'SHARED_SECRET_TTL': 300,  # 5 minutes
    'LRU_CACHE_SIZE': 256,
}



# Password validation
# https://docs.djangoproject.com/en/5.1.15/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 12,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Authentication settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        #'rest_framework.authentication.SessionAuthentication',  # removed for SPA JWT usage
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.NamespaceVersioning',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 100,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.environ.get('RATE_LIMIT_ANON', '100/minute') if DEBUG else os.environ.get('RATE_LIMIT_ANON', '10/minute'),
        'user': os.environ.get('RATE_LIMIT_USER', '200/minute') if DEBUG else os.environ.get('RATE_LIMIT_USER', '60/minute'),
        'auth': os.environ.get('RATE_LIMIT_AUTH', '30/minute') if DEBUG else os.environ.get('RATE_LIMIT_AUTH', '3/minute'),
        'password_check': '5/hour',  # Reduced breach checks
        'security': '20/hour',  # Security operations
        'passkey': '10/minute',  # WebAuthn operations
        'vault': '100/hour',  # Reasonable vault operations
        'dj_rest_auth': '10/minute',  # dj-rest-auth operations
        'ml_inference': '10/minute',      # BERT, Siamese ML models
        'fhe_operation': '5/minute',      # FHE encrypt/decrypt
        'biometric_frame': '60/minute',   # Video frame submission
        'websocket_connect': '5/minute',  # WS connection rate
        'dark_web_scan': '1/hour',        # Manual scan trigger
        'analytics_track': '30/minute',   # Anonymous analytics submission (Item #3)
        'what_if_simulation': '10/hour',  # CPU-intensive what-if scenarios
        'deaddrop_collect': '5/minute',   # Fragment collection per IP
    }
}

# Additional throttling settings
ANON_VAULT_RATE = '10/hour'  # Rate limit for anonymous vault access

# Password hashing
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]

# Internationalization
# https://docs.djangoproject.com/en/5.1.15/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1.15/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1.15/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==============================================================================
# CORS CONFIGURATION (JWT-based SPA - No cookies/sessions for API)
# ==============================================================================
# Note: Detailed CORS configuration is below (after security settings)
# This placeholder ensures CORS is configured before other settings reference it

# AWS S3 settings
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', '')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', '')
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com' if AWS_STORAGE_BUCKET_NAME else ''
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}
AWS_DEFAULT_ACL = 'private'

# Google Cloud Storage Configuration (for vault backups)
CLOUD_STORAGE_BUCKET = os.environ.get('CLOUD_STORAGE_BUCKET', '')
GOOGLE_CLOUD_CREDENTIALS = os.environ.get('GOOGLE_CLOUD_CREDENTIALS', '')

# Site ID for django-allauth
SITE_ID = 1

# Security settings
SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = os.environ.get('DJANGO_SESSION_COOKIE_SECURE', 'False') == 'True'
CSRF_COOKIE_SECURE = os.environ.get('DJANGO_CSRF_COOKIE_SECURE', 'False') == 'True'


# CSRF Trusted Origins (for SPA development)
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:4173',
    'http://127.0.0.1:4173',
]

# Add production origins from environment
csrf_origins_env = os.environ.get('CSRF_TRUSTED_ORIGINS', '').strip()
if csrf_origins_env:
    CSRF_TRUSTED_ORIGINS.extend([origin.strip() for origin in csrf_origins_env.split(',') if origin.strip()])

# NOTE: Logging configuration merged into Enhanced Logging block below

# Authentication backends
AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin
    'django.contrib.auth.backends.ModelBackend',
    # allauth specific authentication methods
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Provider specific settings - Use environment variables
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.environ.get('GOOGLE_OAUTH_CLIENT_ID', ''),
            'secret': os.environ.get('GOOGLE_OAUTH_CLIENT_SECRET', ''),
            'key': ''
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    },
    'apple': {
        'APP': {
            'client_id': os.environ.get('APPLE_OAUTH_CLIENT_ID', ''),
            'secret': os.environ.get('APPLE_OAUTH_CLIENT_SECRET', ''),
            'key': os.environ.get('APPLE_OAUTH_KEY_ID', ''),
            'team': os.environ.get('APPLE_OAUTH_TEAM_ID', ''),
            'certificate_key': os.environ.get('APPLE_OAUTH_PRIVATE_KEY', '')
        },
        'SCOPE': ['email', 'name']
    },
    'github': {
        'APP': {
            'client_id': os.environ.get('GITHUB_OAUTH_CLIENT_ID', ''),
            'secret': os.environ.get('GITHUB_OAUTH_CLIENT_SECRET', ''),
        },
        'SCOPE': ['user:email', 'read:user']
    }
}

# ==============================================================================
# EMAIL & NOTIFICATION CONFIGURATION
# ==============================================================================

# Email settings for account recovery and notifications
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.example.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

# Email addresses
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'SecureVault <noreply@securevault.com>')
SECURITY_EMAIL = os.environ.get('SECURITY_EMAIL', 'security@securevault.com')

# Frontend URL (for email links)
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')

# AllAuth settings
# Note: The UserWarnings from dj_rest_auth are from the dj-rest-auth library itself,
# not from this configuration. They will be fixed when dj-rest-auth updates to the new format.
# Our configuration here is correct for django-allauth 65.x
ACCOUNT_SIGNUP_FIELDS = ['username', 'email*', 'password1*', 'password2*']
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_LOGOUT_ON_GET = True
ACCOUNT_UNIQUE_EMAIL = True

# Authy settings
AUTHY_API_KEY = os.environ.get('AUTHY_API_KEY', '')

# Push notification settings
PUSH_NOTIFICATIONS_SETTINGS = {
    'FCM_API_KEY': os.environ.get('FCM_API_KEY', ''),
    'GCM_API_KEY': os.environ.get('GCM_API_KEY', ''),
    'APNS_CERTIFICATE': os.path.join(BASE_DIR, 'certs', 'apns-cert.pem'),
    'WP_PRIVATE_KEY': os.path.join(BASE_DIR, 'certs', 'windows_private.pem'),
    'WP_CLAIMS': {'sub': f"mailto:{os.environ.get('WP_VAPID_EMAIL', 'admin@example.com')}"}
}

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),  # Short-lived access tokens
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     # Longer-lived refresh tokens
    'ROTATE_REFRESH_TOKENS': True,                   # Enable refresh token rotation
    'BLACKLIST_AFTER_ROTATION': True,                # Blacklist old tokens after rotation
    'UPDATE_LAST_LOGIN': True,                       # Track last login
    
    # Refresh Token Family (Security Enhancement)
    'REFRESH_TOKEN_ROTATE_ON_USE': True,             # Rotate token on each use
    'REFRESH_TOKEN_FAMILY_MAX_SIZE': 5,              # Limit concurrent devices to 5
    
    # Algorithm settings
    # To upgrade to RS256 (recommended for multi-service architectures):
    #   1. Generate an RSA keypair:
    #      openssl genrsa -out jwt-private.pem 4096
    #      openssl rsa -in jwt-private.pem -pubout -out jwt-public.pem
    #   2. Set env vars JWT_ALGORITHM=RS256, JWT_PRIVATE_KEY=<contents of jwt-private.pem>,
    #      JWT_PUBLIC_KEY=<contents of jwt-public.pem>
    #   3. Only the auth service needs the private key; all other services
    #      verify tokens with the public key alone, eliminating shared-secret risk.
    'ALGORITHM': os.environ.get('JWT_ALGORITHM', 'HS256'),
    'SIGNING_KEY': os.environ.get('JWT_PRIVATE_KEY', SECRET_KEY),
    'VERIFYING_KEY': os.environ.get('JWT_PUBLIC_KEY', None),
    
    # Audience and issuer claims for added security
    'AUDIENCE': None,
    'ISSUER': 'password_manager',
    
    # Token classes
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    
    # Token type headers
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    
    # Custom serializer for refresh token family enforcement (Item #1)
    # Blacklists oldest outstanding tokens when concurrent device count
    # exceeds REFRESH_TOKEN_FAMILY_MAX_SIZE. Oldest is determined by
    # OutstandingToken.created_at timestamp.
    'TOKEN_OBTAIN_SERIALIZER': 'auth_module.token_family.FamilyLimitedTokenObtainPairSerializer',
}


# Firebase Settings
FIREBASE_PROJECT_ID = os.environ.get('FIREBASE_PROJECT_ID', '')
FIREBASE_PRIVATE_KEY_ID = os.environ.get('FIREBASE_PRIVATE_KEY_ID', '')
FIREBASE_PRIVATE_KEY = os.environ.get('FIREBASE_PRIVATE_KEY', '').replace('\\n', '\n')
FIREBASE_CLIENT_EMAIL = os.environ.get('FIREBASE_CLIENT_EMAIL', '')
FIREBASE_CLIENT_ID = os.environ.get('FIREBASE_CLIENT_ID', '')
FIREBASE_CLIENT_CERT_URL = os.environ.get('FIREBASE_CLIENT_CERT_URL', '')
FIREBASE_DATABASE_URL = os.environ.get('FIREBASE_DATABASE_URL', '')

# =============================================================================
# Feature Flags — Module Enable/Disable
# =============================================================================

# AI Assistant module (Claude-powered)
AI_ASSISTANT_ENABLED = os.environ.get('AI_ASSISTANT_ENABLED', 'True').lower() in ('true', '1', 'yes')

# Adversarial AI module (password strength simulation)
ADVERSARIAL_AI_ENABLED = os.environ.get('ADVERSARIAL_AI_ENABLED', 'True').lower() in ('true', '1', 'yes')

# =============================================================================
# PKCE Configuration (OAuth2 Proof Key for Code Exchange)
# =============================================================================
# Required for public clients (mobile apps, browser extensions) that cannot
# securely store a client_secret.
# ACTION REQUIRED: Flip to 'True' (or set env var OAUTH_PKCE_REQUIRED=true)
# before shipping mobile or browser-extension clients.  Without PKCE,
# authorization-code flows for public clients are vulnerable to code
# interception attacks.  See RFC 7636 for details.
OAUTH_PKCE_REQUIRED = os.environ.get('OAUTH_PKCE_REQUIRED', 'False').lower() in ('true', '1', 'yes')
OAUTH_PKCE_CODE_CHALLENGE_METHOD = 'S256'
OAUTH_PKCE_CODE_VERIFIER_MIN_LENGTH = 43
OAUTH_PKCE_CODE_VERIFIER_MAX_LENGTH = 128

# GeoIP Database Configuration
# Download GeoLite2-City.mmdb and GeoLite2-Country.mmdb from MaxMind
# Instructions:
# 1. Register at https://www.maxmind.com/en/geolite2/signup
# 2. Download GeoLite2-City.mmdb and GeoLite2-Country.mmdb
# 3. Place them in the directory specified by GEOIP_PATH
# You can also set this via environment variable: GEOIP_PATH
GEOIP_PATH = os.environ.get('GEOIP_PATH', os.path.join(BASE_DIR, 'geoip'))

# Create the GeoIP directory if it doesn't exist
os.makedirs(GEOIP_PATH, exist_ok=True)

# GeoIP database files (optional - will work without them but with reduced functionality)
GEOIP_CITY = 'GeoLite2-City.mmdb'
GEOIP_COUNTRY = 'GeoLite2-Country.mmdb'


# Security Service Configuration
MAX_FAILED_ATTEMPTS = 5
LOCKOUT_DURATION_MINUTES = 30
SUSPICIOUS_THRESHOLD = 3
_blacklisted = os.environ.get('BLACKLISTED_IPS', '')
BLACKLISTED_IPS = set(_blacklisted.split(',')) if _blacklisted else set()

# IP Whitelisting (Enterprise Feature - Optional)
# Set ALLOWED_IP_RANGES in .env for IP restriction
# Example: ALLOWED_IP_RANGES=192.168.1.0/24,10.0.0.0/8
ALLOWED_IP_RANGES = os.environ.get('ALLOWED_IP_RANGES', '').split(',') if os.environ.get('ALLOWED_IP_RANGES') else []
IP_WHITELISTING_ENABLED = os.environ.get('IP_WHITELISTING_ENABLED', 'False').lower() == 'true'

# ==============================================================================
# SMS NOTIFICATION CONFIGURATION (Twilio)
# ==============================================================================

# SMS Service (Optional - for Twilio integration)
# Configure these in your .env file for production:
# TWILIO_ACCOUNT_SID=your_actual_account_sid
# TWILIO_AUTH_TOKEN=your_actual_auth_token
# TWILIO_PHONE_NUMBER=+1234567890
TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN', '')
TWILIO_PHONE_NUMBER = os.environ.get('TWILIO_PHONE_NUMBER', '')
TWILIO_ENABLED = os.environ.get('TWILIO_ENABLED', 'False').lower() == 'true'

# Enhanced Security Configuration
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Force HTTPS in production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# ==============================================================================
# ENHANCED CORS SETTINGS FOR JWT-BASED SPA
# ==============================================================================

# CORS settings for frontend (JWT-based SPA - no cookies for API auth)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",   # Vite default dev port
    "http://127.0.0.1:5173",
    "http://localhost:3000",   # Alternative React dev port
    "http://127.0.0.1:3000",
    "http://localhost:4173",   # Vite preview port
    "http://127.0.0.1:4173",
    "http://localhost:8000",   # Django dev server (for testing)
    "http://127.0.0.1:8000",
]

# When using JWT auth (Authorization header), no cookies are required for API calls.
# Set to False to avoid exposing cookies unnecessarily.
# Note: WebSocket connections using query param tokens also work without credentials=True
CORS_ALLOW_CREDENTIALS = False

CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS',
]

CORS_ALLOW_HEADERS = [
    'Authorization',           # Required for JWT (Bearer token)
    'Content-Type',
    'X-CSRFToken',            # Required for Django admin/form CSRF on cross-origin requests
    'X-Device-Fingerprint',   # Custom security header
    'Accept',
    'Origin',
    'User-Agent',
    'DNT',
    'Cache-Control',
    'X-Requested-With',
]

CORS_EXPOSE_HEADERS = [
    'Content-Length',
]

CORS_PREFLIGHT_MAX_AGE = 86400  # 24 hours

# Add production origins from environment
env_origins = os.environ.get('CORS_ALLOWED_ORIGINS', '').strip()
if env_origins:
    parsed_origins = [origin.strip() for origin in env_origins.split(',') if origin.strip()]
    if '*' in parsed_origins:
        raise ValueError("Wildcard CORS origin '*' is not allowed. Set explicit frontend origins only.")
    CORS_ALLOWED_ORIGINS.extend(parsed_origins)

# Hard fail if wildcard sneaks in from any source.
if '*' in CORS_ALLOWED_ORIGINS:
    raise ValueError("Wildcard CORS origin '*' is not allowed. Use explicit trusted origins.")

# Strict CSP policy used by SecurityHeadersMiddleware.
SECURITY_CSP_POLICY = (
    "default-src 'self'; "
    "script-src 'self' https://cdn.jsdelivr.net; "
    "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; "
    "font-src 'self' https://fonts.gstatic.com; "
    "img-src 'self' data: blob:; "
    "connect-src 'self' wss: ws: https://api.haveibeenpwned.com; "
    "object-src 'none'; "
    "base-uri 'self'; "
    "frame-ancestors 'none'; "
    "form-action 'self'"
)



# ==============================================================================
# SESSION & CSRF CONFIGURATION (For admin/WebSocket only - API uses JWT)
# ==============================================================================

# Session configuration (used for Django admin, not for SPA API)
SESSION_COOKIE_AGE = 3600  # 1 hour
SESSION_COOKIE_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax' if DEBUG else 'Strict'  # Relaxed for dev

# CSRF configuration (not needed for JWT API calls, but used for admin/forms)
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax' if DEBUG else 'Strict'  # Relaxed for dev
CSRF_USE_SESSIONS = False  # Use cookie-based CSRF (default); sessions not needed for JWT API

# ==============================================================================
# LOGGING CONFIGURATION (12-Factor XI compliant)
# ==============================================================================
# Production (DEBUG=False): stream ALL logs to stdout (console handler) + DB.
#   Log collectors (Fluentd, Datadog, CloudWatch) consume stdout automatically.
#   File handlers are removed — container filesystems are ephemeral.
# Development (DEBUG=True): keep file handlers as a convenience for developers.

LOGS_DIR = os.path.join(BASE_DIR, 'logs')

# Build handlers and loggers conditionally
_logging_handlers = {
    'db': {
        'level': 'INFO',
        'class': 'logging_manager.handlers.DatabaseLogHandler',
        'formatter': 'verbose',
    },
    'console': {
        'level': 'DEBUG' if DEBUG else 'INFO',
        'class': 'logging.StreamHandler',
        'formatter': 'verbose' if not DEBUG else 'simple',
    },
}

if DEBUG:
    # Local development: add file handlers for convenience
    os.makedirs(LOGS_DIR, exist_ok=True)
    _logging_handlers['file'] = {
        'level': 'INFO',
        'class': 'logging.FileHandler',
        'filename': os.path.join(LOGS_DIR, 'django.log'),
        'formatter': 'verbose',
    }
    _logging_handlers['security_file'] = {
        'level': 'WARNING',
        'class': 'logging.FileHandler',
        'filename': os.path.join(LOGS_DIR, 'security.log'),
        'formatter': 'verbose',
    }

# In production, all loggers route to console + db (stdout streaming).
# In development, loggers also write to file handlers.
_dev_django_handlers = ['console', 'file', 'db'] if DEBUG else ['console', 'db']
_dev_security_handlers = ['console', 'security_file', 'db'] if DEBUG else ['console', 'db']
_dev_vault_handlers = ['console', 'file', 'db'] if DEBUG else ['console', 'db']
_dev_auth_handlers = ['console', 'security_file'] if DEBUG else ['console']

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': _logging_handlers,
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': _dev_django_handlers,
            'level': 'INFO',
            'propagate': False,
        },
        'security': {
            'handlers': _dev_security_handlers,
            'level': 'WARNING',
            'propagate': False,
        },
        'vault': {
            'handlers': _dev_vault_handlers,
            'level': 'INFO',
            'propagate': False,
        },
        'auth_module': {
            'handlers': _dev_auth_handlers,
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# ==============================================================================
# FIDO2/WebAuthn Passkey Configuration
# ==============================================================================

# Relying Party (RP) Configuration
PASSKEY_RP_ID = os.environ.get('PASSKEY_RP_ID', 'localhost')
PASSKEY_RP_NAME = os.environ.get('PASSKEY_RP_NAME', 'Password Manager')

# Allowed origins for WebAuthn operations
passkey_origins_env = os.environ.get('PASSKEY_ALLOWED_ORIGINS', '').strip()
PASSKEY_ALLOWED_ORIGINS = [origin.strip() for origin in passkey_origins_env.split(',') if origin.strip()]

# Add localhost origins for development
if DEBUG:
    PASSKEY_ALLOWED_ORIGINS.extend([
        'http://localhost:5173',   # Vite default
        'http://127.0.0.1:5173',
        'http://localhost:3000',
        'http://127.0.0.1:3000',
        'http://localhost:4173',
        'http://127.0.0.1:4173',
        'http://localhost:8000',
        'http://127.0.0.1:8000',
    ])

# Passkey settings
PASSKEY_TIMEOUT = 300000  # 5 minutes in milliseconds
PASSKEY_USER_VERIFICATION = 'preferred'  # 'required', 'preferred', or 'discouraged'
PASSKEY_AUTHENTICATOR_ATTACHMENT = 'platform'  # 'platform' or 'cross-platform'

# ==============================================================================
# PERFORMANCE MONITORING CONFIGURATION
# ==============================================================================

# Enable/disable performance metric collection
STORE_PERFORMANCE_METRICS = os.environ.get('STORE_PERFORMANCE_METRICS', 'True').lower() == 'true'
STORE_API_METRICS = os.environ.get('STORE_API_METRICS', 'True').lower() == 'true'

# Performance thresholds
SLOW_REQUEST_THRESHOLD = float(os.environ.get('SLOW_REQUEST_THRESHOLD', '1.0'))  # seconds
QUERY_COUNT_THRESHOLD = int(os.environ.get('QUERY_COUNT_THRESHOLD', '50'))  # number of queries

# System resource monitoring thresholds
CPU_WARNING_THRESHOLD = float(os.environ.get('CPU_WARNING_THRESHOLD', '80'))  # percentage
MEMORY_WARNING_THRESHOLD = float(os.environ.get('MEMORY_WARNING_THRESHOLD', '80'))  # percentage
DISK_WARNING_THRESHOLD = float(os.environ.get('DISK_WARNING_THRESHOLD', '80'))  # percentage

# Error rate threshold for alerting
ERROR_RATE_THRESHOLD = float(os.environ.get('ERROR_RATE_THRESHOLD', '5'))  # percentage

# Performance metric retention (days)
PERFORMANCE_METRIC_RETENTION_DAYS = int(os.environ.get('PERFORMANCE_METRIC_RETENTION_DAYS', '30'))
ERROR_LOG_RETENTION_DAYS = int(os.environ.get('ERROR_LOG_RETENTION_DAYS', '90'))
SYSTEM_METRIC_RETENTION_DAYS = int(os.environ.get('SYSTEM_METRIC_RETENTION_DAYS', '7'))

# ML model training interval (hours)
ML_MODEL_TRAINING_INTERVAL = int(os.environ.get('ML_MODEL_TRAINING_INTERVAL', '24'))

# System resource monitoring interval (seconds)
SYSTEM_MONITORING_INTERVAL = int(os.environ.get('SYSTEM_MONITORING_INTERVAL', '60'))

# ==============================================================================
# BEHAVIORAL RECOVERY SETTINGS
# ==============================================================================

# Behavioral Recovery Configuration
BEHAVIORAL_RECOVERY = {
    'SIMILARITY_THRESHOLD': float(os.environ.get('BEHAVIORAL_SIMILARITY_THRESHOLD', '0.87')),
    'RECOVERY_TIMELINE_DAYS': int(os.environ.get('BEHAVIORAL_RECOVERY_DAYS', '5')),
    'MIN_SAMPLES_PER_CHALLENGE': int(os.environ.get('MIN_SAMPLES_PER_CHALLENGE', '50')),
    'DIFFERENTIAL_PRIVACY_EPSILON': float(os.environ.get('DIFFERENTIAL_PRIVACY_EPSILON', '0.5')),
    'EMBEDDING_DIMENSION': 128,  # 128-dimensional behavioral DNA
    'INPUT_DIMENSION': 247,      # 247-dimensional input features
    'ENABLED': os.environ.get('BEHAVIORAL_RECOVERY_ENABLED', 'True').lower() == 'true',
}

# Post-Quantum Cryptography Configuration (Phase 2A)
QUANTUM_CRYPTO = {
    'ENABLED': os.environ.get('QUANTUM_CRYPTO_ENABLED', 'True').lower() == 'true',
    'ALGORITHM': os.environ.get('QUANTUM_ALGORITHM', 'Kyber768'),
    'FALLBACK_ENABLED': os.environ.get('QUANTUM_FALLBACK_ENABLED', 'True').lower() == 'true',
    'HYBRID_MODE': True,  # Always use hybrid Kyber + AES-256-GCM
    'ALLOW_SIMULATION': DEBUG,  # Only allow simulation in DEBUG mode
}

# ==============================================================================
# OPENID CONNECT (OIDC) CONFIGURATION
# ==============================================================================

# OIDC enables enterprise SSO integration (Okta, Azure AD, Auth0, etc.)
# and provides ID token validation for secure identity verification.

# Enable/disable OIDC features
OIDC_ENABLED = os.environ.get('OIDC_ENABLED', 'True').lower() == 'true'

# OIDC Provider Configuration
# These can be configured via environment variables or directly here
OIDC_PROVIDERS = {
    # Microsoft Azure AD / Entra ID
    'microsoft': {
        'client_id': os.environ.get('MICROSOFT_OAUTH_CLIENT_ID', ''),
        'client_secret': os.environ.get('MICROSOFT_OAUTH_CLIENT_SECRET', ''),
        'tenant_id': os.environ.get('MICROSOFT_TENANT_ID', 'common'),
        'discovery_url': f"https://login.microsoftonline.com/{os.environ.get('MICROSOFT_TENANT_ID', 'common')}/v2.0/.well-known/openid-configuration",
        'scopes': ['openid', 'profile', 'email', 'User.Read'],
    },
    # Okta
    'okta': {
        'client_id': os.environ.get('OKTA_OAUTH_CLIENT_ID', ''),
        'client_secret': os.environ.get('OKTA_OAUTH_CLIENT_SECRET', ''),
        'domain': os.environ.get('OKTA_DOMAIN', ''),
        'discovery_url': f"https://{os.environ.get('OKTA_DOMAIN', 'example.okta.com')}/.well-known/openid-configuration",
        'scopes': ['openid', 'profile', 'email'],
    },
    # Auth0
    'auth0': {
        'client_id': os.environ.get('AUTH0_CLIENT_ID', ''),
        'client_secret': os.environ.get('AUTH0_CLIENT_SECRET', ''),
        'domain': os.environ.get('AUTH0_DOMAIN', ''),
        'discovery_url': f"https://{os.environ.get('AUTH0_DOMAIN', 'example.auth0.com')}/.well-known/openid-configuration",
        'scopes': ['openid', 'profile', 'email'],
    },
    # Generic OIDC Provider (for custom enterprise SSO)
    'generic': {
        'client_id': os.environ.get('OIDC_CLIENT_ID', ''),
        'client_secret': os.environ.get('OIDC_CLIENT_SECRET', ''),
        'discovery_url': os.environ.get('OIDC_DISCOVERY_URL', ''),
        'scopes': os.environ.get('OIDC_SCOPES', 'openid profile email').split(),
    },
}

# Filter out unconfigured providers
OIDC_PROVIDERS = {
    name: config for name, config in OIDC_PROVIDERS.items()
    if config.get('client_id') and config.get('client_secret')
}

# OIDC Security Settings
OIDC_NONCE_TTL = int(os.environ.get('OIDC_NONCE_TTL', '600'))  # 10 minutes
OIDC_STATE_TTL = int(os.environ.get('OIDC_STATE_TTL', '600'))  # 10 minutes
OIDC_JWKS_CACHE_TTL = int(os.environ.get('OIDC_JWKS_CACHE_TTL', '3600'))  # 1 hour

# ID Token validation settings
OIDC_VERIFY_SSL = os.environ.get('OIDC_VERIFY_SSL', 'True').lower() == 'true'
OIDC_CLOCK_SKEW_SECONDS = int(os.environ.get('OIDC_CLOCK_SKEW_SECONDS', '120'))

# Auto-create users from OIDC claims
OIDC_CREATE_USER = os.environ.get('OIDC_CREATE_USER', 'True').lower() == 'true'
OIDC_UPDATE_USER = os.environ.get('OIDC_UPDATE_USER', 'True').lower() == 'true'

# ==============================================================================
# PASSKEY RECOVERY CONFIGURATION
# ==============================================================================

# Primary Recovery Settings
PASSKEY_RECOVERY = {
    'KEY_LENGTH': 24,  # Characters in recovery key (excluding hyphens)
    'KEY_FORMAT': 'XXXX-XXXX-XXXX-XXXX-XXXX-XXXX',
    'MAX_BACKUPS_PER_USER': int(os.environ.get('MAX_RECOVERY_BACKUPS', '5')),
    'BACKUP_EXPIRY_DAYS': int(os.environ.get('RECOVERY_BACKUP_EXPIRY_DAYS', '365')),
    'MAX_RECOVERY_ATTEMPTS_PER_HOUR': int(os.environ.get('MAX_RECOVERY_ATTEMPTS', '3')),
    'LOCKOUT_DURATION_HOURS': int(os.environ.get('RECOVERY_LOCKOUT_HOURS', '24')),
}

# Recovery Rate Limiting
RECOVERY_THROTTLE_RATE = os.environ.get('RECOVERY_THROTTLE_RATE', '3/hour')
RECOVERY_INITIATE_RATE = os.environ.get('RECOVERY_INITIATE_RATE', '5/hour')
RECOVERY_COMPLETE_RATE = os.environ.get('RECOVERY_COMPLETE_RATE', '3/hour')

# Security Alert Configuration
SECURITY_ALERT_EMAIL = os.environ.get('SECURITY_ALERT_EMAIL', SECURITY_EMAIL)
RECOVERY_ALERT_THRESHOLD = int(os.environ.get('RECOVERY_ALERT_THRESHOLD', '5'))

# Blockchain Anchoring Configuration (Phase 2B)
BLOCKCHAIN_ANCHORING = {
    'ENABLED': os.environ.get('BLOCKCHAIN_ENABLED', 'False').lower() == 'true',
    'NETWORK': os.environ.get('BLOCKCHAIN_NETWORK', 'testnet'),  # 'testnet' or 'mainnet'
    'RPC_URL': os.environ.get(
        f'ARBITRUM_{os.environ.get("BLOCKCHAIN_NETWORK", "testnet").upper()}_RPC_URL',
        'https://sepolia-rollup.arbitrum.io/rpc'
    ),
    'CONTRACT_ADDRESS': os.environ.get(
        f'COMMITMENT_REGISTRY_ADDRESS_{os.environ.get("BLOCKCHAIN_NETWORK", "testnet").upper()}',
        ''
    ),
    'BATCH_SIZE': int(os.environ.get('BLOCKCHAIN_BATCH_SIZE', '1000')),
    'BATCH_INTERVAL_HOURS': int(os.environ.get('BLOCKCHAIN_BATCH_INTERVAL_HOURS', '24')),
}

# Smart Contract Automation Configuration
SMART_CONTRACT_AUTOMATION = {
    'ENABLED': os.environ.get('SMART_CONTRACTS_ENABLED', 'False').lower() == 'true',
    'TIMELOCKED_VAULT_ADDRESS': os.environ.get('TIMELOCKED_VAULT_ADDRESS', ''),
    'CHAINLINK_ETH_USD_ORACLE': os.environ.get(
        'CHAINLINK_ETH_USD_ORACLE',
        ''
    ),
    'DEFAULT_CHECK_IN_INTERVAL_DAYS': int(os.environ.get('SC_DEFAULT_CHECKIN_DAYS', '30')),
    'DEFAULT_GRACE_PERIOD_DAYS': int(os.environ.get('SC_DEFAULT_GRACE_DAYS', '7')),
    'MAX_MULTI_SIG_SIGNERS': int(os.environ.get('SC_MAX_MULTISIG_SIGNERS', '10')),
    'DAO_DEFAULT_QUORUM_PERCENT': int(os.environ.get('SC_DAO_QUORUM_PERCENT', '51')),
    'DAO_VOTING_PERIOD_DAYS': int(os.environ.get('SC_DAO_VOTING_DAYS', '7')),
    'ORACLE_CACHE_TTL_SECONDS': int(os.environ.get('SC_ORACLE_CACHE_TTL', '300')),
}

# ==============================================================================
# CELERY CONFIGURATION (Phase 2B.1)
# ==============================================================================

# Celery Configuration
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Queue separation: CPU-heavy ML/blockchain tasks run on dedicated queues
# so they don't starve lightweight default tasks (audit logs, emails, etc.).
# Workers are started per queue:
#   celery -A password_manager worker -Q default -c 4
#   celery -A password_manager worker -Q ml -c 2
#   celery -A password_manager worker -Q blockchain -c 1
CELERY_TASK_ROUTES = {
    # ML inference tasks → dedicated ml queue
    'ml_security.tasks.*': {'queue': 'ml'},
    'ml_dark_web.tasks.*': {'queue': 'ml'},
    'adversarial_ai.tasks.*': {'queue': 'ml'},
    'ai_assistant.tasks.*': {'queue': 'ml'},
    'biometric_liveness.tasks.*': {'queue': 'ml'},
    'cognitive_auth.tasks.*': {'queue': 'ml'},
    # Blockchain tasks → single-concurrency queue
    'blockchain.tasks.*': {'queue': 'blockchain'},
    'smart_contracts.tasks.*': {'queue': 'blockchain'},
}
CELERY_TASK_DEFAULT_QUEUE = 'default'

# NOTE: Celery Beat Schedule is defined in celery.py — do NOT import celery here.
# Settings should not import application code (breaks clean installs).

# ==============================================================================
# FHE Homomorphic Password Sharing Configuration
# ==============================================================================
FHE_SHARING_SETTINGS = {
    'DEFAULT_EXPIRY_HOURS': 72,         # Default share expiration (3 days)
    'MAX_EXPIRY_DAYS': 90,              # Maximum share lifetime
    'MAX_USES_DEFAULT': None,           # Unlimited uses by default
    'MAX_USES_LIMIT': 10000,            # Hard limit on max_uses
    'DOMAIN_BINDING_REQUIRED': True,    # Require domain binding for shares
    'AUDIT_RETENTION_DAYS': 365,        # Keep audit logs for 1 year
    'CLEANUP_INTERVAL_HOURS': 6,        # Cleanup expired shares every 6 hours
}

# ==============================================================================
# EPIGENETIC PASSWORD ADAPTATION CONFIGURATION
# ==============================================================================

ADAPTIVE_PASSWORD = {
    # Feature Flag
    'ENABLED': os.environ.get('ADAPTIVE_PASSWORD_ENABLED', 'True').lower() == 'true',
    
    # Privacy Settings
    'DEFAULT_OPT_IN': False,  # Opt-in by default (GDPR compliant)
    'DIFFERENTIAL_PRIVACY_EPSILON': float(os.environ.get('DP_EPSILON', '0.5')),
    
    # Suggestion Settings
    'SUGGESTION_FREQUENCY_DAYS': int(os.environ.get('ADAPTATION_FREQUENCY_DAYS', '30')),
    'MIN_SESSIONS_FOR_SUGGESTION': 10,
    'AUTO_APPLY_THRESHOLD': 0.9,  # Confidence threshold for auto-apply
    
    # Rollback Settings
    'MAX_ROLLBACK_DEPTH': 10,  # Maximum number of rollback versions
    'ADAPTATION_EXPIRY_DAYS': 7,  # Days before pending adaptations expire
    
    # ML Training Settings
    'ALLOW_CENTRALIZED_TRAINING': True,
    'ALLOW_FEDERATED_LEARNING': False,
    'RL_MODEL_UPDATE_INTERVAL_DAYS': 7,
    
    # Performance Settings
    'ASYNC_SUGGESTION_GENERATION': True,  # Use Celery for suggestions
    'MAX_ERROR_POSITIONS_STORED': 10,  # Limit for privacy
    'TIMING_BUCKET_COUNT': 9,  # Number of timing buckets
}

# ==============================================================================
# QUANTUM ENTANGLEMENT-INSPIRED KEY DISTRIBUTION CONFIGURATION
# ==============================================================================

QUANTUM_ENTANGLEMENT = {
    # Feature Flag
    'ENABLED': os.environ.get('ENTANGLEMENT_ENABLED', 'True').lower() == 'true',
    
    # Lattice Cryptography
    'LATTICE_ALGORITHM': os.environ.get('LATTICE_ALGO', 'kyber-1024'),
    
    # Randomness Pool
    'POOL_SIZE_BYTES': int(os.environ.get('ENTANGLE_POOL_SIZE', '4096')),
    
    # Entropy Thresholds
    'ENTROPY_THRESHOLD': float(os.environ.get('ENTROPY_THRESHOLD', '7.5')),
    'ENTROPY_CRITICAL': float(os.environ.get('ENTROPY_CRITICAL', '7.0')),
    
    # Synchronization
    'SYNC_INTERVAL_SECONDS': int(os.environ.get('ENTANGLE_SYNC_INTERVAL', '300')),
    
    # Limits
    'MAX_PAIRS_PER_USER': int(os.environ.get('MAX_ENTANGLED_PAIRS', '5')),
    
    # Security
    'AUTO_REVOKE_ON_ANOMALY': os.environ.get('AUTO_REVOKE_ANOMALY', 'True').lower() == 'true',
    'PAIRING_TIMEOUT_MINUTES': int(os.environ.get('PAIRING_TIMEOUT', '10')),
    
    # KL Divergence Thresholds
    'KL_DIVERGENCE_WARNING': float(os.environ.get('KL_WARNING', '0.1')),
    'KL_DIVERGENCE_CRITICAL': float(os.environ.get('KL_CRITICAL', '0.5')),
}

# ==============================================================================
# GEOFENCING & IMPOSSIBLE TRAVEL DETECTION CONFIGURATION
# ==============================================================================

GEOFENCE_SETTINGS = {
    # Feature Flags
    'ENABLED': os.environ.get('GEOFENCE_ENABLED', 'True').lower() == 'true',
    'IMPOSSIBLE_TRAVEL_ENABLED': os.environ.get('IMPOSSIBLE_TRAVEL_ENABLED', 'True').lower() == 'true',
    'AIRLINE_VERIFICATION_ENABLED': os.environ.get('AIRLINE_VERIFICATION_ENABLED', 'True').lower() == 'true',
    'CLONED_SESSION_DETECTION': os.environ.get('CLONED_SESSION_DETECTION_ENABLED', 'True').lower() == 'true',
    
    # Speed Thresholds (km/h) - Used for travel mode inference
    'SPEED_WALKING': float(os.environ.get('TRAVEL_SPEED_WALKING', '6')),
    'SPEED_CYCLING': float(os.environ.get('TRAVEL_SPEED_CYCLING', '40')),
    'SPEED_DRIVING': float(os.environ.get('TRAVEL_SPEED_DRIVING', '200')),
    'SPEED_HIGH_SPEED_RAIL': float(os.environ.get('TRAVEL_SPEED_RAIL', '400')),
    'SPEED_COMMERCIAL_FLIGHT': float(os.environ.get('TRAVEL_SPEED_FLIGHT', '920')),
    'SPEED_SUPERSONIC_THRESHOLD': float(os.environ.get('TRAVEL_SPEED_SUPERSONIC', '1200')),
    
    # Action Thresholds
    'CHALLENGE_SPEED_THRESHOLD': float(os.environ.get('CHALLENGE_SPEED_THRESHOLD', '500')),  # Require MFA
    'BLOCK_SPEED_THRESHOLD': float(os.environ.get('BLOCK_SPEED_THRESHOLD', '1200')),  # Block access
    
    # Time Thresholds
    'MIN_TIME_BETWEEN_LOCATIONS_SECONDS': int(os.environ.get('MIN_LOCATION_GAP', '60')),  # 1 minute
    'CLONED_SESSION_MAX_TIME_DIFF_SECONDS': int(os.environ.get('CLONED_SESSION_TIME', '300')),  # 5 minutes
    
    # Data Retention (days)
    'LOCATION_HISTORY_RETENTION_DAYS': int(os.environ.get('LOCATION_HISTORY_RETENTION_DAYS', '90')),
    'TRAVEL_EVENT_RETENTION_DAYS': int(os.environ.get('TRAVEL_EVENT_RETENTION_DAYS', '365')),
    
    # Geofence Zone Limits
    'MAX_ZONES_PER_USER': int(os.environ.get('MAX_GEOFENCE_ZONES', '10')),
    'DEFAULT_ZONE_RADIUS_METERS': int(os.environ.get('DEFAULT_ZONE_RADIUS', '500')),
    'MIN_ZONE_RADIUS_METERS': 50,
    'MAX_ZONE_RADIUS_METERS': 10000,
    
    # NTP Time Synchronization
    'NTP_SERVER': os.environ.get('NTP_SERVER', 'pool.ntp.org'),
    'NTP_TIMEOUT_SECONDS': int(os.environ.get('NTP_TIMEOUT', '5')),
    'USE_NTP_VERIFICATION': os.environ.get('USE_NTP_VERIFICATION', 'True').lower() == 'true',
}

# Amadeus API Configuration (Primary Airline Verification Provider)
AMADEUS_API_KEY = os.environ.get('AMADEUS_API_KEY', '')
AMADEUS_API_SECRET = os.environ.get('AMADEUS_API_SECRET', '')
AMADEUS_ENVIRONMENT = os.environ.get('AMADEUS_ENVIRONMENT', 'test')  # 'test' or 'production'

# Sabre API Configuration (Fallback Provider)
SABRE_API_KEY = os.environ.get('SABRE_API_KEY', '')
SABRE_API_SECRET = os.environ.get('SABRE_API_SECRET', '')
SABRE_REST_URL = os.environ.get('SABRE_REST_URL', 'https://api.cert.sabre.com')


# =============================================================================
# 🌊 Ocean Wave Entropy Configuration
# =============================================================================
# Configuration for ocean wave entropy harvesting from NOAA buoys.
# Ocean data provides chaotic, unpredictable entropy for password generation.

OCEAN_ENTROPY = {
    # Feature Toggle
    'ENABLED': os.environ.get('OCEAN_ENTROPY_ENABLED', 'True').lower() == 'true',
    
    # NOAA API Settings
    'TIMEOUT': int(os.environ.get('NOAA_API_TIMEOUT', '10')),  # seconds
    'MAX_RETRIES': int(os.environ.get('NOAA_MAX_RETRIES', '3')),
    
    # Caching Configuration
    'CACHE_TTL': int(os.environ.get('OCEAN_ENTROPY_CACHE_TTL', '300')),  # 5 minutes
    'USE_REDIS': os.environ.get('OCEAN_ENTROPY_USE_REDIS', 'False').lower() == 'true',
    'REDIS_KEY_PREFIX': 'ocean_entropy:',
    
    # Buoy Selection
    'BUOY_ROTATION_HOURS': int(os.environ.get('OCEAN_BUOY_ROTATION_HOURS', '4')),
    'MAX_BUOYS_PER_REQUEST': int(os.environ.get('OCEAN_MAX_BUOYS', '5')),
    'PREFERRED_BUOYS': os.environ.get('PREFERRED_BUOYS', '44013,41010,46050,42001').split(','),
    
    # Quality Thresholds
    'MIN_QUALITY_SCORE': float(os.environ.get('OCEAN_MIN_QUALITY_SCORE', '0.3')),
    'MIN_ENTROPY_BITS_PER_BYTE': float(os.environ.get('OCEAN_MIN_ENTROPY_BITS', '4.0')),
    'MAX_DATA_AGE_MINUTES': int(os.environ.get('OCEAN_MAX_DATA_AGE_MINUTES', '60')),
    
    # Security Requirements
    'REQUIRE_TWO_SOURCES': os.environ.get('OCEAN_REQUIRE_TWO_SOURCES', 'True').lower() == 'true',
    
    # Pool Contribution
    'POOL_CONTRIBUTION_PERCENT': int(os.environ.get('OCEAN_POOL_CONTRIBUTION_PERCENT', '25')),
    
    # Rate Limiting (to respect NOAA servers)
    'MAX_REQUESTS_PER_HOUR_PER_BUOY': int(os.environ.get('OCEAN_MAX_REQUESTS_PER_HOUR', '60')),
}


# =============================================================================
# 🍯 Honeypot Email Breach Detection Configuration
# =============================================================================
# Configuration for honeypot email aliases used to detect data breaches.
# When a honeypot receives spam, it indicates the associated service was breached.

HONEYPOT_EMAIL = {
    # Feature Toggle
    'ENABLED': os.environ.get('HONEYPOT_ENABLED', 'True').lower() == 'true',
    
    # Default Email Provider (simplelogin, anonaddy, or custom)
    'DEFAULT_PROVIDER': os.environ.get('HONEYPOT_DEFAULT_PROVIDER', 'simplelogin'),
    
    # SimpleLogin Configuration (https://simplelogin.io)
    'SIMPLELOGIN_API_KEY': os.environ.get('SIMPLELOGIN_API_KEY', ''),
    'SIMPLELOGIN_BASE_URL': os.environ.get('SIMPLELOGIN_BASE_URL', 'https://app.simplelogin.io/api'),
    
    # AnonAddy Configuration (https://anonaddy.com)
    'ANONADDY_API_KEY': os.environ.get('ANONADDY_API_KEY', ''),
    'ANONADDY_BASE_URL': os.environ.get('ANONADDY_BASE_URL', 'https://app.anonaddy.com/api/v1'),
    'ANONADDY_DOMAIN': os.environ.get('ANONADDY_DOMAIN', 'anonaddy.me'),
    
    # Custom SMTP Configuration (for enterprise deployments)
    'CUSTOM_SMTP_DOMAIN': os.environ.get('HONEYPOT_SMTP_DOMAIN', ''),
    'CUSTOM_SMTP_HOST': os.environ.get('HONEYPOT_SMTP_HOST', ''),
    'CUSTOM_SMTP_PORT': int(os.environ.get('HONEYPOT_SMTP_PORT', '587')),
    'CUSTOM_SMTP_USERNAME': os.environ.get('HONEYPOT_SMTP_USERNAME', ''),
    'CUSTOM_SMTP_PASSWORD': os.environ.get('HONEYPOT_SMTP_PASSWORD', ''),
    
    # Webhook Configuration
    'WEBHOOK_SECRET': os.environ.get('HONEYPOT_WEBHOOK_SECRET', ''),
    'WEBHOOK_SIGNATURE_HEADER': os.environ.get('HONEYPOT_WEBHOOK_SIG_HEADER', 'X-SimpleLogin-Signature'),
    
    # Breach Detection Thresholds
    'SPAM_THRESHOLD_FOR_BREACH': int(os.environ.get('HONEYPOT_SPAM_THRESHOLD', '1')),
    'ACTIVITY_SPIKE_THRESHOLD': int(os.environ.get('HONEYPOT_ACTIVITY_SPIKE', '3')),
    'HIGH_CONFIDENCE_THRESHOLD': float(os.environ.get('HONEYPOT_HIGH_CONFIDENCE', '0.8')),
    
    # User Limits
    'DEFAULT_MAX_HONEYPOTS': int(os.environ.get('HONEYPOT_DEFAULT_MAX', '50')),
    'PREMIUM_MAX_HONEYPOTS': int(os.environ.get('HONEYPOT_PREMIUM_MAX', '200')),
    
    # Notification Settings
    'SECURITY_EMAIL': os.environ.get('SECURITY_EMAIL', 'security@securevault.com'),
    'NOTIFY_ADMINS_ON_BREACH': os.environ.get('HONEYPOT_NOTIFY_ADMINS', 'True').lower() == 'true',
    
    # Data Retention (days)
    'ACTIVITY_RETENTION_DAYS': int(os.environ.get('HONEYPOT_ACTIVITY_RETENTION', '365')),
    'BREACH_RETENTION_DAYS': int(os.environ.get('HONEYPOT_BREACH_RETENTION', '730')),  # 2 years
    
    # Auto-Rotation Settings
    'DEFAULT_AUTO_ROTATE': os.environ.get('HONEYPOT_DEFAULT_AUTO_ROTATE', 'False').lower() == 'true',
    'DEFAULT_REQUIRE_CONFIRMATION': os.environ.get('HONEYPOT_REQUIRE_CONFIRM', 'True').lower() == 'true',
}

# Security email for breach notifications
SECURITY_EMAIL = os.environ.get('SECURITY_EMAIL', 'security@securevault.com')

# =============================================================================
# 🌑 Dark Protocol Network Configuration
# =============================================================================
# Anonymous vault access using garlic routing and cover traffic
# Provides government-level censorship resistance

DARK_PROTOCOL = {
    # Feature toggle
    'ENABLED': os.environ.get('DARK_PROTOCOL_ENABLED', 'True').lower() == 'true',
    
    # Network settings
    'DEFAULT_HOP_COUNT': int(os.environ.get('DARK_PROTOCOL_DEFAULT_HOPS', '3')),
    'MAX_HOP_COUNT': int(os.environ.get('DARK_PROTOCOL_MAX_HOPS', '7')),
    'MIN_NODE_TRUST_SCORE': float(os.environ.get('DARK_PROTOCOL_MIN_TRUST', '0.3')),
    
    # Session settings
    'SESSION_TIMEOUT_MINUTES': int(os.environ.get('DARK_PROTOCOL_SESSION_TIMEOUT', '30')),
    'PATH_ROTATION_MINUTES': int(os.environ.get('DARK_PROTOCOL_PATH_ROTATION', '5')),
    
    # Cover traffic
    'COVER_TRAFFIC_ENABLED': os.environ.get('DARK_PROTOCOL_COVER_TRAFFIC', 'True').lower() == 'true',
    'COVER_TRAFFIC_RATE': float(os.environ.get('DARK_PROTOCOL_COVER_RATE', '0.5')),
    'COVER_TRAFFIC_INTERVAL_SECONDS': int(os.environ.get('DARK_PROTOCOL_COVER_INTERVAL', '5')),
    
    # Bridge nodes (for censorship circumvention)
    'USE_BRIDGE_NODES': os.environ.get('DARK_PROTOCOL_USE_BRIDGES', 'False').lower() == 'true',
    'BRIDGE_DISCOVERY_URL': os.environ.get('DARK_PROTOCOL_BRIDGE_DISCOVERY', ''),
    
    # Encryption
    'ENCRYPTION_ALGORITHM': os.environ.get('DARK_PROTOCOL_ENCRYPTION', 'kyber-1024'),
    'USE_LATTICE_CRYPTO': os.environ.get('DARK_PROTOCOL_USE_LATTICE', 'True').lower() == 'true',
    
    # Noise and padding
    'MIN_PADDING_BYTES': int(os.environ.get('DARK_PROTOCOL_MIN_PADDING', '32')),
    'MAX_PADDING_BYTES': int(os.environ.get('DARK_PROTOCOL_MAX_PADDING', '2048')),
    
    # Timing
    'MIN_JITTER_MS': int(os.environ.get('DARK_PROTOCOL_MIN_JITTER', '10')),
    'MAX_JITTER_MS': int(os.environ.get('DARK_PROTOCOL_MAX_JITTER', '500')),
    
    # Health checks
    'HEALTH_CHECK_INTERVAL_SECONDS': int(os.environ.get('DARK_PROTOCOL_HEALTH_INTERVAL', '60')),
    'NODE_TIMEOUT_MS': int(os.environ.get('DARK_PROTOCOL_NODE_TIMEOUT', '5000')),
    
    # Data retention
    'SESSION_RETENTION_HOURS': int(os.environ.get('DARK_PROTOCOL_SESSION_RETENTION', '24')),
    'TRAFFIC_BUNDLE_RETENTION_HOURS': int(os.environ.get('DARK_PROTOCOL_BUNDLE_RETENTION', '24')),
    'HEALTH_RECORD_RETENTION_DAYS': int(os.environ.get('DARK_PROTOCOL_HEALTH_RETENTION', '7')),
}

# =============================================================================
# 🔮 Predictive Intent Analysis Configuration
# =============================================================================
# AI-powered password prediction - learns browsing patterns and pre-loads
# passwords before users request them

PREDICTIVE_INTENT = {
    # Feature toggle
    'ENABLED': os.environ.get('PREDICTIVE_INTENT_ENABLED', 'True').lower() == 'true',
    
    # Confidence thresholds
    'MIN_CONFIDENCE': float(os.environ.get('PREDICTIVE_MIN_CONFIDENCE', '0.7')),
    'PRELOAD_CONFIDENCE': float(os.environ.get('PREDICTIVE_PRELOAD_CONFIDENCE', '0.85')),
    
    # Prediction limits
    'MAX_PREDICTIONS': int(os.environ.get('PREDICTIVE_MAX_PREDICTIONS', '5')),
    'PRELOAD_COUNT': int(os.environ.get('PREDICTIVE_PRELOAD_COUNT', '3')),
    
    # Pattern learning
    'PATTERN_HISTORY_DAYS': int(os.environ.get('PREDICTIVE_HISTORY_DAYS', '90')),
    'LEARN_FROM_VAULT_ACCESS': os.environ.get('PREDICTIVE_LEARN_VAULT', 'True').lower() == 'true',
    'LEARN_FROM_AUTOFILL': os.environ.get('PREDICTIVE_LEARN_AUTOFILL', 'True').lower() == 'true',
    
    # Caching
    'PRELOAD_EXPIRY_MINUTES': int(os.environ.get('PREDICTIVE_PRELOAD_EXPIRY', '15')),
    'PREDICTION_EXPIRY_MINUTES': int(os.environ.get('PREDICTIVE_PREDICTION_EXPIRY', '15')),
    
    # Model settings
    'MODEL_VERSION': os.environ.get('PREDICTIVE_MODEL_VERSION', '1.0'),
    'RETRAIN_INTERVAL_HOURS': int(os.environ.get('PREDICTIVE_RETRAIN_INTERVAL', '24')),
    
    # Privacy
    'HASH_SENSITIVE_DATA': os.environ.get('PREDICTIVE_HASH_DATA', 'True').lower() == 'true',
    'EXCLUDE_FINANCIAL_DOMAINS': os.environ.get('PREDICTIVE_EXCLUDE_FINANCIAL', 'False').lower() == 'true',
}

# =============================================================================
# 🧠 Neuro-Feedback Password Training Configuration
# =============================================================================
# EEG-based password memory training with real-time neurofeedback

NEURO_FEEDBACK = {
    # Feature toggle
    'ENABLED': os.environ.get('NEURO_FEEDBACK_ENABLED', 'False').lower() == 'true',
    
    # Supported EEG devices
    'SUPPORTED_DEVICES': ['muse', 'muse_2', 'muse_s', 'neurosky', 'openbci', 'emotiv'],
    
    # Signal quality thresholds
    'MIN_SIGNAL_QUALITY': float(os.environ.get('NEURO_MIN_SIGNAL_QUALITY', '0.7')),  # 0-1
    
    # Session settings
    'SESSION_TIMEOUT_MINUTES': int(os.environ.get('NEURO_SESSION_TIMEOUT', '30')),
    'OPTIMAL_TRAINING_DURATION': int(os.environ.get('NEURO_OPTIMAL_DURATION', '15')),  # Minutes
    
    # Brain state thresholds
    'ALPHA_THRESHOLD': float(os.environ.get('NEURO_ALPHA_THRESHOLD', '0.6')),  # Memory-ready state
    'FOCUS_THRESHOLD': float(os.environ.get('NEURO_FOCUS_THRESHOLD', '0.5')),
    'MEMORY_READINESS_THRESHOLD': float(os.environ.get('NEURO_MEMORY_THRESHOLD', '0.6')),
    
    # Spaced repetition settings (SM-2 algorithm)
    'SPACED_REP_MULTIPLIER': float(os.environ.get('NEURO_SR_MULTIPLIER', '2.5')),
    'INITIAL_INTERVAL_HOURS': int(os.environ.get('NEURO_INITIAL_INTERVAL', '24')),
    'MASTERY_THRESHOLD': float(os.environ.get('NEURO_MASTERY_THRESHOLD', '0.9')),
    
    # Password chunking
    'MAX_PASSWORD_LENGTH': int(os.environ.get('NEURO_MAX_PASSWORD', '128')),
    'CHUNK_SIZE': int(os.environ.get('NEURO_CHUNK_SIZE', '8')),  # Characters per chunk
    
    # Feedback settings
    'BINAURAL_BEATS_ENABLED': os.environ.get('NEURO_BINAURAL_ENABLED', 'True').lower() == 'true',
    'HAPTIC_FEEDBACK_ENABLED': os.environ.get('NEURO_HAPTIC_ENABLED', 'True').lower() == 'true',
    
    # Data retention
    'SESSION_DATA_RETENTION_DAYS': int(os.environ.get('NEURO_SESSION_RETENTION', '90')),
    'EVENT_DATA_RETENTION_DAYS': int(os.environ.get('NEURO_EVENT_RETENTION', '30')),
}

# =============================================================================
# 🧪 Cognitive Password Testing with Implicit Memory
# =============================================================================
# Distinguishes password creators from attackers via reaction time patterns

COGNITIVE_AUTH = {
    # Feature toggle
    'ENABLED': os.environ.get('COGNITIVE_AUTH_ENABLED', 'False').lower() == 'true',
    
    # Challenge types to include in verification sessions
    'CHALLENGE_TYPES': ['scrambled', 'stroop', 'priming', 'partial'],
    
    # Session settings
    'MIN_CHALLENGES': int(os.environ.get('COGNITIVE_MIN_CHALLENGES', '5')),
    'MAX_CHALLENGES': int(os.environ.get('COGNITIVE_MAX_CHALLENGES', '10')),
    'BASELINE_CALIBRATION_CHALLENGES': int(os.environ.get('COGNITIVE_CALIBRATION_CHALLENGES', '15')),
    
    # Timing thresholds (milliseconds)
    'REACTION_TIME_THRESHOLD_MS': int(os.environ.get('COGNITIVE_REACTION_THRESHOLD', '2000')),
    'CREATOR_ADVANTAGE_FACTOR': float(os.environ.get('COGNITIVE_CREATOR_ADVANTAGE', '0.3')),  # 30% faster
    
    # ML/Analysis settings
    'ML_CONFIDENCE_THRESHOLD': float(os.environ.get('COGNITIVE_ML_THRESHOLD', '0.65')),
    'ANOMALY_Z_THRESHOLD': float(os.environ.get('COGNITIVE_ANOMALY_Z', '2.5')),
    'MIN_SAMPLES': int(os.environ.get('COGNITIVE_MIN_SAMPLES', '5')),
    
    # Verification triggers
    'VERIFY_ON_LOGIN': os.environ.get('COGNITIVE_VERIFY_LOGIN', 'False').lower() == 'true',
    'VERIFY_ON_SENSITIVE_ACTIONS': os.environ.get('COGNITIVE_VERIFY_SENSITIVE', 'True').lower() == 'true',
    'PERIODIC_VERIFICATION_DAYS': int(os.environ.get('COGNITIVE_PERIODIC_DAYS', '30')),
    
    # Session expiry (minutes)
    'SESSION_EXPIRY_MINUTES': int(os.environ.get('COGNITIVE_SESSION_EXPIRY', '10')),
    
    # Data retention
    'SESSION_DATA_RETENTION_DAYS': int(os.environ.get('COGNITIVE_SESSION_RETENTION', '90')),
}

# =============================================================================
# 🎭 Deepfake-Resistant Biometric Liveness
# =============================================================================
# Advanced anti-spoofing that defeats deepfakes using micro-expressions,
# gaze tracking, pulse oximetry, and thermal imaging

BIOMETRIC_LIVENESS = {
    # Feature toggle
    'ENABLED': os.environ.get('BIOMETRIC_LIVENESS_ENABLED', 'False').lower() == 'true',
    
    # Detection thresholds
    'LIVENESS_THRESHOLD': float(os.environ.get('LIVENESS_THRESHOLD', '0.85')),
    'DEEPFAKE_THRESHOLD': float(os.environ.get('DEEPFAKE_THRESHOLD', '0.70')),
    'PULSE_CONFIDENCE_MIN': float(os.environ.get('PULSE_CONFIDENCE_MIN', '0.75')),
    
    # Cognitive tasks
    'COGNITIVE_TASK_TIMEOUT_MS': int(os.environ.get('LIVENESS_TASK_TIMEOUT', '5000')),
    'GAZE_TRACKING_POINTS': int(os.environ.get('LIVENESS_GAZE_POINTS', '9')),
    
    # Session settings
    'SESSION_TIMEOUT_SECONDS': int(os.environ.get('LIVENESS_SESSION_TIMEOUT', '120')),
    'REQUIRED_CHALLENGES': ['gaze', 'expression', 'pulse'],
    
    # Thermal settings
    'THERMAL_ENABLED': os.environ.get('LIVENESS_THERMAL_ENABLED', 'False').lower() == 'true',
    'THERMAL_MIN_TEMP_C': float(os.environ.get('LIVENESS_THERMAL_MIN', '35.0')),
    'THERMAL_MAX_TEMP_C': float(os.environ.get('LIVENESS_THERMAL_MAX', '38.0')),
}

# =============================================================================
# 🔮 Predictive Password Expiration Based on Threat Intelligence
# =============================================================================
# AI that predicts when passwords might be compromised using pattern analysis,
# dark web monitoring, and threat actor TTPs for proactive rotation

PREDICTIVE_EXPIRATION = {
    # Feature toggle
    'ENABLED': os.environ.get('PREDICTIVE_EXPIRATION_ENABLED', 'True').lower() == 'true',
    
    # Risk thresholds
    'RISK_THRESHOLD_HIGH': float(os.environ.get('PREDICTIVE_RISK_THRESHOLD_HIGH', '0.7')),
    'RISK_THRESHOLD_MEDIUM': float(os.environ.get('PREDICTIVE_RISK_THRESHOLD_MEDIUM', '0.4')),
    
    # Scanning settings
    'SCAN_INTERVAL_HOURS': int(os.environ.get('PREDICTIVE_SCAN_INTERVAL', '24')),
    'DAILY_SCAN_ENABLED': os.environ.get('PREDICTIVE_DAILY_SCAN', 'True').lower() == 'true',
    
    # Threat feed sources
    'THREAT_FEED_SOURCES': [
        'internal_dark_web',      # ml_dark_web integration
        'misp',                   # MISP threat intel platform
        'alienvault_otx',         # AlienVault OTX
    ],
    
    # Pattern analysis
    'PATTERN_SIMILARITY_THRESHOLD': float(os.environ.get('PREDICTIVE_PATTERN_THRESHOLD', '0.85')),
    'MAX_CREDENTIAL_AGE_DAYS': int(os.environ.get('PREDICTIVE_MAX_AGE_DAYS', '90')),
    
    # Threat correlation
    'INDUSTRY_THREAT_WEIGHT': float(os.environ.get('PREDICTIVE_INDUSTRY_WEIGHT', '0.3')),
    'TTP_WEIGHT': float(os.environ.get('PREDICTIVE_TTP_WEIGHT', '0.4')),
    'PATTERN_WEIGHT': float(os.environ.get('PREDICTIVE_PATTERN_WEIGHT', '0.3')),
    
    # Notification settings
    'NOTIFICATION_ENABLED': os.environ.get('PREDICTIVE_NOTIFICATIONS', 'True').lower() == 'true',
    'MAX_NOTIFICATIONS_PER_DAY': int(os.environ.get('PREDICTIVE_MAX_NOTIFICATIONS', '3')),
    
    # Auto-rotation settings
    'AUTO_ROTATION_ENABLED': os.environ.get('PREDICTIVE_AUTO_ROTATE', 'False').lower() == 'true',
    'FORCE_ROTATION_THRESHOLD': float(os.environ.get('PREDICTIVE_FORCE_ROTATE_THRESHOLD', '0.9')),
    
    # ML model settings
    'ML_MODEL_PATH': os.environ.get('PREDICTIVE_ML_MODEL_PATH', 'models/pattern_classifier.pkl'),
    'ML_CONFIDENCE_THRESHOLD': float(os.environ.get('PREDICTIVE_ML_CONFIDENCE', '0.75')),
}

# =============================================================================
# Cosmic Ray Entropy Configuration
# =============================================================================
# Settings for cosmic ray-based true random number generation.
# Uses USB cosmic ray detectors (e.g., CosmicWatch) or simulation fallback.

COSMIC_RAY_ENTROPY = {
    # Master enable/disable for cosmic ray entropy
    'ENABLED': os.environ.get('COSMIC_RAY_ENABLED', 'True').lower() == 'true',
    
    # Serial port configuration
    # 'auto' = auto-detect CosmicWatch devices
    'SERIAL_PORT': os.environ.get('COSMIC_RAY_SERIAL_PORT', 'auto'),
    'BAUD_RATE': int(os.environ.get('COSMIC_RAY_BAUD_RATE', '9600')),
    
    # Event buffer settings
    'EVENT_BUFFER_SIZE': int(os.environ.get('COSMIC_RAY_BUFFER_SIZE', '100')),
    'MIN_EVENTS_FOR_ENTROPY': int(os.environ.get('COSMIC_RAY_MIN_EVENTS', '10')),
    
    # Simulation fallback (when no hardware detected)
    'SIMULATION_FALLBACK': os.environ.get('COSMIC_RAY_SIMULATION', 'True').lower() == 'true',
    
    # Pool contribution when mixing with other entropy sources
    'POOL_CONTRIBUTION_PERCENT': int(os.environ.get('COSMIC_RAY_POOL_PERCENT', '20')),
    
    # Continuous background collection (requires user opt-in)
    # If False, events are collected on-demand only
    'CONTINUOUS_COLLECTION': os.environ.get('COSMIC_RAY_CONTINUOUS', 'False').lower() == 'true',
}

# ==============================================================================
# AI-POWERED SECURITY ASSISTANT (Claude API)
# ==============================================================================
# Conversational AI assistant for password security queries and recommendations.
# Powered by Anthropic's Claude API.

AI_ASSISTANT_ENABLED = os.environ.get('AI_ASSISTANT_ENABLED', 'True').lower() == 'true'
ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY', '')
AI_ASSISTANT_MODEL = os.environ.get('AI_ASSISTANT_MODEL', 'claude-sonnet-4-6')
AI_ASSISTANT_MAX_TOKENS = int(os.environ.get('AI_ASSISTANT_MAX_TOKENS', '4096'))
AI_ASSISTANT_RATE_LIMIT = os.environ.get('AI_ASSISTANT_RATE_LIMIT', '20/hour')

# =============================================================================
# Test-environment overrides
# =============================================================================
TESTING = 'test' in sys.argv or 'pytest' in sys.modules

if TESTING:
    REST_FRAMEWORK['DEFAULT_THROTTLE_CLASSES'] = []

    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'test-default',
        },
        'rate_limiting': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'test-ratelimit',
        },
    }

    CHANNEL_LAYERS = {
        'default': {'BACKEND': 'channels.layers.InMemoryChannelLayer'}
    }
