# Generated by Django 5.1.15 on 2026-06-25 05:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfTestRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled')], default='manual', max_length=16)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=16)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_bounty_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bug_bounty_self_test_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_id', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='info', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('false_positive', 'False positive')], default='open', max_length=16)),
                ('remediation', models.TextField(blank=True, default='')),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('fingerprint', models.CharField(help_text='Stable identity of the logical issue, for dedup across runs.', max_length=128)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_bounty_findings', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(blank=True, help_text='The most recent run that re-surfaced this finding.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='bug_bounty.selftestrun')),
            ],
            options={
                'db_table': 'bug_bounty_findings',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.AddIndex(
            model_name='selftestrun',
            index=models.Index(fields=['user', '-started_at'], name='bug_bounty__user_id_5bae9c_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['user', 'status', 'severity'], name='bug_bounty__user_id_ab0a22_idx'),
        ),
        migrations.AddConstraint(
            model_name='finding',
            constraint=models.UniqueConstraint(fields=('user', 'check_id', 'fingerprint'), name='uniq_finding_user_check_fingerprint'),
        ),
    ]
