# Generated by Django 5.1.15 on 2026-06-25 11:19

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_bounty', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BountyProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('scope', models.JSONField(blank=True, default=list)),
                ('policy', models.TextField(blank=True, default='')),
                ('reward_tiers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_bounty_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bug_bounty_programs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity_claimed', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('severity_assigned', models.CharField(blank=True, choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='', max_length=16)),
                ('status', models.CharField(choices=[('new', 'New'), ('triaging', 'Triaging'), ('accepted', 'Accepted'), ('duplicate', 'Duplicate'), ('rejected', 'Rejected'), ('resolved', 'Resolved'), ('rewarded', 'Rewarded')], db_index=True, default='new', max_length=16)),
                ('triage_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='bug_bounty.bountyprogram')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_bounty_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bug_bounty_submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('owed', 'Owed'), ('paid', 'Paid'), ('void', 'Void')], default='owed', max_length=16)),
                ('adapter', models.CharField(default='manual', max_length=64)),
                ('payout_ref', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward', to='bug_bounty.submission')),
            ],
            options={
                'db_table': 'bug_bounty_rewards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bountyprogram',
            index=models.Index(fields=['owner', 'status'], name='bug_bounty__owner_i_c675ea_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['program', 'status'], name='bug_bounty__program_acd32e_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['researcher', 'status'], name='bug_bounty__researc_f4bb57_idx'),
        ),
    ]
