# Generated by Django 5.1.15 on 2026-06-25 16:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_bounty', '0002_bountyprogram_submission_reward_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reward',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0.01'))), name='bug_bounty_reward_amount_positive'),
        ),
    ]
