# Generated by Django 5.1.15 on 2026-04-17 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot_credentials', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='honeypotaccessevent',
            new_name='honeypot_ac_honeypo_7855ff_idx',
            old_name='hp_event_hp_time_idx',
        ),
        migrations.RenameIndex(
            model_name='honeypotaccessevent',
            new_name='honeypot_ac_ip_65e8e9_idx',
            old_name='hp_event_ip_time_idx',
        ),
        migrations.RenameIndex(
            model_name='honeypotcredential',
            new_name='honeypot_cr_user_id_60aa3b_idx',
            old_name='hp_user_active_idx',
        ),
        migrations.RenameIndex(
            model_name='honeypotcredential',
            new_name='honeypot_cr_fake_si_b9e31a_idx',
            old_name='hp_fake_site_idx',
        ),
    ]
