# Generated by Django 4.2.27 on 2026-02-06 19:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vault', '0004_encryptedvaultitem_cached_breach_check_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrainwaveSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('error', 'Error')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('avg_alpha_power', models.FloatField(blank=True, null=True)),
                ('avg_theta_power', models.FloatField(blank=True, null=True)),
                ('avg_gamma_power', models.FloatField(blank=True, null=True)),
                ('avg_focus_index', models.FloatField(blank=True, null=True)),
                ('avg_signal_quality', models.FloatField(blank=True, null=True)),
                ('passwords_trained', models.IntegerField(default=0)),
                ('chunks_memorized', models.IntegerField(default=0)),
                ('optimal_state_time', models.IntegerField(default=0, help_text='Seconds spent in optimal memory encoding state')),
                ('raw_data_reference', models.CharField(blank=True, help_text='Reference to encrypted EEG data storage', max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='EEGDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_type', models.CharField(choices=[('muse', 'Muse Headband'), ('muse_2', 'Muse 2'), ('muse_s', 'Muse S'), ('neurosky', 'NeuroSky MindWave'), ('openbci', 'OpenBCI'), ('emotiv', 'Emotiv Insight'), ('other', 'Other Device')], max_length=20)),
                ('device_name', models.CharField(help_text='User-assigned device name', max_length=100)),
                ('device_id', models.CharField(help_text='Bluetooth/hardware ID', max_length=100)),
                ('status', models.CharField(choices=[('paired', 'Paired'), ('calibrating', 'Calibrating'), ('ready', 'Ready'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='disconnected', max_length=20)),
                ('calibration_data', models.JSONField(default=dict, help_text='Device-specific calibration parameters')),
                ('baseline_alpha', models.FloatField(blank=True, help_text="User's baseline alpha power (8-12 Hz)", null=True)),
                ('baseline_theta', models.FloatField(blank=True, help_text="User's baseline theta power (4-8 Hz)", null=True)),
                ('signal_quality_threshold', models.FloatField(default=0.7, help_text='Minimum acceptable signal quality', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('battery_level', models.IntegerField(blank=True, null=True)),
                ('last_connected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eeg_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_connected_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordTrainingProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paused', 'Paused'), ('abandoned', 'Abandoned')], default='not_started', max_length=20)),
                ('password_hash', models.CharField(help_text='SHA-256 for verification', max_length=64)),
                ('password_length', models.IntegerField()),
                ('chunk_count', models.IntegerField(help_text='Number of 8-char chunks')),
                ('current_chunk', models.IntegerField(default=0)),
                ('chunks_mastered', models.IntegerField(default=0)),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_practice_time', models.IntegerField(default=0, help_text='Seconds')),
                ('current_interval_days', models.FloatField(default=1.0)),
                ('easiness_factor', models.FloatField(default=2.5, help_text='SuperMemo-style easiness factor')),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('target_completion_days', models.IntegerField(default=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_programs', to=settings.AUTH_USER_MODEL)),
                ('vault_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_programs', to='vault.encryptedvaultitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NeuroFeedbackSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('auto_connect', models.BooleanField(default=True)),
                ('session_duration_minutes', models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)])),
                ('chunk_size', models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(16)])),
                ('daily_reminder', models.BooleanField(default=True)),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('feedback_mode', models.CharField(choices=[('visual', 'Visual Only'), ('audio', 'Audio Only'), ('haptic', 'Haptic Only'), ('combined', 'Combined')], default='combined', max_length=20)),
                ('audio_volume', models.IntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('haptic_intensity', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('alpha_threshold', models.FloatField(default=0.6, validators=[django.core.validators.MinValueValidator(0.3), django.core.validators.MaxValueValidator(0.9)])),
                ('binaural_beats_enabled', models.BooleanField(default=True)),
                ('binaural_frequency', models.FloatField(default=10.0, help_text='Target frequency for alpha enhancement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='neuro_feedback.eegdevice')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='neuro_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NeurofeedbackEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('alpha_peak', 'Alpha Peak Detected'), ('theta_burst', 'Theta Burst'), ('gamma_spike', 'Gamma Spike'), ('focus_achieved', 'Focus State Achieved'), ('memory_ready', 'Memory Encoding Ready'), ('distraction', 'Distraction Detected'), ('fatigue', 'Mental Fatigue'), ('success', 'Successful Recall'), ('struggle', 'Recall Difficulty')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('alpha_power', models.FloatField(blank=True, null=True)),
                ('theta_power', models.FloatField(blank=True, null=True)),
                ('gamma_power', models.FloatField(blank=True, null=True)),
                ('focus_index', models.FloatField(blank=True, null=True)),
                ('password_chunk_index', models.IntegerField(blank=True, null=True)),
                ('feedback_given', models.CharField(blank=True, max_length=50)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='neuro_feedback.brainwavesession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MemoryStrengthScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField(help_text='0-indexed chunk position')),
                ('chunk_hash', models.CharField(help_text='Hash of chunk content', max_length=64)),
                ('strength_score', models.FloatField(default=0.0, help_text='Current memory strength (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('peak_strength', models.FloatField(default=0.0)),
                ('decay_rate', models.FloatField(default=0.1, help_text='Forgetting curve decay rate')),
                ('successful_recalls', models.IntegerField(default=0)),
                ('failed_recalls', models.IntegerField(default=0)),
                ('avg_recall_time_ms', models.IntegerField(blank=True, null=True)),
                ('best_alpha_correlation', models.FloatField(blank=True, null=True)),
                ('encoding_quality', models.FloatField(blank=True, help_text='EEG-measured encoding quality', null=True)),
                ('first_exposure_at', models.DateTimeField(blank=True, null=True)),
                ('last_practiced_at', models.DateTimeField(blank=True, null=True)),
                ('mastered_at', models.DateTimeField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_scores', to='neuro_feedback.passwordtrainingprogram')),
            ],
            options={
                'ordering': ['chunk_index'],
            },
        ),
        migrations.AddField(
            model_name='brainwavesession',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='neuro_feedback.eegdevice'),
        ),
        migrations.AddField(
            model_name='brainwavesession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brainwave_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SpacedRepetitionSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('skipped', models.BooleanField(default=False)),
                ('interval_days', models.FloatField()),
                ('predicted_strength', models.FloatField(help_text='Predicted memory strength at review time')),
                ('optimal_difficulty', models.FloatField(help_text='Target difficulty for optimal learning')),
                ('recommended_time_of_day', models.CharField(blank=True, max_length=20)),
                ('brain_state_recommendations', models.JSONField(default=dict, help_text='Optimal brain state for this review')),
                ('actual_strength', models.FloatField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='neuro_feedback.passwordtrainingprogram')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='neuro_feedback.brainwavesession')),
            ],
            options={
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['program', 'scheduled_at'], name='neuro_feedb_program_c0f9ab_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='passwordtrainingprogram',
            index=models.Index(fields=['user', 'status'], name='neuro_feedb_user_id_a37123_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordtrainingprogram',
            index=models.Index(fields=['next_review_at'], name='neuro_feedb_next_re_e09459_idx'),
        ),
        migrations.AddIndex(
            model_name='neurofeedbackevent',
            index=models.Index(fields=['session', 'event_type'], name='neuro_feedb_session_761297_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='memorystrengthscore',
            unique_together={('program', 'chunk_index')},
        ),
        migrations.AlterUniqueTogether(
            name='eegdevice',
            unique_together={('user', 'device_id')},
        ),
        migrations.AddIndex(
            model_name='brainwavesession',
            index=models.Index(fields=['user', 'status'], name='neuro_feedb_user_id_821dac_idx'),
        ),
        migrations.AddIndex(
            model_name='brainwavesession',
            index=models.Index(fields=['started_at'], name='neuro_feedb_started_ef60bc_idx'),
        ),
    ]
