# Generated by Django 5.1.15 on 2026-04-17 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circadian_totp', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='circadiantotpdevice',
            new_name='circadian_t_user_id_67315c_idx',
            old_name='circadian_t_user_id_confirm_idx',
        ),
        migrations.RenameIndex(
            model_name='sleepobservation',
            new_name='circadian_t_user_id_e0c695_idx',
            old_name='circadian_t_user_id_sleepend_idx',
        ),
        migrations.RenameIndex(
            model_name='sleepobservation',
            new_name='circadian_t_user_id_b21d0c_idx',
            old_name='circadian_t_user_id_provider_idx',
        ),
    ]
