# Generated by Django 5.1.15 on 2026-04-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circadian_totp', '0002_rename_circadian_t_user_id_confirm_idx_circadian_t_user_id_67315c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='circadiantotpdevice',
            name='last_code_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
