# Generated by Django 4.2.16 on 2025-11-28 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funnel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('steps', models.JSONField(default=list)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Funnel',
                'verbose_name_plural': 'Funnels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CohortDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('criteria', models.JSONField(default=dict)),
                ('active', models.BooleanField(default=True)),
                ('user_count', models.IntegerField(default=0)),
                ('last_calculated', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cohort Definition',
                'verbose_name_plural': 'Cohort Definitions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('page_views', models.IntegerField(default=0)),
                ('event_count', models.IntegerField(default=0)),
                ('feature_usage', models.JSONField(blank=True, default=dict)),
                ('user_journey', models.JSONField(blank=True, default=list)),
                ('referrer', models.TextField(blank=True)),
                ('landing_page', models.CharField(blank=True, max_length=500)),
                ('exit_page', models.CharField(blank=True, max_length=500)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('screen_resolution', models.CharField(blank=True, max_length=50)),
                ('is_bounce', models.BooleanField(default=False)),
                ('is_engaged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['user', 'start_time'], name='analytics_u_user_id_4a09ce_idx'), models.Index(fields=['session_id'], name='analytics_u_session_1131bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserEngagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=200)),
                ('metric', models.CharField(db_index=True, max_length=100)),
                ('value', models.FloatField()),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Engagement',
                'verbose_name_plural': 'User Engagements',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'metric', 'timestamp'], name='analytics_u_user_id_24ca5c_idx'), models.Index(fields=['session_id', 'timestamp'], name='analytics_u_session_46cbeb_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=200)),
                ('metric_type', models.CharField(db_index=True, max_length=100)),
                ('metric_name', models.CharField(max_length=200)),
                ('value', models.FloatField()),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Performance Metric',
                'verbose_name_plural': 'Performance Metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['metric_type', 'timestamp'], name='analytics_p_metric__cd80ae_idx'), models.Index(fields=['user', 'timestamp'], name='analytics_p_user_id_736680_idx')],
            },
        ),
        migrations.CreateModel(
            name='FunnelCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('abandoned_at_step', models.IntegerField(blank=True, null=True)),
                ('steps_completed', models.JSONField(default=list)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('funnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='analytics.funnel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funnel_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Funnel Completion',
                'verbose_name_plural': 'Funnel Completions',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['funnel', 'completed', 'start_time'], name='analytics_f_funnel__94467a_idx'), models.Index(fields=['user', 'start_time'], name='analytics_f_user_id_bd3d17_idx')],
            },
        ),
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=200)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('value', models.FloatField(default=0)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('first_touch', models.CharField(blank=True, max_length=500)),
                ('last_touch', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversion',
                'verbose_name_plural': 'Conversions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'name', 'timestamp'], name='analytics_c_user_id_638bc7_idx'), models.Index(fields=['name', 'timestamp'], name='analytics_c_name_88f7b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('category', models.CharField(choices=[('general', 'General'), ('navigation', 'Navigation'), ('interaction', 'Interaction'), ('feature', 'Feature Usage'), ('error', 'Error'), ('performance', 'Performance'), ('funnel', 'Funnel')], db_index=True, default='general', max_length=50)),
                ('session_id', models.CharField(db_index=True, max_length=200)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('url', models.TextField(blank=True)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('referrer', models.TextField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('platform', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analytics Event',
                'verbose_name_plural': 'Analytics Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='analytics_a_user_id_5c8c13_idx'), models.Index(fields=['session_id', 'timestamp'], name='analytics_a_session_b2ebbe_idx'), models.Index(fields=['name', 'category', 'timestamp'], name='analytics_a_name_b4c37f_idx')],
            },
        ),
    ]
