# Generated by Django 5.1.15 on 2026-03-01 06:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blockchain', '0002_blockchainanchor_submitter_address_and_more'),
        ('vault', '0004_encryptedvaultitem_cached_breach_check_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordTimeline',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='password_timeline', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('total_credentials_tracked', models.IntegerField(default=0)),
                ('total_password_changes', models.IntegerField(default=0)),
                ('total_security_events', models.IntegerField(default=0)),
                ('total_breaches_detected', models.IntegerField(default=0)),
                ('current_overall_score', models.IntegerField(default=50, help_text='Current overall security score (0-100)')),
                ('weakest_credential_domain', models.CharField(blank=True, help_text='Domain of the weakest credential', max_length=255)),
                ('weakest_credential_score', models.IntegerField(default=0, help_text='Score of the weakest credential')),
                ('strongest_credential_domain', models.CharField(blank=True, max_length=255)),
                ('strongest_credential_score', models.IntegerField(default=0)),
                ('average_password_age_days', models.FloatField(default=0.0, help_text='Average age of passwords in days')),
                ('average_strength_score', models.FloatField(default=50.0)),
                ('current_all_strong_streak_days', models.IntegerField(default=0, help_text='Days with all passwords above threshold')),
                ('longest_all_strong_streak_days', models.IntegerField(default=0)),
                ('current_no_breach_streak_days', models.IntegerField(default=0, help_text='Days since last breach detection')),
                ('last_password_change_at', models.DateTimeField(blank=True, null=True)),
                ('last_security_event_at', models.DateTimeField(blank=True, null=True)),
                ('last_computed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Password Timeline',
                'verbose_name_plural': 'Password Timelines',
                'db_table': 'password_archaeology_timeline',
            },
        ),
        migrations.CreateModel(
            name='AchievementRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('achievement_type', models.CharField(choices=[('all_strong_7', 'All Strong (7 Days)'), ('all_strong_30', 'All Strong (30 Days)'), ('all_strong_90', 'All Strong (90 Days)'), ('all_strong_365', 'All Strong (365 Days)'), ('zero_breaches_30', 'Zero Breaches (30 Days)'), ('zero_breaches_90', 'Zero Breaches (90 Days)'), ('zero_breaches_365', 'Zero Breaches (365 Days)'), ('quick_responder', 'Quick Responder'), ('proactive_changer', 'Proactive Changer'), ('diversity_champion', 'Diversity Champion'), ('mfa_everywhere', 'MFA Everywhere'), ('first_password_change', 'First Password Change'), ('ten_passwords_changed', '10 Passwords Changed'), ('fifty_passwords_changed', '50 Passwords Changed'), ('security_score_80', 'Security Score 80+'), ('security_score_90', 'Security Score 90+'), ('security_score_100', 'Perfect Score'), ('time_traveler', 'Used Time Machine'), ('what_if_explorer', 'Used What-If Simulator'), ('streak_master', 'Streak Master (90 days strong)')], max_length=30)),
                ('badge_tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond')], default='bronze', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon_name', models.CharField(blank=True, help_text='Lucide icon name for the badge', max_length=50)),
                ('score_points', models.IntegerField(default=10, help_text='Points awarded for this achievement')),
                ('earned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged', models.BooleanField(default=False, help_text='Whether the user has seen this achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archaeology_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Achievement Record',
                'verbose_name_plural': 'Achievement Records',
                'db_table': 'password_archaeology_achievements',
                'ordering': ['-earned_at'],
                'indexes': [models.Index(fields=['user', '-earned_at'], name='password_ar_user_id_942f32_idx'), models.Index(fields=['achievement_type'], name='password_ar_achieve_46cf0d_idx')],
                'unique_together': {('user', 'achievement_type')},
            },
        ),
        migrations.CreateModel(
            name='PasswordHistoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_domain', models.CharField(blank=True, help_text='Domain or service name (e.g. google.com)', max_length=255)),
                ('credential_label', models.CharField(blank=True, help_text='Human-readable label for the credential', max_length=255)),
                ('old_password_hash', models.CharField(blank=True, help_text='SHA-256 hash of old password (for comparison, never plaintext)', max_length=256)),
                ('new_password_hash', models.CharField(blank=True, help_text='SHA-256 hash of new password (for comparison, never plaintext)', max_length=256)),
                ('strength_before', models.IntegerField(default=0, help_text='Password strength score (0-100) before this change')),
                ('strength_after', models.IntegerField(default=0, help_text='Password strength score (0-100) after this change')),
                ('entropy_before', models.FloatField(default=0.0, help_text='Entropy bits before change')),
                ('entropy_after', models.FloatField(default=0.0, help_text='Entropy bits after change')),
                ('trigger', models.CharField(choices=[('user_initiated', 'User Initiated'), ('breach_response', 'Breach Response'), ('policy_expiration', 'Policy Expiration'), ('predictive_alert', 'Predictive Alert'), ('admin_forced', 'Admin Forced'), ('scheduled_rotation', 'Scheduled Rotation'), ('proactive', 'Proactive Change'), ('system_generated', 'System Generated')], default='user_initiated', max_length=30)),
                ('change_notes', models.TextField(blank=True, help_text='Reason or notes about this change')),
                ('commitment_hash', models.CharField(blank=True, help_text='SHA-256 hash submitted to blockchain', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blockchain_commitment', models.ForeignKey(blank=True, help_text='Blockchain commitment for tamper-proof timestamping', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_history_entries', to='blockchain.pendingcommitment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history_entries', to=settings.AUTH_USER_MODEL)),
                ('vault_item', models.ForeignKey(blank=True, help_text='The vault credential this change applies to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_history', to='vault.encryptedvaultitem')),
            ],
            options={
                'verbose_name': 'Password History Entry',
                'verbose_name_plural': 'Password History Entries',
                'db_table': 'password_archaeology_history',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['user', '-changed_at'], name='password_ar_user_id_d2912b_idx'), models.Index(fields=['vault_item', '-changed_at'], name='password_ar_vault_i_190104_idx'), models.Index(fields=['trigger', '-changed_at'], name='password_ar_trigger_2dc847_idx'), models.Index(fields=['credential_domain'], name='password_ar_credent_b63b69_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('breach_detected', 'Breach Detected'), ('suspicious_login', 'Suspicious Login'), ('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked'), ('mfa_enabled', 'MFA Enabled'), ('mfa_disabled', 'MFA Disabled'), ('device_added', 'New Device Added'), ('device_removed', 'Device Removed'), ('impossible_travel', 'Impossible Travel Detected'), ('password_reuse', 'Password Reuse Detected'), ('weak_password', 'Weak Password Detected'), ('credential_exposed', 'Credential Exposed'), ('phishing_attempt', 'Phishing Attempt'), ('recovery_used', 'Recovery Used'), ('duress_triggered', 'Duress Code Triggered')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional structured data about the event')),
                ('risk_score_impact', models.IntegerField(default=0, help_text='How much this event affected the security score (+/-)')),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archaeology_security_events', to=settings.AUTH_USER_MODEL)),
                ('vault_item', models.ForeignKey(blank=True, help_text='Optional: specific credential this event relates to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archaeology_security_events', to='vault.encryptedvaultitem')),
            ],
            options={
                'verbose_name': 'Security Event',
                'verbose_name_plural': 'Security Events',
                'db_table': 'password_archaeology_security_events',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['user', '-occurred_at'], name='password_ar_user_id_815beb_idx'), models.Index(fields=['event_type', '-occurred_at'], name='password_ar_event_t_8ab8a6_idx'), models.Index(fields=['severity', '-occurred_at'], name='password_ar_severit_150652_idx'), models.Index(fields=['user', 'resolved'], name='password_ar_user_id_8d38af_idx')],
            },
        ),
        migrations.CreateModel(
            name='StrengthSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_domain', models.CharField(blank=True, max_length=255)),
                ('strength_score', models.IntegerField(default=0, help_text='Overall strength score (0-100)')),
                ('entropy_bits', models.FloatField(default=0.0, help_text='Estimated entropy in bits')),
                ('character_class_coverage', models.FloatField(default=0.0, help_text='Fraction of character classes used (0.0-1.0)')),
                ('length', models.IntegerField(default=0, help_text='Password length at this snapshot')),
                ('breach_exposure_count', models.IntegerField(default=0, help_text='Number of known breaches this password appeared in')),
                ('is_reused', models.BooleanField(default=False, help_text='Whether this password was reused across services')),
                ('snapshot_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strength_snapshots', to=settings.AUTH_USER_MODEL)),
                ('vault_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strength_snapshots', to='vault.encryptedvaultitem')),
            ],
            options={
                'verbose_name': 'Strength Snapshot',
                'verbose_name_plural': 'Strength Snapshots',
                'db_table': 'password_archaeology_strength_snapshots',
                'ordering': ['-snapshot_at'],
                'indexes': [models.Index(fields=['user', '-snapshot_at'], name='password_ar_user_id_b1450c_idx'), models.Index(fields=['vault_item', '-snapshot_at'], name='password_ar_vault_i_6dcc57_idx'), models.Index(fields=['credential_domain', '-snapshot_at'], name='password_ar_credent_5fb0ac_idx')],
            },
        ),
        migrations.CreateModel(
            name='WhatIfScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_domain', models.CharField(blank=True, max_length=255)),
                ('scenario_type', models.CharField(choices=[('earlier_change', 'Changed Password Earlier'), ('stronger_password', 'Used Stronger Password'), ('mfa_enabled', 'Enabled MFA Earlier'), ('breach_response', 'Responded to Breach Faster'), ('no_reuse', 'Avoided Password Reuse'), ('regular_rotation', 'Regular Rotation Schedule')], max_length=30)),
                ('scenario_params', models.JSONField(default=dict, help_text='Parameters for the simulation (e.g. {days_earlier: 30})')),
                ('actual_risk_score', models.IntegerField(default=0, help_text='Actual risk score at the time')),
                ('simulated_risk_score', models.IntegerField(default=0, help_text='Risk score if the scenario had played out')),
                ('risk_reduction', models.IntegerField(default=0, help_text='How much risk would have been reduced')),
                ('exposure_days_saved', models.IntegerField(default=0, help_text='Days of exposure that could have been avoided')),
                ('insight_text', models.TextField(blank=True, help_text='Human-readable insight from the simulation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='what_if_scenarios', to=settings.AUTH_USER_MODEL)),
                ('vault_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='what_if_scenarios', to='vault.encryptedvaultitem')),
            ],
            options={
                'verbose_name': 'What-If Scenario',
                'verbose_name_plural': 'What-If Scenarios',
                'db_table': 'password_archaeology_what_if',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='password_ar_user_id_551a03_idx'), models.Index(fields=['scenario_type'], name='password_ar_scenari_abdcf1_idx')],
            },
        ),
    ]
