# Generated by Django 4.2.27 on 2026-01-20 12:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_entangleddevicepair_sharedrandomnesspool_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntropyMeasurementRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entropy_value', models.FloatField(help_text='Shannon entropy in bits per byte (0-8)')),
                ('kl_divergence', models.FloatField(blank=True, help_text='KL divergence from paired pool', null=True)),
                ('is_healthy', models.BooleanField(default=True)),
                ('is_warning', models.BooleanField(default=False)),
                ('is_critical', models.BooleanField(default=False)),
                ('sample_size', models.IntegerField(help_text='Pool size in bytes')),
                ('sample_hash', models.CharField(help_text='SHA-256 hash of sampled data for verification', max_length=64)),
                ('measured_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entropy_measurements', to='security.userdevice')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entropy_history', to='security.entangleddevicepair')),
            ],
            options={
                'verbose_name': 'Entropy Measurement Record',
                'verbose_name_plural': 'Entropy Measurement Records',
                'db_table': 'entropy_measurement_record',
                'ordering': ['-measured_at'],
                'indexes': [models.Index(fields=['pair', 'measured_at'], name='entropy_mea_pair_id_b8dc7f_idx'), models.Index(fields=['is_critical', 'measured_at'], name='entropy_mea_is_crit_2f4eca_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnomalyEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anomaly_type', models.CharField(choices=[('low_entropy', 'Low Entropy'), ('high_kl_divergence', 'High KL Divergence'), ('tampering_suspected', 'Tampering Suspected'), ('sync_failure', 'Sync Failure'), ('device_offline', 'Device Offline'), ('chi_squared_anomaly', 'Chi-Squared Anomaly')], help_text='Type of anomaly detected', max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], help_text='Severity level of the anomaly', max_length=20)),
                ('entropy_value', models.FloatField(blank=True, help_text='Entropy value when anomaly was detected', null=True)),
                ('kl_divergence', models.FloatField(blank=True, help_text='KL divergence when anomaly was detected', null=True)),
                ('auto_revoked', models.BooleanField(default=False, help_text='Whether pair was auto-revoked due to this anomaly')),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional anomaly details')),
                ('recommendation', models.TextField(help_text='Recommended action for this anomaly')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomaly_events', to='security.userdevice')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_events', to='security.entangleddevicepair')),
            ],
            options={
                'verbose_name': 'Anomaly Event',
                'verbose_name_plural': 'Anomaly Events',
                'db_table': 'anomaly_event',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['pair', 'severity'], name='anomaly_eve_pair_id_485629_idx'), models.Index(fields=['resolved', 'detected_at'], name='anomaly_eve_resolve_d3e3ec_idx'), models.Index(fields=['anomaly_type', 'detected_at'], name='anomaly_eve_anomaly_05e282_idx')],
            },
        ),
    ]
