# Generated by Django 4.2.27 on 2026-01-20 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('security', '0004_entropy_anomaly_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=7, help_text='Latitude in decimal degrees (-90 to 90)', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, help_text='Longitude in decimal degrees (-180 to 180)', max_digits=10)),
                ('accuracy_meters', models.FloatField(default=0, help_text='GPS accuracy in meters')),
                ('altitude', models.FloatField(blank=True, help_text='Altitude in meters (for satellite verification)', null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('ip_location_city', models.CharField(blank=True, max_length=255)),
                ('ip_location_country', models.CharField(blank=True, max_length=255)),
                ('ip_location_country_code', models.CharField(blank=True, max_length=10)),
                ('source', models.CharField(choices=[('gps', 'GPS (High Accuracy)'), ('network', 'Network Location'), ('ip_fallback', 'IP Geolocation'), ('manual', 'Manually Provided')], default='ip_fallback', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('server_timestamp', models.DateTimeField(auto_now_add=True, help_text='NTP-synchronized server time')),
                ('is_ntp_verified', models.BooleanField(default=True, help_text='Whether timestamp is NTP-verified')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_records', to='security.userdevice')),
                ('login_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_records', to='security.loginattempt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'location_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ImpossibleTravelEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distance_km', models.FloatField(help_text='Great-circle distance in kilometers')),
                ('time_difference_seconds', models.IntegerField(help_text='Time between locations')),
                ('required_speed_kmh', models.FloatField(help_text='Speed required to travel')),
                ('max_allowed_speed_kmh', models.FloatField(default=920, help_text='Maximum plausible speed (commercial flight ~920 km/h)')),
                ('inferred_travel_mode', models.CharField(choices=[('walking', 'Walking'), ('driving', 'Driving'), ('train', 'Train/Rail'), ('flight', 'Commercial Flight'), ('supersonic', 'Supersonic (Impossible)'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('risk_score', models.IntegerField(default=0, help_text='Risk score 0-100')),
                ('action_taken', models.CharField(choices=[('allowed', 'Allowed'), ('challenged', 'MFA Challenge Required'), ('blocked', 'Access Blocked'), ('travel_verified', 'Travel Verified via Airline'), ('user_confirmed', 'User Confirmed Legitimate')], default='challenged', max_length=30)),
                ('is_legitimate', models.BooleanField(default=False)),
                ('airline_verified', models.BooleanField(default=False)),
                ('verification_data', models.JSONField(blank=True, default=dict, help_text='Airline booking proof or verification details')),
                ('is_cloned_session', models.BooleanField(default=False, help_text='Indicates simultaneous sessions from impossible locations')),
                ('concurrent_session_id', models.CharField(blank=True, max_length=255)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_to_events', to='security.locationhistory')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_travel_events', to=settings.AUTH_USER_MODEL)),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_from_events', to='security.locationhistory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impossible_travel_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'impossible_travel_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeofenceZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Friendly name (e.g., 'Home', 'Office')", max_length=100)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('radius_meters', models.IntegerField(default=500, help_text='Zone radius in meters')),
                ('is_always_trusted', models.BooleanField(default=True, help_text='Skip MFA checks from this zone')),
                ('require_mfa_outside', models.BooleanField(default=True, help_text='Require MFA when logging in from outside all zones')),
                ('notify_on_entry', models.BooleanField(default=False)),
                ('notify_on_exit', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_zones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'geofence_zone',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TravelItinerary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('departure_city', models.CharField(max_length=255)),
                ('departure_country', models.CharField(blank=True, max_length=100)),
                ('departure_airport_code', models.CharField(blank=True, max_length=10)),
                ('departure_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('departure_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('arrival_city', models.CharField(max_length=255)),
                ('arrival_country', models.CharField(blank=True, max_length=100)),
                ('arrival_airport_code', models.CharField(blank=True, max_length=10)),
                ('arrival_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('arrival_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('airline_code', models.CharField(blank=True, max_length=10)),
                ('airline_name', models.CharField(blank=True, max_length=100)),
                ('flight_number', models.CharField(blank=True, max_length=20)),
                ('booking_reference', models.CharField(blank=True, help_text='PNR / Confirmation number', max_length=50)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('failed', 'Verification Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('verification_provider', models.CharField(choices=[('amadeus', 'Amadeus GDS'), ('sabre', 'Sabre'), ('travelport', 'Travelport'), ('manual', 'Manual Entry'), ('email_parse', 'Email Parsed')], default='manual', max_length=20)),
                ('verification_data', models.JSONField(blank=True, default=dict, help_text='API response or verification details')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_itineraries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'travel_itinerary',
                'ordering': ['-departure_time'],
                'indexes': [models.Index(fields=['user', 'departure_time'], name='travel_itin_user_id_85a148_idx'), models.Index(fields=['verification_status'], name='travel_itin_verific_605b44_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='locationhistory',
            index=models.Index(fields=['user', 'timestamp'], name='location_hi_user_id_6233db_idx'),
        ),
        migrations.AddIndex(
            model_name='locationhistory',
            index=models.Index(fields=['latitude', 'longitude'], name='location_hi_latitud_3e9aaf_idx'),
        ),
        migrations.AddIndex(
            model_name='locationhistory',
            index=models.Index(fields=['ip_address'], name='location_hi_ip_addr_7cd8f8_idx'),
        ),
        migrations.AddIndex(
            model_name='impossibletravelevent',
            index=models.Index(fields=['user', 'created_at'], name='impossible__user_id_c199ed_idx'),
        ),
        migrations.AddIndex(
            model_name='impossibletravelevent',
            index=models.Index(fields=['severity', 'resolved'], name='impossible__severit_8f1618_idx'),
        ),
        migrations.AddIndex(
            model_name='impossibletravelevent',
            index=models.Index(fields=['action_taken'], name='impossible__action__cfc50e_idx'),
        ),
    ]
