# Generated by Django 4.2.27 on 2026-01-23 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('security', '0005_locationhistory_impossibletravelevent_geofencezone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapsuleBeneficiary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(blank=True, help_text="e.g., 'Spouse', 'Lawyer', 'Business Partner'", max_length=100)),
                ('access_level', models.CharField(choices=[('view', 'View Only'), ('full', 'Full Access'), ('download', 'Download Only')], default='view', max_length=20)),
                ('requires_verification', models.BooleanField(default=True, help_text='Require identity verification before access')),
                ('verification_token', models.CharField(blank=True, max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(blank=True, help_text='When unlock notification was sent', null=True)),
                ('accessed_at', models.DateTimeField(blank=True, help_text='When beneficiary accessed the content', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'capsule_beneficiary',
            },
        ),
        migrations.CreateModel(
            name='EscrowAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('release_condition', models.CharField(choices=[('date', 'On Specific Date'), ('all_approve', 'All Parties Approve'), ('any_approve', 'Any Party Approves'), ('majority', 'Majority Approves'), ('date_or_approve', 'Date OR Approval')], default='date', max_length=20)),
                ('approved_by', models.JSONField(default=list, help_text='List of user IDs who have approved')),
                ('approval_deadline', models.DateTimeField(blank=True, help_text='Deadline for parties to approve', null=True)),
                ('dispute_resolution_email', models.EmailField(blank=True, help_text='Contact for dispute resolution', max_length=254)),
                ('is_disputed', models.BooleanField(default=False)),
                ('dispute_notes', models.TextField(blank=True)),
                ('is_released', models.BooleanField(default=False)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'escrow_agreement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordWill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('inactivity', 'Inactivity Trigger'), ('date', 'Specific Date'), ('manual', 'Manual Trigger')], default='inactivity', max_length=20)),
                ('inactivity_days', models.IntegerField(blank=True, help_text='Days of inactivity before trigger (for inactivity type)', null=True)),
                ('target_date', models.DateTimeField(blank=True, help_text='Specific date to trigger (for date type)', null=True)),
                ('last_check_in', models.DateTimeField(default=django.utils.timezone.now, help_text="Last time owner confirmed they're alive")),
                ('check_in_reminder_days', models.IntegerField(default=7, help_text='Days before deadline to send reminder')),
                ('is_active', models.BooleanField(default=True)),
                ('is_triggered', models.BooleanField(default=False)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('beneficiaries_notified', models.BooleanField(default=False)),
                ('beneficiaries_notified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Personal message to beneficiaries')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'password_will',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VDFProof',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('challenge', models.TextField(help_text='Initial challenge value (g)')),
                ('output', models.TextField(help_text='VDF output (y = g^(2^t) mod n)')),
                ('proof', models.TextField(help_text='Wesolowski proof (π)')),
                ('modulus', models.TextField(help_text='RSA modulus (n)')),
                ('iterations', models.BigIntegerField(help_text='Number of squarings (t)')),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_time_ms', models.IntegerField(blank=True, help_text='Time to verify the proof in milliseconds', null=True)),
                ('computation_time_seconds', models.FloatField(help_text='Actual computation time')),
                ('hardware_info', models.JSONField(blank=True, default=dict, help_text='Information about the computing hardware')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vdf_proof',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='timelockcapsule',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='timelockcapsule',
            name='beneficiary_email',
        ),
        migrations.RemoveField(
            model_name='timelockcapsule',
            name='puzzle_data',
        ),
        migrations.RemoveField(
            model_name='timelockcapsule',
            name='requires_verification',
        ),
        migrations.RemoveField(
            model_name='timelockcapsule',
            name='unlocked_at',
        ),
        migrations.RemoveField(
            model_name='timelockcapsule',
            name='user',
        ),
        migrations.AddField(
            model_name='timelockcapsule',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timelockcapsule',
            name='capsule_type',
            field=models.CharField(choices=[('general', 'General'), ('will', 'Password Will'), ('escrow', 'Escrow'), ('time_capsule', 'Time Capsule'), ('emergency', 'Emergency Access')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='timelockcapsule',
            name='description',
            field=models.TextField(blank=True, help_text='Additional details about the capsule'),
        ),
        migrations.AddField(
            model_name='timelockcapsule',
            name='max_unlock_attempts',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='timelockcapsule',
            name='opened_at',
            field=models.DateTimeField(blank=True, help_text='When the capsule was unlocked', null=True),
        ),
        migrations.AddField(
            model_name='timelockcapsule',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='time_lock_capsules', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timelockcapsule',
            name='puzzle_a',
            field=models.TextField(blank=True, help_text='Base value for repeated squaring'),
        ),
        migrations.AddField(
            model_name='timelockcapsule',
            name='puzzle_n',
            field=models.TextField(blank=True, help_text='RSA modulus (large integer as string)'),
        ),
        migrations.AddField(
            model_name='timelockcapsule',
            name='puzzle_t',
            field=models.BigIntegerField(blank=True, help_text='Number of squarings required', null=True),
        ),
        migrations.AddField(
            model_name='timelockcapsule',
            name='title',
            field=models.CharField(default='Migrated Capsule', help_text='User-friendly title for the capsule', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timelockcapsule',
            name='unlock_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timelockcapsule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='quantumentropybatch',
            name='provider',
            field=models.CharField(choices=[('anu_qrng', 'ANU QRNG'), ('ibm_quantum', 'IBM Quantum'), ('ionq_quantum', 'IonQ Quantum'), ('noaa_ocean_wave', 'NOAA Ocean Wave'), ('cryptographic_fallback', 'Cryptographic Fallback')], max_length=50),
        ),
        migrations.AlterField(
            model_name='quantumpasswordcertificate',
            name='quantum_source',
            field=models.CharField(choices=[('vacuum_fluctuations', 'Vacuum Fluctuations (ANU)'), ('superconducting_qubit_superposition', 'Superconducting Qubit Superposition (IBM)'), ('trapped_ion_superposition', 'Trapped Ion Superposition (IonQ)'), ('ocean_wave_patterns', 'Ocean Wave Patterns (NOAA)'), ('cryptographic_prng', 'Cryptographic PRNG (Fallback)')], max_length=100),
        ),
        migrations.AlterField(
            model_name='timelockcapsule',
            name='delay_seconds',
            field=models.IntegerField(help_text='Original delay duration in seconds'),
        ),
        migrations.AlterField(
            model_name='timelockcapsule',
            name='encrypted_data',
            field=models.BinaryField(help_text='AES-encrypted secret data'),
        ),
        migrations.AlterField(
            model_name='timelockcapsule',
            name='encryption_key_encrypted',
            field=models.BinaryField(help_text='Encryption key encrypted with server master key'),
        ),
        migrations.AlterField(
            model_name='timelockcapsule',
            name='mode',
            field=models.CharField(choices=[('server', 'Server-Enforced'), ('client', 'Client-Side Puzzle'), ('hybrid', 'Hybrid Mode')], default='server', max_length=20),
        ),
        migrations.AlterField(
            model_name='timelockcapsule',
            name='status',
            field=models.CharField(choices=[('locked', 'Locked'), ('solving', 'Solving (Client Mode)'), ('unlocked', 'Unlocked'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='locked', max_length=20),
        ),
        migrations.AlterField(
            model_name='timelockcapsule',
            name='unlock_at',
            field=models.DateTimeField(help_text='When the capsule becomes accessible'),
        ),
        migrations.AddIndex(
            model_name='timelockcapsule',
            index=models.Index(fields=['owner', 'status'], name='time_lock_c_owner_i_34df4c_idx'),
        ),
        migrations.AddIndex(
            model_name='timelockcapsule',
            index=models.Index(fields=['unlock_at', 'status'], name='time_lock_c_unlock__36cf25_idx'),
        ),
        migrations.AddIndex(
            model_name='timelockcapsule',
            index=models.Index(fields=['capsule_type'], name='time_lock_c_capsule_13e9b4_idx'),
        ),
        migrations.AddField(
            model_name='vdfproof',
            name='capsule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vdf_proofs', to='security.timelockcapsule'),
        ),
        migrations.AddField(
            model_name='passwordwill',
            name='capsule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_will', to='security.timelockcapsule'),
        ),
        migrations.AddField(
            model_name='passwordwill',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_wills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escrowagreement',
            name='capsule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_agreement', to='security.timelockcapsule'),
        ),
        migrations.AddField(
            model_name='escrowagreement',
            name='parties',
            field=models.ManyToManyField(related_name='escrow_agreements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capsulebeneficiary',
            name='capsule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='security.timelockcapsule'),
        ),
        migrations.AlterUniqueTogether(
            name='capsulebeneficiary',
            unique_together={('capsule', 'email')},
        ),
    ]
