# Generated by Django 4.2.27 on 2026-01-31 19:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('security', '0008_duresscode_oceanentropyusagestats_oceanentropybatch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoneypotEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('honeypot_address', models.EmailField(help_text='The unique honeypot email address', max_length=254, unique=True)),
                ('provider_alias_id', models.CharField(blank=True, help_text="ID of the alias in the email provider's system", max_length=255)),
                ('service_name', models.CharField(help_text='Name of the service this honeypot is registered with', max_length=255)),
                ('service_domain', models.CharField(blank=True, help_text='Domain of the associated service (e.g., example.com)', max_length=255)),
                ('vault_item_id', models.UUIDField(blank=True, help_text='Optional link to vault password entry', null=True)),
                ('status', models.CharField(choices=[('active', 'Active - Monitoring'), ('triggered', 'Triggered - Activity Detected'), ('breached', 'Breached - Confirmed Compromise'), ('disabled', 'Disabled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('total_emails_received', models.PositiveIntegerField(default=0)),
                ('spam_emails_received', models.PositiveIntegerField(default=0)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('first_activity_at', models.DateTimeField(blank=True, null=True)),
                ('breach_detected', models.BooleanField(default=False)),
                ('breach_detected_at', models.DateTimeField(blank=True, null=True)),
                ('breach_confidence', models.FloatField(default=0.0, help_text='Confidence level that this is a real breach (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('notes', models.TextField(blank=True, help_text='User notes about this honeypot')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for organization')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for the honeypot', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honeypot_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Honeypot Email',
                'verbose_name_plural': 'Honeypot Emails',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HoneypotConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True, help_text='Master switch for honeypot email feature')),
                ('email_provider', models.CharField(choices=[('simplelogin', 'SimpleLogin'), ('anonaddy', 'AnonAddy'), ('custom', 'Custom SMTP')], default='simplelogin', help_text='Email aliasing service to use', max_length=20)),
                ('provider_api_key', models.TextField(blank=True, help_text='Encrypted API key for the email provider')),
                ('custom_domain', models.CharField(blank=True, help_text='Custom domain for honeypot emails (enterprise only)', max_length=255)),
                ('auto_rotate_on_breach', models.BooleanField(default=False, help_text='Automatically rotate credentials when breach detected')),
                ('require_confirmation', models.BooleanField(default=True, help_text='Require user confirmation before credential rotation')),
                ('auto_create_on_signup', models.BooleanField(default=False, help_text='Automatically create honeypot when adding vault items')),
                ('suggest_honeypot_creation', models.BooleanField(default=True, help_text='Show suggestion to create honeypot when adding vault items')),
                ('notify_on_any_activity', models.BooleanField(default=True, help_text='Notify on any honeypot email activity')),
                ('notify_on_breach', models.BooleanField(default=True, help_text='Notify when breach is confirmed')),
                ('notification_email', models.EmailField(blank=True, help_text='Override email for honeypot notifications', max_length=254)),
                ('max_honeypots', models.PositiveIntegerField(default=50, help_text='Maximum honeypot emails allowed', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='honeypot_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Honeypot Configuration',
                'verbose_name_plural': 'Honeypot Configurations',
            },
        ),
        migrations.CreateModel(
            name='HoneypotBreachEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('low', 'Low - Possible data sharing'), ('medium', 'Medium - Likely breach'), ('high', 'High - Confirmed breach'), ('critical', 'Critical - Active exploitation')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('investigating', 'Investigating'), ('confirmed', 'Confirmed'), ('mitigated', 'Mitigated'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='detected', max_length=20)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_activity_at', models.DateTimeField(blank=True, help_text='When first suspicious activity was detected', null=True)),
                ('public_disclosure_at', models.DateTimeField(blank=True, help_text='When breach was publicly disclosed (if known)', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('detection_method', models.CharField(default='honeypot_activity', help_text='How the breach was detected', max_length=100)),
                ('confidence_score', models.FloatField(default=0.8, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('triggering_activities', models.JSONField(default=list, help_text='IDs of activities that triggered breach detection')),
                ('exposed_data_types', models.JSONField(default=list, help_text='Types of data likely exposed (email, password, etc.)')),
                ('breach_source', models.CharField(blank=True, help_text='Suspected or confirmed source of breach', max_length=255)),
                ('credentials_rotated', models.BooleanField(default=False)),
                ('user_notified', models.BooleanField(default=False)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('user_acknowledged', models.BooleanField(default=False)),
                ('user_acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('user_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('honeypot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breach_events', to='security.honeypotemail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honeypot_breaches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Honeypot Breach Event',
                'verbose_name_plural': 'Honeypot Breach Events',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='HoneypotActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('email_received', 'Email Received'), ('spam_detected', 'Spam Detected'), ('phishing_detected', 'Phishing Detected'), ('marketing_email', 'Marketing Email'), ('password_reset', 'Password Reset Request'), ('account_notification', 'Account Notification'), ('unknown', 'Unknown')], default='email_received', max_length=30)),
                ('sender_address', models.EmailField(blank=True, max_length=254)),
                ('sender_domain', models.CharField(blank=True, max_length=255)),
                ('subject_hash', models.CharField(blank=True, help_text='SHA-256 hash of subject for pattern matching', max_length=64)),
                ('subject_preview', models.CharField(blank=True, help_text='First 100 chars of subject (redacted sensitive info)', max_length=100)),
                ('is_spam', models.BooleanField(default=False)),
                ('spam_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_breach_indicator', models.BooleanField(default=False, help_text='Whether this activity indicates a breach')),
                ('breach_indicators', models.JSONField(blank=True, default=dict, help_text='Detected breach indicators')),
                ('raw_headers', models.TextField(blank=True, help_text='Encrypted email headers for forensics')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('honeypot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='security.honeypotemail')),
            ],
            options={
                'verbose_name': 'Honeypot Activity',
                'verbose_name_plural': 'Honeypot Activities',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='CredentialRotationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vault_item_id', models.UUIDField(blank=True, help_text='Vault item whose credentials were rotated', null=True)),
                ('service_name', models.CharField(max_length=255)),
                ('trigger', models.CharField(choices=[('auto_breach', 'Automatic - Breach Detected'), ('manual_user', 'Manual - User Initiated'), ('manual_admin', 'Manual - Admin Initiated'), ('scheduled', 'Scheduled Rotation')], default='manual_user', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('old_credential_hash', models.CharField(blank=True, help_text='SHA-256 hash of old credential (for verification)', max_length=64)),
                ('new_credential_hash', models.CharField(blank=True, help_text='SHA-256 hash of new credential', max_length=64)),
                ('rotation_method', models.CharField(default='manual', help_text='How the rotation was performed', max_length=50)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('user_confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('breach_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotation_logs', to='security.honeypotbreachevent')),
                ('honeypot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotation_logs', to='security.honeypotemail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_rotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credential Rotation Log',
                'verbose_name_plural': 'Credential Rotation Logs',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='honeypotemail',
            index=models.Index(fields=['user', 'status'], name='security_ho_user_id_7817a8_idx'),
        ),
        migrations.AddIndex(
            model_name='honeypotemail',
            index=models.Index(fields=['honeypot_address'], name='security_ho_honeypo_c30d93_idx'),
        ),
        migrations.AddIndex(
            model_name='honeypotemail',
            index=models.Index(fields=['service_name'], name='security_ho_service_576eee_idx'),
        ),
        migrations.AddIndex(
            model_name='honeypotemail',
            index=models.Index(fields=['breach_detected'], name='security_ho_breach__0fa29d_idx'),
        ),
        migrations.AddIndex(
            model_name='honeypotbreachevent',
            index=models.Index(fields=['user', 'status'], name='security_ho_user_id_d054ea_idx'),
        ),
        migrations.AddIndex(
            model_name='honeypotbreachevent',
            index=models.Index(fields=['severity'], name='security_ho_severit_ee2943_idx'),
        ),
        migrations.AddIndex(
            model_name='honeypotbreachevent',
            index=models.Index(fields=['detected_at'], name='security_ho_detecte_3228d9_idx'),
        ),
        migrations.AddIndex(
            model_name='honeypotactivity',
            index=models.Index(fields=['honeypot', 'received_at'], name='security_ho_honeypo_bdf96f_idx'),
        ),
        migrations.AddIndex(
            model_name='honeypotactivity',
            index=models.Index(fields=['activity_type'], name='security_ho_activit_c25063_idx'),
        ),
        migrations.AddIndex(
            model_name='honeypotactivity',
            index=models.Index(fields=['is_breach_indicator'], name='security_ho_is_brea_c9be7c_idx'),
        ),
        migrations.AddIndex(
            model_name='credentialrotationlog',
            index=models.Index(fields=['user', 'status'], name='security_cr_user_id_50c6de_idx'),
        ),
        migrations.AddIndex(
            model_name='credentialrotationlog',
            index=models.Index(fields=['honeypot'], name='security_cr_honeypo_10bf02_idx'),
        ),
        migrations.AddIndex(
            model_name='credentialrotationlog',
            index=models.Index(fields=['initiated_at'], name='security_cr_initiat_5a936b_idx'),
        ),
    ]
