# Generated by Django 4.2.27 on 2026-02-04 14:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('security', '0009_honeypotemail_honeypotconfiguration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DarkProtocolNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('fingerprint', models.CharField(max_length=128, unique=True)),
                ('node_type', models.CharField(choices=[('entry', 'Entry Node'), ('relay', 'Relay Node'), ('destination', 'Destination Node'), ('bridge', 'Bridge Node')], default='relay', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance'), ('compromised', 'Compromised')], default='active', max_length=20)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('onion_address', models.CharField(blank=True, max_length=128)),
                ('public_key', models.BinaryField()),
                ('signing_key', models.BinaryField()),
                ('bandwidth_mbps', models.IntegerField(default=100)),
                ('max_circuits', models.IntegerField(default=1000)),
                ('current_circuits', models.IntegerField(default=0)),
                ('trust_score', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('uptime_percentage', models.FloatField(default=100.0)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dark_protocol_nodes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-trust_score', '-uptime_percentage'],
            },
        ),
        migrations.CreateModel(
            name='GarlicSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('establishing', 'Establishing'), ('active', 'Active'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='establishing', max_length=20)),
                ('encrypted_path', models.BinaryField()),
                ('path_length', models.IntegerField(default=3)),
                ('layer_keys', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('bytes_sent', models.BigIntegerField(default=0)),
                ('bytes_received', models.BigIntegerField(default=0)),
                ('messages_sent', models.IntegerField(default=0)),
                ('messages_received', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('rotation_pending', models.BooleanField(default=False)),
                ('entry_node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_sessions', to='security.darkprotocolnode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dark_protocol_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DarkProtocolConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=False)),
                ('auto_enable_on_threat', models.BooleanField(default=True)),
                ('preferred_regions', models.JSONField(default=list)),
                ('min_hops', models.IntegerField(default=3)),
                ('max_hops', models.IntegerField(default=5)),
                ('cover_traffic_enabled', models.BooleanField(default=True)),
                ('cover_traffic_intensity', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('session_timeout_minutes', models.IntegerField(default=30)),
                ('auto_path_rotation', models.BooleanField(default=True)),
                ('path_rotation_interval_minutes', models.IntegerField(default=5)),
                ('use_bridge_nodes', models.BooleanField(default=False)),
                ('require_verified_nodes', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dark_protocol_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoverTrafficPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_rate_per_minute', models.IntegerField(default=10)),
                ('max_rate_per_minute', models.IntegerField(default=30)),
                ('burst_probability', models.FloatField(default=0.1)),
                ('avg_interval_ms', models.IntegerField(default=2000)),
                ('jitter_ms', models.IntegerField(default=500)),
                ('min_message_size', models.IntegerField(default=64)),
                ('max_message_size', models.IntegerField(default=4096)),
                ('typical_message_size', models.IntegerField(default=512)),
                ('hourly_pattern', models.JSONField(default=dict)),
                ('learn_from_real_traffic', models.BooleanField(default=True)),
                ('last_pattern_update', models.DateTimeField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cover_traffic_pattern', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficBundle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bundle_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('bundle_type', models.CharField(choices=[('real', 'Real Operation'), ('cover', 'Cover Traffic'), ('heartbeat', 'Heartbeat'), ('padding', 'Padding')], default='cover', max_length=20)),
                ('encrypted_payload', models.BinaryField()),
                ('payload_size', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sequence_number', models.BigIntegerField()),
                ('padding_size', models.IntegerField(default=0)),
                ('timing_jitter_ms', models.IntegerField(default=0)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_bundles', to='security.garlicsession')),
            ],
            options={
                'ordering': ['sequence_number'],
                'indexes': [models.Index(fields=['session', 'is_sent'], name='security_tr_session_77ff14_idx'), models.Index(fields=['created_at'], name='security_tr_created_6d2327_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoutingPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('encrypted_path_data', models.BinaryField()),
                ('hop_count', models.IntegerField(default=3)),
                ('estimated_latency_ms', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('times_used', models.IntegerField(default=0)),
                ('failures', models.IntegerField(default=0)),
                ('entry_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_entries', to='security.darkprotocolnode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_paths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='security_ro_user_id_41aeb2_idx')],
            },
        ),
        migrations.CreateModel(
            name='NetworkHealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('latency_ms', models.IntegerField()),
                ('jitter_ms', models.IntegerField(default=0)),
                ('is_reachable', models.BooleanField(default=True)),
                ('response_time_ms', models.IntegerField(null=True)),
                ('current_load_percent', models.FloatField(default=0.0)),
                ('signature_valid', models.BooleanField(default=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='security.darkprotocolnode')),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['node', 'checked_at'], name='security_ne_node_id_f82e8e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='garlicsession',
            index=models.Index(fields=['user', 'status'], name='security_ga_user_id_115835_idx'),
        ),
        migrations.AddIndex(
            model_name='garlicsession',
            index=models.Index(fields=['expires_at'], name='security_ga_expires_719376_idx'),
        ),
        migrations.AddIndex(
            model_name='darkprotocolnode',
            index=models.Index(fields=['node_type', 'status'], name='security_da_node_ty_1bfa47_idx'),
        ),
        migrations.AddIndex(
            model_name='darkprotocolnode',
            index=models.Index(fields=['region', 'status'], name='security_da_region_a653b0_idx'),
        ),
    ]
