# Generated by Django 5.1.15 on 2026-02-21 17:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0011_threatintelfeed_threatactorttp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='timelockcapsule',
            index=models.Index(fields=['status', 'unlock_at'], name='status_unlock_idx'),
        ),
    ]
