# Generated by Django 5.1.15 on 2026-04-19 05:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0016_dnaconnection_user_foreignkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaptivepasswordconfig',
            name='auto_apply_high_confidence',
            field=models.BooleanField(default=False, help_text='Automatically apply adaptations with high confidence score'),
        ),
        migrations.AddField(
            model_name='decoyvault',
            name='fake_credentials',
            field=models.JSONField(default=dict, help_text='Fake credential set for this decoy vault'),
        ),
        migrations.AddField(
            model_name='duresscodeconfiguration',
            name='decoy_vault_enabled',
            field=models.BooleanField(default=False, help_text='Enable decoy vault for duress scenarios'),
        ),
        migrations.AddField(
            model_name='evidencepackage',
            name='access_pattern_data',
            field=models.JSONField(default=dict, help_text='Access pattern information'),
        ),
        migrations.AddField(
            model_name='evidencepackage',
            name='behavioral_data',
            field=models.JSONField(default=dict, help_text='Alias for behavioral_snapshot'),
        ),
        migrations.AddField(
            model_name='evidencepackage',
            name='chain_of_custody',
            field=models.JSONField(default=list, help_text='Alias for custody_log'),
        ),
        migrations.AddField(
            model_name='evidencepackage',
            name='network_data',
            field=models.JSONField(default=dict, help_text='Alias for network_info'),
        ),
        migrations.AddField(
            model_name='evidencepackage',
            name='session_data',
            field=models.JSONField(default=dict, help_text='Alias for session_recording'),
        ),
        migrations.AddField(
            model_name='geneticevolutionlog',
            name='biological_age_after',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geneticevolutionlog',
            name='biological_age_before',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trustedauthority',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='trustedauthority',
            name='minimum_threat_level',
            field=models.CharField(blank=True, help_text='Minimum threat level that triggers this authority', max_length=20),
        ),
        migrations.AddField(
            model_name='trustedauthority',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='darkprotocolnode',
            name='trust_score',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='geneticpasswordcertificate',
            name='password_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passwordadaptation',
            name='adapted_hash_prefix',
            field=models.CharField(help_text='Hash prefix of ADAPTED password', max_length=32),
        ),
        migrations.AlterField(
            model_name='passwordadaptation',
            name='password_hash_prefix',
            field=models.CharField(help_text='Hash prefix of ORIGINAL password', max_length=32),
        ),
        migrations.AlterField(
            model_name='passwordrotationevent',
            name='credential_id',
            field=models.CharField(db_index=True, help_text='Identifier of the rotated credential', max_length=128),
        ),
        migrations.AlterField(
            model_name='predictiveexpirationrule',
            name='credential_id',
            field=models.CharField(db_index=True, help_text='Identifier of the credential in vault (UUID or external id)', max_length=128),
        ),
        migrations.AlterField(
            model_name='trustedauthority',
            name='authority_type',
            field=models.CharField(choices=[('law_enforcement', 'Law Enforcement'), ('legal_counsel', 'Legal Counsel'), ('security_team', 'Corporate Security Team'), ('family', 'Family/Emergency Contact'), ('emergency_contact', 'Emergency Contact'), ('custom', 'Custom Contact')], max_length=30),
        ),
        migrations.AlterField(
            model_name='trustedauthority',
            name='contact_details',
            field=models.JSONField(default=dict, help_text='Encrypted contact info: {email/phone/webhook_url}'),
        ),
        migrations.AlterField(
            model_name='typingsession',
            name='password_hash_prefix',
            field=models.CharField(help_text='First 16 chars of password hash for correlation', max_length=32),
        ),
    ]
