# Generated by Django 5.1.15 on 2026-06-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0021_alter_garlicsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictiveexpirationrule',
            name='char_class_sequence',
            field=models.CharField(blank=True, default='', help_text="Character-class sequence, e.g. 'ULLLLDDDD' (U/L/D/S)", max_length=256),
        ),
        migrations.AddField(
            model_name='predictiveexpirationrule',
            name='credential_age_days',
            field=models.IntegerField(default=0, help_text='Age of the credential in days at last fingerprint upload'),
        ),
        migrations.AddField(
            model_name='predictiveexpirationrule',
            name='domain_class',
            field=models.CharField(blank=True, default='', help_text='Coarse domain category (finance/healthcare/...) — not the exact domain', max_length=32),
        ),
        migrations.AddField(
            model_name='predictiveexpirationrule',
            name='entropy_band',
            field=models.CharField(blank=True, default='', help_text='Entropy band (very_low/low/medium/high/very_high)', max_length=20),
        ),
        migrations.AddField(
            model_name='predictiveexpirationrule',
            name='has_date_pattern',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='predictiveexpirationrule',
            name='has_dictionary_base',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='predictiveexpirationrule',
            name='has_keyboard_pattern',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='predictiveexpirationrule',
            name='has_leet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='predictiveexpirationrule',
            name='length_bucket',
            field=models.CharField(blank=True, default='', help_text='Length bucket (very_short/short/medium/long/very_long)', max_length=20),
        ),
        migrations.AddField(
            model_name='predictiveexpirationrule',
            name='structure_hash',
            field=models.CharField(blank=True, default='', help_text='Salted SHA-256 (hex) of the structure fingerprint', max_length=64),
        ),
    ]
