# Generated by Django 5.1.15 on 2026-06-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0022_predictiveexpirationrule_char_class_sequence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordStructurePrevalence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_class_pattern', models.CharField(help_text="Char-class transition signature (runs collapsed), e.g. 'ULD'", max_length=64)),
                ('length_bucket', models.CharField(blank=True, default='', help_text='Coarse length bucket; blank = applies to any length', max_length=20)),
                ('prevalence', models.FloatField(default=0.0, help_text='Fraction of breached passwords with this structure (0-1)')),
                ('occurrence_count', models.BigIntegerField(default=0)),
                ('sample_size', models.BigIntegerField(default=0, help_text='Size of the corpus this prevalence was derived from')),
                ('source', models.CharField(default='curated_seed', help_text='Where this statistic came from (curated_seed, internal_darkweb, ...)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Password Structure Prevalence',
                'verbose_name_plural': 'Password Structure Prevalences',
                'db_table': 'security_password_structure_prevalence',
                'ordering': ('-prevalence',),
                'unique_together': {('char_class_pattern', 'length_bucket', 'source')},
            },
        ),
    ]
