# Generated by Django 5.1.15 on 2026-08-05 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0024_adaptive_fingerprint_key_era'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSubstitutionPrior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_char', models.CharField(max_length=1)),
                ('to_char', models.CharField(max_length=1)),
                ('alpha', models.FloatField(default=1.0)),
                ('beta', models.FloatField(default=1.0)),
                ('contributing_users', models.PositiveIntegerField(default=0, help_text='Consenting users folded into the most recent aggregation')),
                ('dp_epsilon', models.FloatField(blank=True, help_text='DP epsilon the noise for this row was drawn under', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Substitution Prior',
                'verbose_name_plural': 'Global Substitution Priors',
                'db_table': 'adaptive_global_substitution_prior',
                'ordering': ['from_char', 'to_char'],
                'constraints': [models.UniqueConstraint(fields=('from_char', 'to_char'), name='uniq_global_prior_per_class')],
            },
        ),
        migrations.CreateModel(
            name='SubstitutionPolicyArm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_char', models.CharField(help_text="Original character of the substitution class (e.g. 'o')", max_length=1)),
                ('to_char', models.CharField(help_text="Substituted character of the class (e.g. '0')", max_length=1)),
                ('alpha', models.FloatField(default=1.0, help_text='Beta posterior alpha (accumulated success evidence + prior)')),
                ('beta', models.FloatField(default=1.0, help_text='Beta posterior beta (accumulated failure evidence + prior)')),
                ('pulls', models.PositiveIntegerField(default=0, help_text='How many rewards have been folded into this arm')),
                ('fp_key_version', models.PositiveIntegerField(default=1, help_text="Fingerprint key era (see AdaptivePasswordConfig.fp_key_version). Arms do not survive a rotation's correlation reset.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitution_policy_arms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Substitution Policy Arm',
                'verbose_name_plural': 'Substitution Policy Arms',
                'db_table': 'adaptive_substitution_policy_arm',
                'ordering': ['from_char', 'to_char'],
                'indexes': [models.Index(fields=['user', 'fp_key_version'], name='policy_arm_user_fpver_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'from_char', 'to_char', 'fp_key_version'), name='uniq_policy_arm_per_user_era')],
            },
        ),
    ]
