# Generated by Django 5.1.15 on 2026-08-05 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0025_adaptive_policy_bandit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adaptationfeedback',
            name='policy_reward_applied_at',
            field=models.DateTimeField(blank=True, help_text='When this feedback was folded into the RL policy (null = pending)', null=True),
        ),
        migrations.AddIndex(
            model_name='adaptationfeedback',
            index=models.Index(fields=['policy_reward_applied_at'], name='adapt_fb_policy_pending_idx'),
        ),
    ]
