# Generated by Django 5.1.15 on 2026-08-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0026_adaptation_feedback_policy_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsubstitutionprior',
            name='from_char',
            field=models.CharField(help_text="Original character of the substitution class (e.g. 'o')", max_length=1),
        ),
        migrations.AlterField(
            model_name='globalsubstitutionprior',
            name='to_char',
            field=models.CharField(help_text="Substituted character of the class (e.g. '0')", max_length=1),
        ),
    ]
