# Generated by Django 5.1.15 on 2026-08-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0027_globalsubstitutionprior_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordadaptation',
            name='memorability_driver',
            field=models.CharField(blank=True, choices=[('length', 'Length fit'), ('patterns', 'Repeated patterns'), ('variety', 'Character-class variety'), ('pronounceable', 'Pronounceability')], default='', help_text='Client-reported memorability feature that moved most for this adaptation (empty when nothing moved or a pre-Phase-4 client).', max_length=16),
        ),
        migrations.AddField(
            model_name='usertypingprofile',
            name='memorability_weights',
            field=models.JSONField(default=dict, help_text="Learned memorability feature weights: {'length': 0.2, 'patterns': 0.3, 'variety': 0.2, 'pronounceable': 0.3}. Empty means 'use the defaults'."),
        ),
    ]
