# Generated by Django 5.1.15 on 2026-08-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0028_adaptive_memorability_phase4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordadaptation',
            name='status',
            field=models.CharField(choices=[('suggested', 'Suggested'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('active', 'Active'), ('rolled_back', 'Rolled Back'), ('expired', 'Expired')], default='suggested', max_length=20),
        ),
    ]
