# Generated by Django 5.1.15 on 2026-08-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0029_adaptive_expired_status_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordadaptation',
            name='memorability_driver_delta',
            field=models.FloatField(blank=True, help_text="Signed before→after change in the driver feature's own score, in [-1, 1]. Negative means the driver feature got LESS memorable.", null=True),
        ),
    ]
