# Generated by Django 5.1.15 on 2026-08-22 15:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0030_adaptive_driver_delta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DuressSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, help_text='SHA-256 hex digest of the client-generated signal token', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('trigger_count', models.PositiveIntegerField(default=0)),
                ('duress_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='security.duresscode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duress_signals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Duress Signal',
                'verbose_name_plural': 'Duress Signals',
                'db_table': 'security_duress_signal',
                'indexes': [models.Index(fields=['user', 'is_active'], name='security_du_user_id_a85063_idx'), models.Index(fields=['token_hash'], name='security_du_token_h_a84c3e_idx')],
            },
        ),
    ]
