# Generated by Django 4.2.16 on 2025-11-28 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('ab_test', 'A/B Test'), ('multivariate', 'Multivariate Test'), ('feature_rollout', 'Feature Rollout')], default='ab_test', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='draft', max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('variants', models.JSONField(default=list, help_text='List of variants with weights')),
                ('traffic_allocation', models.FloatField(default=1.0, help_text='Percentage of traffic to include (0.0-1.0)')),
                ('targeting', models.JSONField(blank=True, default=dict, help_text='Targeting rules')),
                ('primary_goal', models.CharField(blank=True, max_length=200)),
                ('secondary_goals', models.JSONField(blank=True, default=list)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('winner', models.CharField(blank=True, max_length=100)),
                ('confidence', models.FloatField(blank=True, help_text='Statistical confidence (0.0-1.0)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_experiments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Experiment',
                'verbose_name_plural': 'Experiments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=False)),
                ('enabled_for_all', models.BooleanField(default=False)),
                ('enabled_for_cohorts', models.JSONField(blank=True, default=list)),
                ('rollout_percentage', models.IntegerField(default=0, help_text='Percentage of users to enable for (0-100)')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Additional configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_flags', to=settings.AUTH_USER_MODEL)),
                ('enabled_for_users', models.ManyToManyField(blank=True, related_name='feature_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlagUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('was_enabled', models.BooleanField()),
                ('context', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('feature_flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='ab_testing.featureflag')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_flag_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feature Flag Usage',
                'verbose_name_plural': 'Feature Flag Usage Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['feature_flag', 'timestamp'], name='ab_testing__feature_e0b274_idx'), models.Index(fields=['user', 'timestamp'], name='ab_testing__user_id_f9ad78_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExperimentMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variant', models.CharField(max_length=100)),
                ('anonymous_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('type', models.CharField(choices=[('exposure', 'Exposure'), ('outcome', 'Outcome'), ('interaction', 'Interaction')], db_index=True, max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('value', models.FloatField(default=0)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='ab_testing.experiment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiment_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Experiment Metric',
                'verbose_name_plural': 'Experiment Metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['experiment', 'type', 'timestamp'], name='ab_testing__experim_645e99_idx'), models.Index(fields=['experiment', 'variant', 'type', 'timestamp'], name='ab_testing__experim_e4a070_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExperimentAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anonymous_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('variant', models.CharField(max_length=100)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='ab_testing.experiment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiment_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Experiment Assignment',
                'verbose_name_plural': 'Experiment Assignments',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['experiment', 'user'], name='ab_testing__experim_6744ce_idx'), models.Index(fields=['experiment', 'anonymous_id'], name='ab_testing__experim_d302c1_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='experimentassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('experiment', 'user'), name='unique_user_experiment_assignment'),
        ),
        migrations.AddConstraint(
            model_name='experimentassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('anonymous_id__isnull', False), models.Q(('anonymous_id', ''), _negated=True)), fields=('experiment', 'anonymous_id'), name='unique_anon_experiment_assignment'),
        ),
    ]
