# Generated by Django 5.1.15 on 2026-04-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambient_auth', '0002_link_geofence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambientcontext',
            name='centroid_json',
            field=models.JSONField(blank=True, default=dict, help_text='64-d centroid for this cluster.'),
        ),
        migrations.AlterField(
            model_name='ambientcontext',
            name='is_trusted',
            field=models.BooleanField(default=False, help_text='Only trusted contexts grant MFA step-down. Must be explicitly promoted.'),
        ),
        migrations.AlterField(
            model_name='ambientcontext',
            name='label',
            field=models.CharField(help_text='Human-readable label (user-provided or auto-generated).', max_length=64),
        ),
        migrations.AlterField(
            model_name='ambientcontext',
            name='radius',
            field=models.FloatField(default=0.35, help_text='Cosine distance threshold under which an observation counts as a match.'),
        ),
        migrations.AlterField(
            model_name='ambientobservation',
            name='coarse_features_json',
            field=models.JSONField(blank=True, default=dict, help_text='Bucketed coarse features (light_bucket, motion_class, ...).'),
        ),
        migrations.AlterField(
            model_name='ambientobservation',
            name='embedding_digest',
            field=models.CharField(blank=True, default='', help_text='Opaque LSH digest (hex). Sensitive signals (BSSIDs, audio, BT) folded in here; never raw.', max_length=256),
        ),
        migrations.AlterField(
            model_name='ambientobservation',
            name='reasons_json',
            field=models.JSONField(blank=True, default=list, help_text='Structured explainability payload for the UX.'),
        ),
        migrations.AlterField(
            model_name='ambientobservation',
            name='signal_availability',
            field=models.JSONField(blank=True, default=dict, help_text='Bitmap of which signals were captured, e.g. {"ambient_light": true, "wifi_signature": false}'),
        ),
        migrations.AlterField(
            model_name='ambientprofile',
            name='centroid_json',
            field=models.JSONField(blank=True, default=dict, help_text='Global centroid of all observations (64-d float vector + covariance).'),
        ),
        migrations.AlterField(
            model_name='ambientprofile',
            name='device_fp',
            field=models.CharField(help_text='Stable device fingerprint (FingerprintJS visitorId or equivalent).', max_length=128),
        ),
        migrations.AlterField(
            model_name='ambientprofile',
            name='local_salt_version',
            field=models.PositiveIntegerField(default=1, help_text='Bump when the client rotates its per-user LSH salt; forces new baseline.'),
        ),
        migrations.AlterField(
            model_name='ambientprofile',
            name='signal_weights_json',
            field=models.JSONField(blank=True, default=dict, help_text='Per-signal reliability weights in [0,1] learned from observation accuracy.'),
        ),
        migrations.AlterField(
            model_name='ambientsignalconfig',
            name='enabled_on_surfaces',
            field=models.JSONField(blank=True, default=list, help_text='List of surfaces on which this signal is enabled, e.g. ["web", "mobile"].'),
        ),
        migrations.AlterField(
            model_name='ambientsignalconfig',
            name='signal_key',
            field=models.CharField(help_text='One of ambient_auth.models.SIGNAL_KEYS.', max_length=32),
        ),
    ]
