# Generated by Django 5.1.15 on 2026-04-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultrasonic_pairing', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pairingsession',
            new_name='ultrasonic__initiat_b18bf5_idx',
            old_name='up_session_init_st_idx',
        ),
        migrations.RenameIndex(
            model_name='pairingsession',
            new_name='ultrasonic__status_403170_idx',
            old_name='up_session_st_exp_idx',
        ),
        migrations.AlterField(
            model_name='pairingevent',
            name='kind',
            field=models.CharField(help_text='initiate|claim|confirm|share|deliver|enroll_device|expire|fail', max_length=32),
        ),
        migrations.AlterField(
            model_name='pairingsession',
            name='initiator_pub_key',
            field=models.BinaryField(help_text='SEC1 uncompressed P-256 public key of the initiator (65B).'),
        ),
        migrations.AlterField(
            model_name='pairingsession',
            name='nonce',
            field=models.BinaryField(help_text='6 random bytes emitted over the ultrasonic channel.'),
        ),
        migrations.AlterField(
            model_name='pairingsession',
            name='responder_pub_key',
            field=models.BinaryField(blank=True, help_text='Responder public key, written on claim.', null=True),
        ),
    ]
