# Generated by Django 4.2.16 on 2025-10-18 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('password_strength', 'Password Strength (LSTM)'), ('anomaly_detection', 'Anomaly Detection (Isolation Forest)'), ('behavior_clustering', 'Behavior Clustering (K-Means)'), ('threat_classification', 'Threat Classification (CNN-LSTM)'), ('risk_prediction', 'Risk Prediction (Random Forest)')], max_length=30, unique=True)),
                ('version', models.CharField(max_length=50)),
                ('file_path', models.CharField(help_text='Path to saved model file', max_length=500)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('auc_roc', models.FloatField(blank=True, null=True)),
                ('training_samples', models.IntegerField(default=0)),
                ('training_date', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('hyperparameters', models.JSONField(default=dict)),
                ('feature_importance', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'ML Model Metadata',
                'ordering': ['-training_date'],
            },
        ),
        migrations.CreateModel(
            name='UserBehaviorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typical_login_hours', models.JSONField(default=list, help_text='Hours user typically logs in')),
                ('typical_login_days', models.JSONField(default=list, help_text='Days user typically logs in')),
                ('avg_session_duration', models.FloatField(default=0.0, help_text='Average session duration in minutes')),
                ('typing_speed_avg', models.FloatField(default=0.0, help_text='Average typing speed (chars/sec)')),
                ('typing_speed_std', models.FloatField(default=0.0, help_text='Typing speed standard deviation')),
                ('mouse_movement_pattern', models.JSONField(default=dict, help_text='Mouse movement characteristics')),
                ('common_locations', models.JSONField(default=list, help_text='Common login locations (lat, lon)')),
                ('common_ip_ranges', models.JSONField(default=list, help_text='Common IP address ranges')),
                ('common_devices', models.JSONField(default=list, help_text='Device fingerprints')),
                ('common_browsers', models.JSONField(default=list, help_text='Common browsers used')),
                ('common_os', models.JSONField(default=list, help_text='Common operating systems')),
                ('vault_access_frequency', models.FloatField(default=0.0)),
                ('password_update_frequency', models.FloatField(default=0.0)),
                ('avg_passwords_accessed_per_session', models.FloatField(default=0.0)),
                ('last_trained', models.DateTimeField(blank=True, null=True)),
                ('samples_used', models.IntegerField(default=0)),
                ('model_version', models.CharField(default='1.0', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MLTrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(max_length=30)),
                ('features', models.JSONField(help_text='Input features')),
                ('label', models.JSONField(help_text='Ground truth label')),
                ('weight', models.FloatField(default=1.0, help_text='Sample weight for training')),
                ('source', models.CharField(blank=True, help_text='Data source', max_length=100)),
                ('is_validated', models.BooleanField(default=False)),
                ('validation_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_type', 'is_validated'], name='ml_security_model_t_9c88e0_idx'), models.Index(fields=['created_at'], name='ml_security_created_6d234d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ThreatPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('threat_type', models.CharField(choices=[('brute_force', 'Brute Force Attack'), ('credential_stuffing', 'Credential Stuffing'), ('account_takeover', 'Account Takeover'), ('bot_activity', 'Bot Activity'), ('phishing', 'Phishing Attempt'), ('data_exfiltration', 'Data Exfiltration'), ('suspicious_pattern', 'Suspicious Pattern')], max_length=30)),
                ('threat_score', models.FloatField(help_text='Threat probability (0-1)')),
                ('risk_level', models.IntegerField(help_text='Overall risk level (0-100)')),
                ('sequence_features', models.JSONField(help_text='Time-series features analyzed')),
                ('spatial_features', models.JSONField(help_text='Spatial features (from CNN)')),
                ('temporal_features', models.JSONField(help_text='Temporal features (from LSTM)')),
                ('cnn_output', models.JSONField(help_text='CNN layer output')),
                ('lstm_output', models.JSONField(help_text='LSTM layer output')),
                ('final_prediction', models.JSONField(help_text='Final hybrid model prediction')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255)),
                ('recommended_action', models.CharField(help_text='MFA, block, monitor, etc.', max_length=100)),
                ('action_executed', models.CharField(blank=True, max_length=100)),
                ('was_true_positive', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threat_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='ml_security_user_id_44c6a5_idx'), models.Index(fields=['threat_type', 'created_at'], name='ml_security_threat__8bb592_idx'), models.Index(fields=['risk_level'], name='ml_security_risk_le_ff6fc3_idx')],
            },
        ),
        migrations.CreateModel(
            name='PasswordStrengthPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(help_text='SHA-256 hash of password for tracking', max_length=255)),
                ('strength', models.CharField(choices=[('very_weak', 'Very Weak'), ('weak', 'Weak'), ('moderate', 'Moderate'), ('strong', 'Strong'), ('very_strong', 'Very Strong')], max_length=20)),
                ('confidence_score', models.FloatField(help_text='Model confidence (0-1)')),
                ('entropy', models.FloatField(help_text='Password entropy score')),
                ('character_diversity', models.FloatField()),
                ('length', models.IntegerField()),
                ('has_numbers', models.BooleanField(default=False)),
                ('has_uppercase', models.BooleanField(default=False)),
                ('has_lowercase', models.BooleanField(default=False)),
                ('has_special', models.BooleanField(default=False)),
                ('contains_common_patterns', models.BooleanField(default=False)),
                ('guessability_score', models.FloatField(help_text='How easily guessable (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='password_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='ml_security_user_id_21cec3_idx'), models.Index(fields=['strength'], name='ml_security_strengt_01e1c4_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnomalyDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('anomaly_type', models.CharField(choices=[('location', 'Unusual Location'), ('time', 'Unusual Time'), ('device', 'Unknown Device'), ('behavior', 'Unusual Behavior'), ('velocity', 'Impossible Travel Velocity'), ('frequency', 'Unusual Access Frequency'), ('multiple', 'Multiple Anomalies')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('anomaly_score', models.FloatField(help_text='Anomaly score from model (0-1)')),
                ('confidence', models.FloatField(help_text='Model confidence (0-1)')),
                ('ip_address', models.GenericIPAddressField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255)),
                ('user_agent', models.TextField(blank=True)),
                ('expected_values', models.JSONField(default=dict, help_text='Expected behavior values')),
                ('actual_values', models.JSONField(default=dict, help_text='Actual observed values')),
                ('deviations', models.JSONField(default=dict, help_text='Calculated deviations')),
                ('action_taken', models.CharField(blank=True, help_text='MFA, lock, alert, etc.', max_length=50)),
                ('was_false_positive', models.BooleanField(default=False)),
                ('user_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='ml_security_user_id_de00fc_idx'), models.Index(fields=['severity', 'created_at'], name='ml_security_severit_2091d1_idx'), models.Index(fields=['anomaly_type'], name='ml_security_anomaly_6bdb68_idx')],
            },
        ),
    ]
