# Generated by Django 4.2.27 on 2026-02-06 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vault', '0004_encryptedvaultitem_cached_breach_check_and_more'),
        ('ml_security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confidence_score', models.FloatField(help_text='Prediction confidence 0.0-1.0')),
                ('prediction_reason', models.CharField(choices=[('time_pattern', 'Time-Based Pattern'), ('sequence_pattern', 'Sequence Pattern'), ('domain_correlation', 'Domain Correlation'), ('context_match', 'Context Match'), ('frequency', 'High Frequency'), ('recent', 'Recently Used'), ('combined', 'Multiple Signals')], max_length=30)),
                ('reason_details', models.JSONField(blank=True, default=dict, help_text='Detailed breakdown of prediction factors')),
                ('rank', models.SmallIntegerField(default=1, help_text='Rank among predictions for this context')),
                ('trigger_domain', models.CharField(blank=True, max_length=255)),
                ('trigger_context', models.JSONField(blank=True, default=dict, help_text='Context snapshot when prediction was made')),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('was_used', models.BooleanField(blank=True, help_text='True if user used this prediction', null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('was_dismissed', models.BooleanField(default=False)),
                ('model_version', models.CharField(default='1.0', max_length=20)),
                ('alternative_item_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_instead_of_predictions', to='vault.encryptedvaultitem')),
                ('predicted_vault_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='vault.encryptedvaultitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intent_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-predicted_at', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='PredictiveIntentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('learn_from_vault_access', models.BooleanField(default=True)),
                ('learn_from_autofill', models.BooleanField(default=True)),
                ('show_predictions', models.BooleanField(default=True)),
                ('min_confidence_threshold', models.FloatField(default=0.7, help_text='Minimum confidence to show prediction')),
                ('preload_confidence_threshold', models.FloatField(default=0.85, help_text='Minimum confidence to preload credential')),
                ('max_predictions_shown', models.SmallIntegerField(default=5)),
                ('max_preloaded', models.SmallIntegerField(default=3)),
                ('excluded_domains', models.JSONField(blank=True, default=list, help_text='Domains to never learn from or predict for')),
                ('pattern_retention_days', models.SmallIntegerField(default=90, help_text='Days to retain usage patterns')),
                ('notify_high_confidence', models.BooleanField(default=False, help_text='Push notification for high-confidence predictions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='predictive_intent_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Predictive Intent Settings',
                'verbose_name_plural': 'Predictive Intent Settings',
            },
        ),
        migrations.CreateModel(
            name='ContextSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_domain', models.CharField(max_length=255)),
                ('current_url_hash', models.CharField(help_text='SHA-256 hash of full URL for privacy', max_length=64)),
                ('page_title_keywords', models.JSONField(blank=True, default=list, help_text='Extracted keywords from page title')),
                ('active_form_detected', models.BooleanField(default=False)),
                ('login_form_probability', models.FloatField(default=0.0, help_text='ML confidence that a login form is present')),
                ('form_fields_detected', models.JSONField(blank=True, default=list, help_text='Types of form fields detected')),
                ('tab_count', models.SmallIntegerField(default=1)),
                ('time_on_page_seconds', models.IntegerField(default=0)),
                ('is_new_tab', models.BooleanField(default=False)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet')], default='desktop', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('predictions_generated', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_signals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PreloadedCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_credential', models.BinaryField(help_text='Session-key encrypted credential for fast access')),
                ('encryption_iv', models.BinaryField()),
                ('session_key_id', models.CharField(help_text='Reference to session encryption key', max_length=64)),
                ('preload_reason', models.CharField(max_length=50)),
                ('confidence_at_preload', models.FloatField()),
                ('preloaded_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('was_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('requires_biometric', models.BooleanField(default=False, help_text='Require biometric confirmation before delivery')),
                ('delivery_count', models.SmallIntegerField(default=0, help_text='Number of times delivered (for rate limiting)')),
                ('prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preloaded_credentials', to='ml_security.intentprediction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preloaded_credentials', to=settings.AUTH_USER_MODEL)),
                ('vault_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preloaded_instances', to='vault.encryptedvaultitem')),
            ],
            options={
                'ordering': ['-preloaded_at'],
                'indexes': [models.Index(fields=['user', 'expires_at'], name='ml_security_user_id_a0dedf_idx'), models.Index(fields=['user', 'vault_item'], name='ml_security_user_id_ff7e91_idx'), models.Index(fields=['session_key_id'], name='ml_security_session_4bdffc_idx')],
            },
        ),
        migrations.CreateModel(
            name='PredictionFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(choices=[('used', 'Prediction Used'), ('dismissed', 'Prediction Dismissed'), ('wrong', 'Wrong Prediction'), ('helpful', 'Marked Helpful'), ('not_helpful', 'Marked Not Helpful'), ('timeout', 'Prediction Expired'), ('alternative', 'Used Alternative')], max_length=20)),
                ('was_correct', models.BooleanField(blank=True, help_text='Whether prediction matched user intent', null=True)),
                ('time_to_use_ms', models.IntegerField(blank=True, help_text='Time from prediction shown to use', null=True)),
                ('time_to_dismiss_ms', models.IntegerField(blank=True, help_text='Time from prediction shown to dismiss', null=True)),
                ('context_snapshot', models.JSONField(blank=True, default=dict)),
                ('explicit_rating', models.SmallIntegerField(blank=True, help_text='User rating 1-5 if explicitly provided', null=True)),
                ('user_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_for_training', models.BooleanField(default=False)),
                ('training_batch_id', models.CharField(blank=True, max_length=64)),
                ('alternative_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vault.encryptedvaultitem')),
                ('prediction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='ml_security.intentprediction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='ml_security_user_id_8d016a_idx'), models.Index(fields=['feedback_type'], name='ml_security_feedbac_ae7869_idx'), models.Index(fields=['was_correct'], name='ml_security_was_cor_9940c8_idx'), models.Index(fields=['used_for_training'], name='ml_security_used_fo_bd16c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='PasswordUsagePattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('day_of_week', models.SmallIntegerField(help_text='0=Monday, 6=Sunday')),
                ('time_of_day', models.CharField(choices=[('early_morning', 'Early Morning (5-8am)'), ('morning', 'Morning (8-12pm)'), ('afternoon', 'Afternoon (12-5pm)'), ('evening', 'Evening (5-9pm)'), ('night', 'Night (9pm-12am)'), ('late_night', 'Late Night (12-5am)')], max_length=20)),
                ('hour_of_day', models.SmallIntegerField()),
                ('domain', models.CharField(max_length=255)),
                ('domain_category', models.CharField(blank=True, help_text='work/personal/social/financial/shopping/entertainment', max_length=50)),
                ('device_fingerprint_hash', models.CharField(blank=True, max_length=64)),
                ('location_hash', models.CharField(blank=True, help_text='Hashed location for pattern matching', max_length=64)),
                ('referrer_domain_hash', models.CharField(blank=True, max_length=64)),
                ('session_sequence_position', models.SmallIntegerField(default=1, help_text='Position in session access sequence')),
                ('access_method', models.CharField(choices=[('search', 'Search'), ('browse', 'Browse List'), ('autofill', 'Browser Autofill'), ('prediction', 'From Prediction'), ('quick_access', 'Quick Access/Favorites')], default='browse', max_length=30)),
                ('time_to_access_ms', models.IntegerField(blank=True, help_text='Time from page load to credential use', null=True)),
                ('previous_vault_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followed_by_patterns', to='vault.encryptedvaultitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_patterns', to=settings.AUTH_USER_MODEL)),
                ('vault_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_patterns', to='vault.encryptedvaultitem')),
            ],
            options={
                'ordering': ['-access_time'],
                'indexes': [models.Index(fields=['user', 'access_time'], name='ml_security_user_id_d4a2dd_idx'), models.Index(fields=['user', 'vault_item'], name='ml_security_user_id_97078b_idx'), models.Index(fields=['user', 'domain'], name='ml_security_user_id_4ed955_idx'), models.Index(fields=['user', 'day_of_week', 'hour_of_day'], name='ml_security_user_id_dc6597_idx'), models.Index(fields=['domain', 'vault_item'], name='ml_security_domain_641a3a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='intentprediction',
            index=models.Index(fields=['user', 'expires_at'], name='ml_security_user_id_36745a_idx'),
        ),
        migrations.AddIndex(
            model_name='intentprediction',
            index=models.Index(fields=['user', 'predicted_at'], name='ml_security_user_id_aab578_idx'),
        ),
        migrations.AddIndex(
            model_name='intentprediction',
            index=models.Index(fields=['user', 'trigger_domain'], name='ml_security_user_id_3b8a97_idx'),
        ),
        migrations.AddIndex(
            model_name='intentprediction',
            index=models.Index(fields=['was_used'], name='ml_security_was_use_e09982_idx'),
        ),
        migrations.AddIndex(
            model_name='contextsignal',
            index=models.Index(fields=['user', 'timestamp'], name='ml_security_user_id_d43e89_idx'),
        ),
        migrations.AddIndex(
            model_name='contextsignal',
            index=models.Index(fields=['user', 'current_domain'], name='ml_security_user_id_fdc88d_idx'),
        ),
        migrations.AddIndex(
            model_name='contextsignal',
            index=models.Index(fields=['predictions_generated'], name='ml_security_predict_8383c9_idx'),
        ),
    ]
