# Generated by Django 5.1.15 on 2026-04-19 05:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_recovery', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='recoverycircle',
            new_name='social_reco_user_id_ddf884_idx',
            old_name='social_reco_user_id_7bf0cd_idx',
        ),
        migrations.RenameIndex(
            model_name='recoverycircle',
            new_name='social_reco_status_5fc426_idx',
            old_name='social_reco_status_7cc2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='socialrecoveryauditlog',
            new_name='social_reco_user_id_682313_idx',
            old_name='social_reco_user_id_a1f2d4_idx',
        ),
        migrations.RenameIndex(
            model_name='socialrecoveryauditlog',
            new_name='social_reco_event_t_8e4370_idx',
            old_name='social_reco_event_t_19ad03_idx',
        ),
        migrations.RenameIndex(
            model_name='socialrecoveryrequest',
            new_name='social_reco_circle__c91303_idx',
            old_name='social_reco_circle__f9b921_idx',
        ),
        migrations.RenameIndex(
            model_name='socialrecoveryrequest',
            new_name='social_reco_status_2a69af_idx',
            old_name='social_reco_status_3c3eb8_idx',
        ),
        migrations.RenameIndex(
            model_name='vouchattestation',
            new_name='social_reco_request_e1e7e9_idx',
            old_name='social_reco_request_1c91f0_idx',
        ),
        migrations.RenameIndex(
            model_name='voucher',
            new_name='social_reco_circle__12e9f7_idx',
            old_name='social_reco_circle__9af1a2_idx',
        ),
        migrations.RenameIndex(
            model_name='voucher',
            new_name='social_reco_invitat_f4311d_idx',
            old_name='social_reco_invitat_b41f05_idx',
        ),
        migrations.AlterField(
            model_name='recoverycircle',
            name='cooldown_hours',
            field=models.IntegerField(default=24, help_text='Minimum time between consecutive live recovery requests.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(720)]),
        ),
        migrations.AlterField(
            model_name='recoverycircle',
            name='min_total_stake',
            field=models.IntegerField(default=0, help_text='Sum of stake units vouchers must collectively commit.'),
        ),
        migrations.AlterField(
            model_name='recoverycircle',
            name='min_voucher_reputation',
            field=models.IntegerField(default=0, help_text='Minimum ReputationAccount.score required before a voucher can participate in a live recovery request.'),
        ),
        migrations.AlterField(
            model_name='recoverycircle',
            name='secret_commitment',
            field=models.BinaryField(help_text='Pedersen commitment of the master recovery seed (33 bytes)'),
        ),
        migrations.AlterField(
            model_name='recoverycircle',
            name='threshold',
            field=models.IntegerField(help_text='Minimum number of vouchers required (M in M-of-N)', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='recoverycircle',
            name='total_vouchers',
            field=models.IntegerField(help_text='Total vouchers enrolled (N in M-of-N)', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='relationshipcommitment',
            name='pedersen_commitment',
            field=models.BinaryField(help_text='33-byte compressed secp256k1 point (C = m*G + r*H)'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='did_string',
            field=models.CharField(blank=True, default='', help_text='W3C DID (e.g. did:key:z...) for external vouchers', max_length=255),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='relationship_label',
            field=models.CharField(blank=True, default='', help_text="Free-form label such as 'spouse', 'lawyer', 'co-founder'.", max_length=64),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='share_index',
            field=models.IntegerField(default=1, help_text='Shamir share index (x-coordinate).'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='stake_amount',
            field=models.IntegerField(default=0, help_text='Stake committed by the voucher (password_reputation units).'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='vouch_weight',
            field=models.IntegerField(default=1, help_text='Relative weight this voucher contributes toward the quorum.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
