/**
 * Layered Recovery Mesh - E2E Tests (Tier 1 + Tier 3 + ZK assertion).
 *
 * Covers:
 *   Tier 1 (Recovery Key)  — enroll, logout, recover, vault readable
 *   Tier 3 (Time-Locked)   — enroll, fast-forward, release, recover
 *   Tier 2 (Social Mesh)   — skipped (multi-actor handshake; covered by
 *                            existing social-recovery e2e)
 *
 * Plus a NETWORK-ZK ASSERTION across the Tier-1 enrollment flow that
 * captures every outgoing request body and asserts the recovery key
 * pattern never appears in any payload. This is the keystone test —
 * never weaken it.
 *
 * Tier 3 uses a Django management command (`advance_time_lock`) to
 * fast-forward `release_after` so the test runs in seconds rather than
 * 7+ days.
 *
 * Worker note: this spec needs a live Django backend on :8000 (for
 * registration/login/recovery-factor APIs) and shells out to
 * `python manage.py advance_time_lock` directly, so `python`/Django must
 * be on PATH with the same DATABASE_URL the running server uses. CI's
 * e2e.yml boots this natively (Postgres + Redis services, migrate,
 * runserver) rather than via docker-compose.
 *
 * Expected `data-testid` selectors (coordinated with Units 11 / 13):
 *   recovery-key-enroll-v2, rk-enroll-master-password, rk-enroll-start
 *   recovery-key-display, rk-copy, rk-download, rk-confirm-phrase, rk-enroll-save
 *   rk-enroll-success
 *   recovery-key-use-v2, rk-use-input, rk-use-recover
 *   rk-use-new-password, rk-use-confirm-new-password, rk-use-set-password
 *   time-locked-enroll, tl-enroll-master-password, tl-enroll-generate
 *   tl-enroll-confirm, tl-enroll-success
 *   time-locked-recover, tl-recover-username, tl-recover-file
 *   tl-recover-begin, tl-recover-poll, tl-recover-set-password
 */
import { test, expect } from '@playwright/test';
import { execSync } from 'child_process';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const BASE_URL = process.env.BASE_URL || 'http://localhost:5173';
const API_URL = process.env.API_URL || 'http://localhost:8000';

// 26-char recovery key pattern generated by generateRecoveryKey.js:
// alphabet excludes I/O/0/1, formatted as six 4-char groups plus a
// trailing 2-char group (ABCD-EFGH-JKLM-NPQR-STUV-WXYZ-23). Used by the
// network-ZK assertion to catch any accidental leak.
const RECOVERY_KEY_REGEX = /^[A-HJ-NP-Z2-9]{4}(-[A-HJ-NP-Z2-9]{4}){5}-[A-HJ-NP-Z2-9]{2}$/;

// Django's User.username is set to the email address at registration
// (App.jsx handleSignup: `username: signupData.email`) — there is no
// separate username field anywhere in the UI. Callers must pass the same
// `email` value wherever a "username" is needed downstream (recovery
// forms, `advance_time_lock`).
async function signupUser(page, { email, password }) {
  await page.goto(`${BASE_URL}/signup`);
  // /signup still renders the LOGIN form first (isLoginMode starts true);
  // the signup form only appears after clicking the "Sign Up" tab.
  await page.getByRole('button', { name: 'Sign Up', exact: true }).click();

  await page.fill('#signup-email', email);
  await page.fill('#signup-password', password);
  await page.fill('#signup-confirm-password', password);
  await page.getByRole('button', { name: 'Create Free Account' }).click();

  // handleSignup() only registers the account then flips back to the
  // login form (setIsLoginMode(true)) — it does NOT log the user in.
  // A second, explicit login is required to actually authenticate.
  await page.waitForSelector('#login-email');
  await page.fill('#login-email', email);
  await page.fill('#login-password', password);
  await page.getByRole('button', { name: 'Login to Vault' }).click();

  // Login is a pure React-state transition (no client-side navigation),
  // so wait for the token useAuth persists rather than a URL change.
  await page.waitForFunction(
    () => !!window.localStorage.getItem('accessToken'),
    { timeout: 15000 },
  );
}

async function logout(page) {
  // Try the user menu logout button; fall back to clearing storage.
  const logoutButton = page.getByRole('button', { name: /log\s*out/i }).first();
  if (await logoutButton.isVisible().catch(() => false)) {
    await logoutButton.click();
  } else {
    await page.evaluate(() => {
      window.localStorage.clear();
      window.sessionStorage.clear();
    });
    await page.goto(`${BASE_URL}/`);
  }
}


test.describe('Layered Recovery — Tier 1 (Recovery Key)', () => {
  test('enroll, logout, recover, vault still readable', async ({ page }) => {
    // isValidEmail's dev/test-user carve-out (App.jsx) accepts any
    // "@...test..." address outside production; @gmail.com is otherwise
    // required, which a disposable e2e address can't satisfy.
    const email = `tier1-${Date.now()}@test.com`;
    const password = 'OldMasterPw1!';
    const newPassword = 'NewMasterPw2!';

    // Capture outgoing request bodies for the network-ZK assertion.
    const seenBodies = [];
    page.on('request', (req) => {
      const body = req.postData();
      if (body) seenBodies.push(body);
    });

    await signupUser(page, { email, password });

    await page.goto(`${BASE_URL}/recovery/key/enroll-v2`);
    await page.fill('[data-testid="rk-enroll-master-password"]', password);
    await page.click('[data-testid="rk-enroll-start"]');

    const keyText = await page.locator('[data-testid="recovery-key-display"]').innerText();
    expect(keyText.replace(/\s/g, '')).toMatch(RECOVERY_KEY_REGEX);

    await page.fill('[data-testid="rk-confirm-phrase"]', 'I have saved this key');
    await page.click('[data-testid="rk-enroll-save"]');
    await expect(page.locator('[data-testid="rk-enroll-success"]')).toBeVisible();

    // ── NETWORK-ZK ASSERTION ────────────────────────────────────────
    // The recovery key was generated client-side and shown on screen,
    // but it must NEVER appear in any outgoing request body.
    for (const body of seenBodies) {
      expect(body).not.toMatch(RECOVERY_KEY_REGEX);
      expect(body).not.toContain(keyText);
      const compact = keyText.replace(/-/g, '');
      expect(body).not.toContain(compact);
    }

    await logout(page);

    await page.goto(`${BASE_URL}/recovery/key/use-v2`);
    await page.fill('[data-testid="rk-use-username"]', email);
    await page.fill('[data-testid="rk-use-input"]', keyText);
    await page.click('[data-testid="rk-use-recover"]');

    await page.fill('[data-testid="rk-use-new-password"]', newPassword);
    await page.fill('[data-testid="rk-use-confirm-new-password"]', newPassword);
    await page.click('[data-testid="rk-use-set-password"]');

    await expect(page.locator('[data-testid="rk-use-success"]')).toBeVisible();
  });
});


test.describe('Layered Recovery — Tier 3 (Time-Locked)', () => {
  test('enroll, initiate, fast-forward, release, recover', async ({ page }) => {
    const email = `tier3-${Date.now()}@test.com`;
    const password = 'Tier3MasterPw!';
    const newPassword = 'Tier3NewPw!';

    await signupUser(page, { email, password });

    // Capture the .dlrec download produced during enrollment.
    const downloadPromise = page.waitForEvent('download');
    await page.goto(`${BASE_URL}/recovery/time-lock/enroll`);
    await page.fill('[data-testid="tl-enroll-master-password"]', password);
    await page.click('[data-testid="tl-enroll-generate"]');
    const download = await downloadPromise;
    const dlrecPath = await download.path();
    expect(dlrecPath).toBeTruthy();
    await page.click('[data-testid="tl-enroll-confirm"]');
    await expect(page.locator('[data-testid="tl-enroll-success"]')).toBeVisible();

    await logout(page);

    await page.goto(`${BASE_URL}/recovery/time-lock/recover`);
    await page.fill('[data-testid="tl-recover-username"]', email);
    await page.setInputFiles('[data-testid="tl-recover-file"]', dlrecPath);
    await page.click('[data-testid="tl-recover-begin"]');

    // Fast-forward release_after via Django mgmt command. advance_time_lock
    // does `User.objects.get(username=...)`, and username == email (see
    // signupUser above), so the full address must be passed here too. The
    // runner resolves the management command path relative to repo root.
    const repoRoot = path.resolve(__dirname, '..', '..');
    execSync(
      `python manage.py advance_time_lock ${email} --hours 169`,
      { cwd: path.join(repoRoot, 'password_manager'), stdio: 'inherit' },
    );

    await page.click('[data-testid="tl-recover-poll"]');
    await page.fill('[data-testid="tl-recover-new-password"]', newPassword);
    await page.fill('[data-testid="tl-recover-confirm-new-password"]', newPassword);
    await page.click('[data-testid="tl-recover-set-password"]');
    await expect(page.locator('[data-testid="tl-recover-success"]')).toBeVisible();
  });
});


test.describe('Layered Recovery — Tier 2 (Social Mesh)', () => {
  test.skip('multi-actor handshake — covered by existing social-recovery e2e', () => {});
});
