# Generated by Django 4.2.27 on 2026-02-07 13:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CognitiveSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enable_scrambled', models.BooleanField(default=True, help_text='Enable scrambled recognition challenges')),
                ('enable_stroop', models.BooleanField(default=True, help_text='Enable Stroop-effect challenges')),
                ('enable_priming', models.BooleanField(default=True, help_text='Enable priming tests')),
                ('enable_partial', models.BooleanField(default=True, help_text='Enable partial reveal challenges')),
                ('preferred_difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('verify_on_login', models.BooleanField(default=False, help_text='Require cognitive verification on every login')),
                ('verify_on_sensitive_actions', models.BooleanField(default=True, help_text='Require verification for sensitive actions')),
                ('periodic_verification_days', models.IntegerField(default=30, help_text='Days between periodic re-verification (0 = disabled)')),
                ('extended_time_limit', models.BooleanField(default=False, help_text='Allow extra time for responses')),
                ('high_contrast_mode', models.BooleanField(default=False, help_text='Use high contrast visuals for challenges')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cognitive_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cognitive Settings',
                'verbose_name_plural': 'Cognitive Settings',
            },
        ),
        migrations.CreateModel(
            name='CognitiveSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vault_item_id', models.UUIDField(blank=True, help_text='Optional: specific vault item being verified', null=True)),
                ('verification_context', models.CharField(choices=[('login', 'Login Verification'), ('high_security', 'High Security Action'), ('recovery', 'Account Recovery'), ('periodic', 'Periodic Re-verification'), ('suspicious', 'Suspicious Activity')], default='login', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('passed', 'Passed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('total_challenges', models.IntegerField(default=5, help_text='Total number of challenges in this session')),
                ('challenges_completed', models.IntegerField(default=0)),
                ('challenges_passed', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(help_text='Session expiration time')),
                ('overall_score', models.FloatField(default=0.0, help_text='Overall verification score (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('confidence', models.FloatField(default=0.0, help_text='Confidence in the verification result', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('creator_probability', models.FloatField(default=0.0, help_text='Probability that the responder is the password creator', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('device_fingerprint', models.CharField(blank=True, max_length=256)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cognitive_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cognitive Session',
                'verbose_name_plural': 'Cognitive Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CognitiveProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('baseline_reaction_time_mean', models.FloatField(default=0.0, help_text='Mean reaction time in ms for correct recognitions')),
                ('baseline_reaction_time_std', models.FloatField(default=0.0, help_text='Standard deviation of reaction times')),
                ('scrambled_baseline', models.JSONField(default=dict, help_text='Baseline metrics for scrambled recognition tests')),
                ('stroop_baseline', models.JSONField(default=dict, help_text='Baseline metrics for Stroop-effect tests')),
                ('priming_baseline', models.JSONField(default=dict, help_text='Baseline metrics for priming tests')),
                ('partial_baseline', models.JSONField(default=dict, help_text='Baseline metrics for partial reveal tests')),
                ('calibration_challenges_completed', models.IntegerField(default=0, help_text='Number of calibration challenges completed')),
                ('is_calibrated', models.BooleanField(default=False, help_text='Whether the profile has sufficient calibration data')),
                ('last_calibration_at', models.DateTimeField(blank=True, help_text='When calibration was last updated', null=True)),
                ('profile_confidence', models.FloatField(default=0.0, help_text='Confidence level in profile accuracy (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('cognitive_fingerprint', models.CharField(blank=True, help_text='Encrypted hash of cognitive patterns', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cognitive_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cognitive Profile',
                'verbose_name_plural': 'Cognitive Profiles',
            },
        ),
        migrations.CreateModel(
            name='CognitiveChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('challenge_type', models.CharField(choices=[('scrambled', 'Scrambled Recognition'), ('stroop', 'Stroop Effect Test'), ('priming', 'Priming Test'), ('partial', 'Partial Reveal')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('sequence_number', models.IntegerField(help_text='Order of this challenge in the session')),
                ('challenge_data', models.JSONField(default=dict, help_text='Encrypted challenge stimulus data')),
                ('correct_answer_hash', models.CharField(help_text='Hash of the correct answer for verification', max_length=256)),
                ('time_limit_ms', models.IntegerField(default=5000, help_text='Maximum time allowed in milliseconds')),
                ('display_duration_ms', models.IntegerField(default=0, help_text='How long stimulus is displayed (0 = until response)')),
                ('is_presented', models.BooleanField(default=False)),
                ('presented_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='cognitive_auth.cognitivesession')),
            ],
            options={
                'verbose_name': 'Cognitive Challenge',
                'verbose_name_plural': 'Cognitive Challenges',
                'ordering': ['session', 'sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response_hash', models.CharField(help_text="Hash of the user's response", max_length=256)),
                ('is_correct', models.BooleanField(help_text='Whether the response was correct')),
                ('reaction_time_ms', models.IntegerField(help_text='Time from stimulus to response in milliseconds')),
                ('first_keystroke_ms', models.IntegerField(blank=True, help_text='Time to first keystroke (for typing responses)', null=True)),
                ('total_input_duration_ms', models.IntegerField(blank=True, help_text='Total time spent inputting response', null=True)),
                ('hesitation_count', models.IntegerField(default=0, help_text='Number of pauses during input')),
                ('correction_count', models.IntegerField(default=0, help_text='Number of corrections/backspaces')),
                ('confidence_score', models.FloatField(default=0.0, help_text='Calculated confidence based on timing patterns', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('eye_tracking_data', models.JSONField(blank=True, default=dict, help_text='Optional eye tracking metrics')),
                ('client_timestamp', models.BigIntegerField(help_text='Client-side timestamp in milliseconds')),
                ('server_received_at', models.DateTimeField(auto_now_add=True)),
                ('z_score', models.FloatField(default=0.0, help_text="Z-score compared to user's baseline")),
                ('is_anomalous', models.BooleanField(default=False, help_text='Whether this response is statistically anomalous')),
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='cognitive_auth.cognitivechallenge')),
            ],
            options={
                'verbose_name': 'Challenge Response',
                'verbose_name_plural': 'Challenge Responses',
            },
        ),
        migrations.CreateModel(
            name='PasswordCreationSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('password_hash', models.CharField(help_text='Hash of the password this signature is for', max_length=256)),
                ('vault_item_id', models.UUIDField(blank=True, help_text='Associated vault item if applicable', null=True)),
                ('creation_reaction_times', models.JSONField(default=list, help_text='Reaction times during password creation')),
                ('creation_typing_pattern', models.JSONField(default=dict, help_text='Typing rhythm during password creation')),
                ('element_associations', models.JSONField(default=dict, help_text='Semantic associations with password elements')),
                ('signature_hash', models.CharField(help_text='Cryptographic hash of the full cognitive signature', max_length=512)),
                ('signature_salt', models.CharField(help_text='Salt used in signature generation', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration for the signature', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cognitive_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Creation Signature',
                'verbose_name_plural': 'Password Creation Signatures',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='cognitive_a_user_id_cb0955_idx'), models.Index(fields=['password_hash'], name='cognitive_a_passwor_5ae9d2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='cognitivesession',
            index=models.Index(fields=['user', 'status'], name='cognitive_a_user_id_1c5ff6_idx'),
        ),
        migrations.AddIndex(
            model_name='cognitivesession',
            index=models.Index(fields=['created_at'], name='cognitive_a_created_f01a95_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cognitivechallenge',
            unique_together={('session', 'sequence_number')},
        ),
    ]
