# Generated by Django 5.1.15 on 2026-04-08 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationSession',
            fields=[
            ],
            options={
                'verbose_name': 'Verification Session',
                'verbose_name_plural': 'Verification Sessions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cognitive_auth.cognitivesession',),
        ),
    ]
