# Generated by Django 5.1.15 on 2026-04-19 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personality_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='moralframeworksnapshot',
            new_name='personality_profile_10a2ca_idx',
            old_name='pa_mfs_profile_created_idx',
        ),
        migrations.RenameIndex(
            model_name='personalityauditlog',
            new_name='personality_profile_b8efc7_idx',
            old_name='pa_audit_profile_idx',
        ),
        migrations.RenameIndex(
            model_name='personalityauditlog',
            new_name='personality_event_t_bf32a4_idx',
            old_name='pa_audit_event_idx',
        ),
        migrations.RenameIndex(
            model_name='personalitychallenge',
            new_name='personality_profile_c7a9ac_idx',
            old_name='pa_ch_profile_created_idx',
        ),
        migrations.RenameIndex(
            model_name='personalitychallenge',
            new_name='personality_status_f295a0_idx',
            old_name='pa_ch_status_expires_idx',
        ),
        migrations.RenameIndex(
            model_name='personalityquestion',
            new_name='personality_profile_f8b01c_idx',
            old_name='pa_q_profile_dim_idx',
        ),
        migrations.RenameIndex(
            model_name='personalityquestion',
            new_name='personality_expires_bc1f42_idx',
            old_name='pa_q_expires_idx',
        ),
        migrations.RenameIndex(
            model_name='personalityresponse',
            new_name='personality_challen_cff15c_idx',
            old_name='pa_resp_chal_sub_idx',
        ),
    ]
