# Generated by Django 5.1.15 on 2026-04-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_reputation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anchorbatch',
            name='adapter',
            field=models.CharField(help_text='Name of the AnchorAdapter that handled (or will handle) this batch.', max_length=32),
        ),
        migrations.AlterField(
            model_name='anchorbatch',
            name='merkle_root',
            field=models.CharField(help_text='0x-prefixed hex string of the 32-byte Merkle root.', max_length=66),
        ),
        migrations.AlterField(
            model_name='reputationaccount',
            name='score',
            field=models.IntegerField(default=0, help_text='Current reputation score. Incremented on accepted proofs, slashed on breach.'),
        ),
        migrations.AlterField(
            model_name='reputationaccount',
            name='tokens',
            field=models.BigIntegerField(default=0, help_text='Total reputation tokens minted to this user (monotonically non-decreasing).'),
        ),
        migrations.AlterField(
            model_name='reputationevent',
            name='leaf_hash',
            field=models.BinaryField(help_text='SHA-256 leaf committed in the merkle batch (32 bytes).'),
        ),
        migrations.AlterField(
            model_name='reputationproof',
            name='claimed_entropy_bits',
            field=models.PositiveIntegerField(help_text='Entropy threshold the proof claims the secret meets.'),
        ),
        migrations.AlterField(
            model_name='reputationproof',
            name='commitment',
            field=models.BinaryField(help_text='Provider-specific commitment payload.'),
        ),
        migrations.AlterField(
            model_name='reputationproof',
            name='scope_id',
            field=models.CharField(help_text='Opaque identifier for the password the proof is about (e.g. vault item ID).', max_length=128),
        ),
    ]
