# Generated by Django 4.2.16 on 2025-11-27 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_module', '0004_passkeyrecoverybackup_passkeyrecoveryattempt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KyberEncryptedPassword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(db_index=True, help_text="Service name (e.g., 'Google', 'GitHub')", max_length=255)),
                ('username', models.CharField(help_text='Username for the service', max_length=255)),
                ('url', models.URLField(blank=True, help_text='Service URL', max_length=2048, null=True)),
                ('kyber_ciphertext', models.BinaryField(help_text='Kyber KEM ciphertext (1088 bytes for Kyber-768)', max_length=2048)),
                ('aes_ciphertext', models.BinaryField(help_text='AES-256-GCM encrypted password data')),
                ('nonce', models.BinaryField(help_text='AES-GCM nonce (12 bytes)', max_length=32)),
                ('ephemeral_public_key', models.BinaryField(blank=True, help_text='Ephemeral public key for forward secrecy', max_length=1568, null=True)),
                ('encryption_version', models.IntegerField(default=1, help_text='Encryption scheme version')),
                ('algorithm', models.CharField(default='Kyber768-AES256-GCM', help_text='Full encryption algorithm identifier', max_length=100)),
                ('encrypted_metadata', models.BinaryField(blank=True, help_text='Additional encrypted metadata (notes, tags, etc.)', null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed', models.DateTimeField(auto_now=True, help_text='Last time password was accessed')),
                ('is_favorite', models.BooleanField(db_index=True, default=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Kyber Encrypted Password',
                'verbose_name_plural': 'Kyber Encrypted Passwords',
                'db_table': 'kyber_encrypted_passwords',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='KyberKeyPair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_key', models.BinaryField(help_text='CRYSTALS-Kyber-768 public key (1184 bytes)', max_length=1568)),
                ('private_key', models.BinaryField(help_text='CRYSTALS-Kyber-768 private key (2400 bytes) - encrypted at rest', max_length=3168)),
                ('key_version', models.IntegerField(db_index=True, default=1, help_text='Key version for rotation support')),
                ('algorithm', models.CharField(default='Kyber768', help_text='Kyber variant (Kyber512, Kyber768, Kyber1024)', max_length=50)),
                ('security_level', models.IntegerField(default=3, help_text='NIST security level (1, 3, or 5)')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this key is currently active')),
                ('is_compromised', models.BooleanField(default=False, help_text='Flag if key is suspected compromised')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_used', models.DateTimeField(auto_now=True, help_text='Last time key was used for encryption/decryption')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional key expiration time', null=True)),
                ('x25519_public_key', models.BinaryField(blank=True, help_text='Optional X25519 public key for hybrid mode', max_length=32, null=True)),
                ('x25519_private_key', models.BinaryField(blank=True, help_text='Optional X25519 private key for hybrid mode', max_length=32, null=True)),
                ('encryption_count', models.IntegerField(default=0, help_text='Number of times key used for encryption')),
                ('decryption_count', models.IntegerField(default=0, help_text='Number of times key used for decryption')),
            ],
            options={
                'verbose_name': 'Kyber Key Pair',
                'verbose_name_plural': 'Kyber Key Pairs',
                'db_table': 'kyber_keypairs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KyberSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('ciphertext', models.BinaryField(help_text='Kyber ciphertext from encapsulation')),
                ('encrypted_shared_secret', models.BinaryField(blank=True, help_text='Encrypted shared secret (if persisted)', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Kyber Session',
                'verbose_name_plural': 'Kyber Sessions',
                'db_table': 'kyber_sessions',
            },
        ),
        migrations.RenameIndex(
            model_name='passkeyrecoveryattempt',
            new_name='auth_module_user_id_efdfbb_idx',
            old_name='auth_module_pkra_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='passkeyrecoveryattempt',
            new_name='auth_module_initiat_40ac22_idx',
            old_name='auth_module_pkra_initiated_idx',
        ),
        migrations.RenameIndex(
            model_name='passkeyrecoverybackup',
            new_name='auth_module_user_id_31aeb8_idx',
            old_name='auth_module_pkr_user_active_idx',
        ),
        migrations.RenameIndex(
            model_name='passkeyrecoverybackup',
            new_name='auth_module_recover_a4762e_idx',
            old_name='auth_module_pkr_key_hash_idx',
        ),
        migrations.AlterField(
            model_name='passkeyrecoverybackup',
            name='encrypted_credential_data',
            field=models.BinaryField(help_text='Kyber + AES-GCM encrypted passkey credential data (public key, metadata)'),
        ),
        migrations.AddField(
            model_name='kybersession',
            name='keypair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='auth_module.kyberkeypair'),
        ),
        migrations.AddField(
            model_name='kybersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyber_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kyberkeypair',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyber_keypairs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kyberencryptedpassword',
            name='keypair',
            field=models.ForeignKey(blank=True, help_text='Reference to the Kyber keypair used for encryption', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encrypted_items', to='auth_module.kyberkeypair'),
        ),
        migrations.AddField(
            model_name='kyberencryptedpassword',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyber_passwords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='kybersession',
            index=models.Index(fields=['user', 'is_active'], name='kyber_sessi_user_id_f082d7_idx'),
        ),
        migrations.AddIndex(
            model_name='kybersession',
            index=models.Index(fields=['session_id'], name='kyber_sessi_session_8c9225_idx'),
        ),
        migrations.AddIndex(
            model_name='kybersession',
            index=models.Index(fields=['expires_at'], name='kyber_sessi_expires_0cf57f_idx'),
        ),
        migrations.AddIndex(
            model_name='kyberkeypair',
            index=models.Index(fields=['user', 'is_active'], name='idx_kyber_user_active'),
        ),
        migrations.AddIndex(
            model_name='kyberkeypair',
            index=models.Index(fields=['user', 'key_version'], name='idx_kyber_user_version'),
        ),
        migrations.AddIndex(
            model_name='kyberkeypair',
            index=models.Index(fields=['created_at'], name='idx_kyber_created'),
        ),
        migrations.AddIndex(
            model_name='kyberkeypair',
            index=models.Index(fields=['key_version', 'is_active'], name='idx_kyber_version_active'),
        ),
        migrations.AddIndex(
            model_name='kyberkeypair',
            index=models.Index(fields=['user', 'algorithm', 'is_active'], name='idx_kyber_user_algo_active'),
        ),
        migrations.AddConstraint(
            model_name='kyberkeypair',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'key_version'), name='unique_active_key_per_version'),
        ),
        migrations.AddIndex(
            model_name='kyberencryptedpassword',
            index=models.Index(fields=['user', 'service_name'], name='idx_kyber_pwd_user_service'),
        ),
        migrations.AddIndex(
            model_name='kyberencryptedpassword',
            index=models.Index(fields=['user', 'created_at'], name='idx_kyber_pwd_user_created'),
        ),
        migrations.AddIndex(
            model_name='kyberencryptedpassword',
            index=models.Index(fields=['user', 'is_deleted'], name='idx_kyber_pwd_user_deleted'),
        ),
        migrations.AddIndex(
            model_name='kyberencryptedpassword',
            index=models.Index(fields=['user', 'is_favorite'], name='idx_kyber_pwd_user_favorite'),
        ),
        migrations.AddIndex(
            model_name='kyberencryptedpassword',
            index=models.Index(fields=['encryption_version'], name='idx_kyber_pwd_enc_version'),
        ),
        migrations.AddConstraint(
            model_name='kyberencryptedpassword',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('user', 'service_name', 'username'), name='unique_service_username_per_user'),
        ),
    ]
