# Generated by Django 5.1.15 on 2026-04-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0005_kyber_optimization_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoveryauditlog',
            name='cryptographic_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hash of previous log entry', max_length=64),
        ),
    ]
