# Generated by Django 4.2.16 on 2025-11-19 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial_performance'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='apiperformancemetric',
            new_name='api_perform_timesta_6ec191_idx',
            old_name='api_perfor_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='apiperformancemetric',
            new_name='api_perform_endpoin_08fbae_idx',
            old_name='api_perfor_endpoin_idx',
        ),
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='error_logs_timesta_d668fd_idx',
            old_name='error_logs_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='error_logs_resolve_b97978_idx',
            old_name='error_logs_resolve_idx',
        ),
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='error_logs_excepti_fdc6ae_idx',
            old_name='error_logs_excepti_idx',
        ),
        migrations.RenameIndex(
            model_name='performancealert',
            new_name='performance_acknowl_724e86_idx',
            old_name='performanc_acknowl_idx',
        ),
        migrations.RenameIndex(
            model_name='performancealert',
            new_name='performance_severit_885d95_idx',
            old_name='performanc_severit_idx',
        ),
        migrations.RenameIndex(
            model_name='performancealert',
            new_name='performance_alert_t_91a987_idx',
            old_name='performanc_alert_t_idx',
        ),
        migrations.RenameIndex(
            model_name='performancemetric',
            new_name='performance_timesta_a0ff78_idx',
            old_name='performance_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='performancemetric',
            new_name='performance_path_f89275_idx',
            old_name='performance_path_me_idx',
        ),
    ]
