# Generated by Django 4.2.27 on 2026-01-16 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdversarialBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(help_text='SHA-256 hash of password for deduplication', max_length=64)),
                ('password_entropy', models.FloatField(help_text='Calculated entropy of the password')),
                ('password_length', models.IntegerField()),
                ('attack_score', models.FloatField(help_text="Attacker AI's success probability (0-1)")),
                ('defense_score', models.FloatField(help_text="Defender AI's protection score (0-1)")),
                ('estimated_crack_time_seconds', models.BigIntegerField(help_text='Estimated time to crack in seconds')),
                ('outcome', models.CharField(choices=[('defender_wins', 'Defender Wins'), ('attacker_wins', 'Attacker Wins'), ('draw', 'Draw'), ('ongoing', 'Ongoing')], default='ongoing', max_length=20)),
                ('attack_vectors_used', models.JSONField(default=list, help_text='List of attack vector IDs that were simulated')),
                ('defense_strategies', models.JSONField(default=list, help_text='List of defense strategies that were effective')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adversarial_battles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttackVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('dictionary', 'Dictionary Attack'), ('brute_force', 'Brute Force'), ('rule_based', 'Rule-Based Mutation'), ('pattern', 'Pattern Recognition'), ('markov', 'Markov Chain'), ('hybrid', 'Hybrid Attack'), ('social', 'Social Engineering'), ('rainbow', 'Rainbow Table')], max_length=20)),
                ('description', models.TextField()),
                ('technique_details', models.JSONField(default=dict, help_text='Technical details of the attack method')),
                ('base_success_rate', models.FloatField(default=0.1, help_text='Base probability of success (0-1)')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('vulnerable_patterns', models.JSONField(default=list, help_text='Password patterns vulnerable to this attack')),
                ('recommended_defenses', models.JSONField(default=list, help_text='Defenses that mitigate this attack')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserDefenseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_defense_score', models.FloatField(default=0.5, help_text='Current overall defense posture (0-1)')),
                ('historical_average_score', models.FloatField(default=0.5, help_text='Average defense score over time')),
                ('total_battles', models.IntegerField(default=0)),
                ('battles_won', models.IntegerField(default=0)),
                ('battles_lost', models.IntegerField(default=0)),
                ('common_vulnerabilities', models.JSONField(default=list, help_text='Common vulnerability patterns for this user')),
                ('strong_practices', models.JSONField(default=list, help_text='Security practices user does well')),
                ('recommendations_applied', models.IntegerField(default=0)),
                ('improvement_rate', models.FloatField(default=0.0, help_text='Rate of defense score improvement over time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_battle_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='defense_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Defense Profiles',
            },
        ),
        migrations.CreateModel(
            name='DefenseRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('action_items', models.JSONField(default=list, help_text='Specific actions user should take')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('viewed', 'Viewed'), ('applied', 'Applied'), ('dismissed', 'Dismissed')], default='pending', max_length=10)),
                ('estimated_strength_improvement', models.FloatField(default=0.0, help_text='Estimated improvement in defense score if applied')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('attack_vectors_addressed', models.ManyToManyField(blank=True, related_name='recommendations', to='adversarial_ai.attackvector')),
                ('battle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='adversarial_ai.adversarialbattle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defense_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='adversarial_user_id_888a7b_idx'), models.Index(fields=['priority', 'created_at'], name='adversarial_priorit_e231f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='AggregatedBreachPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(choices=[('length_distribution', 'Password Length Distribution'), ('char_class_combo', 'Character Class Combination'), ('common_prefix', 'Common Prefix Pattern'), ('common_suffix', 'Common Suffix Pattern'), ('keyboard_pattern', 'Keyboard Walk Pattern'), ('date_pattern', 'Date-Based Pattern'), ('leet_speak', 'Leet Speak Substitution'), ('dictionary_base', 'Dictionary Word Base')], max_length=30)),
                ('pattern_signature', models.CharField(help_text='Anonymized pattern identifier', max_length=100)),
                ('occurrence_count', models.IntegerField(default=0)),
                ('success_rate_against', models.FloatField(default=0.0, help_text='How often attacks succeed against this pattern')),
                ('pattern_features', models.JSONField(default=dict, help_text='Statistical features of the pattern')),
                ('first_observed', models.DateTimeField(auto_now_add=True)),
                ('last_observed', models.DateTimeField(auto_now=True)),
                ('is_trending', models.BooleanField(default=False)),
                ('trend_velocity', models.FloatField(default=0.0, help_text='Rate of increase in observations')),
                ('effective_attacks', models.ManyToManyField(blank=True, related_name='effective_against_patterns', to='adversarial_ai.attackvector')),
            ],
            options={
                'indexes': [models.Index(fields=['pattern_type', 'is_trending'], name='adversarial_pattern_98fa25_idx'), models.Index(fields=['occurrence_count'], name='adversarial_occurre_206661_idx')],
                'unique_together': {('pattern_type', 'pattern_signature')},
            },
        ),
        migrations.AddIndex(
            model_name='adversarialbattle',
            index=models.Index(fields=['user', 'created_at'], name='adversarial_user_id_a78a66_idx'),
        ),
        migrations.AddIndex(
            model_name='adversarialbattle',
            index=models.Index(fields=['outcome'], name='adversarial_outcome_2fb165_idx'),
        ),
    ]
